---
---

//Standoc

== Author info

`:technical-committee:`::
The name of the relevant technical committee.

[[fullname]] `:fullname{_i}:`::
The full name of a person who is a contributor to the document.
A second person is indicated by using a numeric suffix: `:fullname:`, `:fullname_2:`, `fullname_3:`, &c.
The same convention applies to all the following attributes.
(This and the other personal name attributes are not displayed in all standards.)

[[surname]] `:surname{_i}:`::
The surname of a person who is a contributor to the document.

[[givenname]] `:givenname{_i}:`::
The given name(s) of a person who is a contributor to the document.

`:initials{_i}:`::
The initials(s) of a person who is a contributor to the document.

[[role]] `:role{_i}:`::
The role of a a person who is a contributor to the document.
By default, they are coded as an `editor`; they can also be represented as an `author`.

`:affiliation{_i}:`::
The organization that a person who is a contributor to the document is affiliated with.

`:affiliation_abbrev{_i}:`::
The abbreviation of the organization that a person who is a contributor to the document
is affiliated with [added in https://github.com/metanorma/metanorma-standoc/releases/tag/v1.3.12].

`:affiliation_subdiv{_i}:`::
The subdivision of the organization that a person who is a contributor to the document
is affiliated with [added in https://github.com/metanorma/metanorma-standoc/releases/tag/v1.7.0].
Can be multiple (semicolon-delimited: processed via CSV, recognising quote marks).

`:address{_i}:`::
The organizational address of a person who is a contributor to the document.

`:contributor-uri{_i}:`::
The URI of a person who is a contributor to the document.

`:email{_i}:`::
The email of a person who is a contributor to the document.

`:phone{_i}:`::
The phone number of a person who is a contributor to the document.

`:fax{_i}:`::
The fax number of a person who is a contributor to the document.

`:subdivision:`::
The subdivision of the organization that is responsible for this
document [added in https://github.com/metanorma/metanorma-standoc/releases/tag/v1.6.1].

`:subdivision-abbr:`::
The abbreviation of the subdivision of the organization that is responsible for this
document [added in https://github.com/metanorma/metanorma-standoc/releases/tag/v1.6.1].

`:pub-address:`::
The address of the organization responsible for this document, if it overrides
the default. [added in https://github.com/metanorma/metanorma-standoc/releases/tag/v1.6.1]. +
+
[NOTE]
--
Each line in a multi-line address must end with `+ \`, e.g.

[source,adoc]
----
:pub-address: 1 Infinity Loop + \
California + \
United States of America
----
--

`:pub-phone:`::
The phone number of the organization responsible for this document, if it overrides
the default [added in https://github.com/metanorma/metanorma-standoc/releases/tag/v1.6.1].

`:pub-fax:`::
The fax number of the organization responsible for this document, if it overrides
the default [added in https://github.com/metanorma/metanorma-standoc/releases/tag/v1.6.1].

`:pub-email:`::
The email of the organization responsible for this document, if it overrides
the default [added in https://github.com/metanorma/metanorma-standoc/releases/tag/v1.6.1].

`:pub-uri:`::
The URI of the organization responsible for this document, if it overrides
the default [added in https://github.com/metanorma/metanorma-standoc/releases/tag/v1.6.1].
