---
---
//Standoc
//When to use visual appearance attriubutes? Common pitfalls? --> Discuss in an Explanation, for example a blog article and link here. 

== Visual appearance

`:body-font:`::
Font for body text; will be inserted into CSS, overriding the default set for
the particular Metanorma flavour.

`:header-font:`::
Font for headers; will be inserted into CSS, overriding the default set for
the particular Metanorma flavour.

`:monospace-font:`::
Font for monospace; will be inserted into CSS, overriding the default set for
the particular Metanorma flavour.

`:htmlstylesheet:`::
SCSS stylesheet to use for HTML output. Defaults to built-in template
for the particular Metanorma flavour.  Overriding is not recommended.

`:htmlstylesheet-override:`::
CSS stylesheet to use for HTML output. Is inserted after any built in
stylesheet for the particular Metanorma flavour, and can be used to
override it. [added in https://github.com/metanorma/metanorma-standoc/releases/tag/v1.8.7]

`:htmlcoverpage:`::
HTML template for cover page.
Defaults to built-in template for the particular Metanorma flavour.
Overriding is not recommended.

`:htmlintropage:`::
HTML template for introductory section.
Defaults to built-in template for the particular Metanorma flavour.
Overriding is not recommended.

`:scripts:`::
Javascript scripts for HTML output.
Defaults to built-in scripts for the particular Metanorma flavour.
Overriding is not recommended.

`:scripts-pdf:`::
Javascript scripts for HTML to PDF output.
Defaults to built-in scripts for the particular Metanorma flavour.
Overriding is not recommended.

`:wordstylesheet:`::
Primary SCSS stylesheet to use for Word output.
Defaults to built-in template for the particular Metanorma flavour.
Overriding is not recommended.

`:standardstylesheet:`::
Secondary SCSS stylesheet use for Word output.
Defaults to built-in template for the particular Metanorma flavour.
Overriding is not recommended.

`:htmlstylesheet-override:`::
CSS stylesheet to use for Word output. Is inserted after any built in
stylesheets for the particular Metanorma flavour, and can be used to
override them. [added in https://github.com/metanorma/metanorma-standoc/releases/tag/v1.8.7]

`:header:`::
Header and footer file for Word output.
Defaults to built-in template the particular Metanorma flavour.
Overriding is not recommended.

`:wordcoverpage:`::
Word template for cover page.
Defaults to built-in template for the particular Metanorma flavour.
Overriding is not recommended.

`:wordintropage:`::
Word template for introductory section.
Defaults to built-in template for the particular Metanorma flavour.
Overriding is not recommended.

`:ulstyle:`::
Word CSS selector for unordered lists in supplied stylesheets.
Defaults to value for built-in stylesheet.
Overriding is not recommended.

`:olstyle:`::
Word CSS selector for ordered lists in supplied stylesheets.
Defaults to value for built-in stylesheet.
Overriding is not recommended.

`:data-uri-image:`::
Encode all images in HTML output as inline data-URIs. Defaults to true.

`:smartquotes:`::
Apply "`smartquotes`" and other autoformatting to the XML output (and hence the downstream outputs)
(default: `true`).
+
** Smart quotes are not applied to the following type of text:
*** text in sourcecode
*** text in pseudocode
*** text in monospace.
** If this attribute is set to `false`, the AsciiDoc default is used to generate smart quotes:
`"&#x060; &#x060;"`, `'&#x060; &#x060;'`.
** The rules for smart formatting follow the
https://github.com/pbhogan/sterile[sterile] gem, and are given in
https://github.com/pbhogan/sterile/blob/main/lib/sterile/data/smart_format_rules.rb[smart_format_rules.rb].

`:toclevels`::
Number of table of contents levels to render (default: `2`).

`:htmltoclevels`::
Number of table of contents levels to render in HTML/PDF output; used
to override `:toclevels:` (default: `2`).

`:doctoclevels`::
Number of table of contents levels to render in DOC output; used to
override `:toclevels:` (default: `2`).

`:imagesdir`::
Directory in which images are located: all local image file locations
are prefixed with this directory. (Optional.)

`:break-up-urls-in-tables:`::
(for Word output only) If present, long strings in table cells
(longer than 30 characters) are broken up on rendering, to help
tables fit within the page width [added in
https://github.com/metanorma/metanorma-standoc/releases/tag/v1.3.25] +
+
--
NOTE: Due to limitations of Microsoft Word tables with long string
wrapping, this functionality is only applied to Word output [added in
https://github.com/metanorma/metanorma-standoc/releases/tag/v1.3.29].
--

`:sectionsplit:`::
(HTML output only) Treat the HTML output as a Metanorma collection,
with one web page per clause and annex [added in
https://github.com/metanorma/metanorma-standoc/releases/tag/v1.9.0].

`:sourcecode-markup-start:`::
Initial delimiter for markup inserted in sourcecode [added in
https://github.com/metanorma/metanorma-standoc/releases/tag/v1.7.4]

`:sourcecode-markup-end:`::
Final delimiter for markup inserted in sourcecode [added in
https://github.com/metanorma/metanorma-standoc/releases/tag/v1.7.4]

