---
layout: m3aawg-flavor
---

= Writing M3AAWG documents using Metanorma

== Document Attributes

[[note_general_doc_ref_doc_attrib_m3d]]
[NOTE]
====
The document attributes listed below are unique to Metanorma’s processing of M3AAWG documents.

For _common document attributes_, see link:/author/ref/document-attributes/[Document attributes reference] in general Metanorma author’s documentation. That page describes attributes that apply to all Metanorma flavors, not just M3AAWG.

For an _introduction to Metanorma AsciiDoc document attributes_ and how Metanorma uses them, see link:/author/topics/document-format/meta-attributes/[the corresponding topic].
====

`:status:`:: The document status. Synonym: `:docstage:`.
The permitted types are: `proposal`,
`working-draft`, `committee-draft`, `draft-standard`, `final-draft`,
`published`, `withdrawn`.

`:doctype:`:: The document type (see _M3D deliverables: The different types of
M3AAWG publications_) (mandatory). The permitted types are:
+
--
* policy
* best-practices
* supporting-document
* report
--

`:uri:`:: The document URI. Optional, included with document if present.

`:edition:`:: Used to capture document version.

== Markup

`+[keyword]#...#+`: encodes keywords, such as "MUST", "MUST NOT".
(They are formatted as `<span class="keyword">...</span>`.)
