---
layout: docs-base
html-class: docs-page
title: Running Metanorma in CI/CD environments
redirect_from:
  - /setup/cicd
---
Metanorma is often run on continuous integration (CI) and continuous deployment
(CD) environments.

== Running on CI/CD platforms

We currently support the following CI/CD platforms:

* GitHub Actions
* GitLab CI

=== Installation

Metanorma provides native packages installable on most major platforms and
these packages can be installed through a non-interactive console/terminal.
The full list is available link:/install/[here].

Metanorma also provides additional automated actions for the setup and running
of Metanorma on CI/CD testers.

=== GitHub Actions

The following GitHub Actions can be used to simplify a Metanorma CI workflow:

* Metanorma setup: link:https://github.com/marketplace/actions/setup-metanorma[`actions-mn/setup@v2`]

* Metanorma actions: link:https://github.com/actions-mn/cli[`actions-mn/cli/site-gen@main` and more]

You can use our link:https://github.com/metanorma/mn-samples-iso[repository with ISO samples] as a reference

=== GitLab CI

For GitLab CI, Metanorma provides a sample `.gitlab-ci.yml` workflow file
that demonstrates how to use the Metanorma docker container in the environment.

* https://github.com/metanorma/metanorma-build-scripts/blob/master/cimas-config/gh-actions/samples/.gitlab-ci.yml[Sample `.gitlab-ci.yml`]
