---
layout: docs-base
html-class: docs-page
title: Run Metanorma with Docker
redirect_from:
  - /setup/docker
---


This setup method works for all platforms that support the Docker container
framework.

[TIP]
====
This method is the recommended way of getting Metanorma installed.

Possible reasons to _avoid_ this method:

* Performance. Using Metanorma inside Docker container may be a bit slower.

====

. Pull the container:
+
[source,sh]
----
docker pull metanorma/metanorma
----
or
[source,sh]
----
docker pull metanorma/mn
----

. Specify the `:local-cache-only:` AsciiDoc attribute
in document header to speed up rendering (optional)

To render the document into HTML, Word and XML,
execute from within the directory containing the Metanorma document
(replacing `{my-document-path}` with your actual document's filename):

.Running the Metanorma container on macOS and Linux
[source,console]
--
docker run -v "$(pwd)":/metanorma/ -w /metanorma metanorma/metanorma metanorma compile -t {flavor} -x {output-formats} {my-document-path}
--
or for documents with manifest
[source,console]
--
docker run -v "$(pwd)":/metanorma/ -w /metanorma metanorma/metanorma metanorma site generate {my-document-dir} -o {output-directory} -c {manifest-yml} --agree-to-terms
--

.Running the Metanorma container on Windows
[source,console]
--
docker run -v "%cd%":/metanorma/ -w /metanorma metanorma/metanorma metanorma compile -t {flavor} -x {output-formats} {my-document-path}
--

You can speedup compilation by caching fonts between docker runs by passing extra docker volume. Check link:/author/topics/building/font-management[how to do this]

Also `metanorm compile ...` is not the only one command. There are much more, check link:/software/metanorma-cli/docs/usage/[usage section]


[TIP]
====
See https://github.com/metanorma/metanorma-docker[metanorma-docker] for more information.
====