---
layout: docs-base
html-class: docs-page
title: Getting started with Metanorma on on Linux
redirect_from:
  - /setup/linux
---

== Install Metanorma via Snap

https://snapcraft.io[Snap] is a package manager on Linux originating from
Ubuntu that allows excellent isolation between software installs.

It also happens that it is the easiest way to install Metanorma on Linux!

The https://snapcraft.io/metanorma[Metanorma Snap] package can be installed with
a single command:

[source,sh]
----
sudo snap install metanorma
----

If the Snap daemon, `snapd`, isn't available on your distribution, please
instead use the all-in-one install script described below for various platforms.


== Install Metanorma via setup scripts

=== Ubuntu

Run the following commands.

[source,sh]
----
sudo bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu.sh | bash"
curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/install-gems.sh | bash
----

=== CentOS

Run the following commands.

[source,sh]
----
sudo bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/centos.sh | bash"
curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/install-gems.sh | bash
----

TIP: You will need to have `curl` installed beforehand.

TIP: For details, please see the https://github.com/metanorma/metanorma-linux-setup[metanorma-linux-setup] repository.

For more information about `metanorma` CLI see the link:/software/metanorma-cli/docs/usage/[Usage page of Metanorma CLI]

