---
layout: docs-base
html-class: docs-page
title: Getting started with Metanorma on on Linux
redirect_from:
  - /setup/linux
---

== Install Ruby

Ruby is sometimes included with Linux. To see if you already have it (and check the version):

1. Open a console/terminal
2. Type `ruby -v`

If Ruby is installed, you'll see something like the following
[source, console]
----
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-linux]
----

If not, follow the official
https://www.ruby-lang.org/en/documentation/installation[Ruby installation guide].

== Install Metanorma via Snap

https://snapcraft.io[Snap] is a package manager on Linux originating from
Ubuntu that allows excellent isolation between software installs.

It also happens that it is the easiest way to install Metanorma on Linux!

The https://snapcraft.io/metanorma[Metanorma Snap] package can be installed with
a single command:

[source,sh]
----
sudo snap install metanorma
----

If the Snap daemon, `snapd`, isn't available on your distribution, please
instead use the all-in-one install script described below for various platforms.


== Install Metanorma via setup scripts

=== Ubuntu

Run the following commands.

[source,sh]
----
sudo bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu.sh | bash"
curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/install-gems.sh | bash
----

=== CentOS

Run the following commands.

[source,sh]
----
sudo bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/centos.sh | bash"
curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/install-gems.sh | bash
----

TIP: You will need to have `curl` installed beforehand.

TIP: For details, please see the https://github.com/metanorma/metanorma-linux-setup[metanorma-linux-setup] repository.


