---
layout: gb-flavor
---

= Output formats

[[note_general_doc_ref_output_formats_gb]]
NOTE: Output formats supported by Metanorma toolchain can be seen in link:/author/topics/output/output-formats/[Outputs] section in general Metanorma documentation.

The following outputs are generated.

* (Optional) An HTML preview generated directly from the AsciiDoc document,
using Metanorma AsciiDoc formatting.
** http://asciimath.org[AsciiMathML] is to be used for mathematical formatting.
Metanorma-GB uses the https://github.com/asciidoctor/asciimath[Ruby AsciiMath parser],
which is syntactically stricter than the common MathJax processor;
if you do not get expected results, try bracketing terms in your AsciiMathML
expressions.
* an XML representation of the document, intended as a document model for GB
International Standards.
* The XML representation is processed in turn to generate the following outputs
as end deliverable GB standard drafts:
** HTML
** Microsoft Word (.doc) — see link:../ms-word-output-caveats/[caveats]
