---
layout: tutorial
title: Metanorma introduction tutorial
---
This tutorial is a gentle introduction to Metanorma for first-time users. The course is as *flavor-agnostic* as possible and serves as a general introduction to Metanorma. You will learn about:

* The foundations of AsciiDoc and Metanorma
* Creating Metanorma documents
* Compiling Metanorma
* Troubleshooting

== Pre-requisites

Before you start, make sure you have link:/install[installed Metanorma] on your machine or use a Docker image. 

Docker contains all needed dependencies to use Metanorma to get you started. The tutorial will provide samples and assumes that you use Docker.

{% include next-lesson-button.html url="lessons/lesson-1/" content="Start tutorial »" %}

== After the course

After you've completed the course, download a https://github.com/orgs/metanorma/repositories?q=mn-templates[template document] to get started. 
Use the link:/flavors[flavor-specific documentation] to author standards according to your organization's rules. 
