---
layout: author-docs
title: Author’s documentation
article_header_title: Metanorma author’s documentation
html-class: overview
redirect_from:
  - /overview/
  - /docs/
---
:page-liquid:

---
layout: author-docs
title: Get started
description: >-
  Metanorma installation, samples, customization & usage tips.
html-class: getting-started

---

== Choose your starting point

If you'd like to *adopt Metanorma for your organization's standard & specification management workflows*,
the best starting point is to customize an existing processor that
matches your requirements best, such as Metanorma-ISO.

* link:/docs/[Learn more] about Metanorma's features
aiming to help organizations with management of standardization documents

* Check out link:/docs/customization/[Metanorma customization guidelines]

To *author documents compliant with the requirements of certain established standard bodies*,
you may already find an existing Metanorma processor:
see link:/flavors/[Metanorma’s officially supported document flavors]



// == [tbd]#Write your first standard#


+++
<div class="cta"><a class="button" href="/author/getting-started">Get started</a></div>
+++

+++
<div class="cta"><a class="button" href="/author/getting-started">Get started</a></div>
+++

+++
<div class="cta"><a class="button" href="/author/getting-started">Get started</a></div>
+++