---
layout: builder-docs
title: Builder’s documentation
html-class: overview
article_header_title: Builder’s documentation
---
:page-liquid:

This documentation is aimed at those who are using Metanorma 
to build document authoring workflows for their organization.

[NOTE]
====
It is assumed that you are familiar with HTML markup, CSS styling,
and basics of programming with Ruby.
====

[TIP]
====
If you are looking for documentation about *creating documents with Metanorma*,
see link:/author/[Author’s documentation].
====

Here’re some of the features that make Metanorma a good match
for corporate document publishing workflow:

[.feature-list]
* +++<abbr title="‘What you see is what you mean’">WYSIWYM</abbr>+++ semantic authoring
  with syntax based on AsciiDoc.

* Versionable document sources.

* Validation of document contents against a set of style rules,
  and document structure against a formal schema.

* Output in HTML, PDF and DOC formats with the flexibility to tune
  the appearance of rendered documents to align with your organization's requirements
  and branding.

* Multilingual support.
