---
layout: docs-base
html-class: docs-page
title: Contributing to Metanorma
---

Metanorma is a community effort for creating better standards
for everyone -- thanks to our committed partnering organizations
and fellow authors!

== For developers

The Metanorma core code and related projects are all hosted
at the https://github.com/metanorma[Metanorma GitHub organization]
as open-source software.

Any contribution (bugfixes, enhancements) would be much appreciated.

NOTE: A number of Metanorma flavors are required to follow stringent rules
set by SDO user organizations. Please understand that any changes that
may affect the applicability or validity of those rules may require
SDO approval.


== For technical writers

Metanorma has applied for support from the
https://developers.google.com/season-of-docs[Google Seasons of Docs]
program.

We are committed to making the application process and participation
accessible to everyone -- please feel free to reach out and we will
do our best to accommodate your needs.

If you are interested in participating in the GSoD program for Metanorma,
please apply at the https://github.com/metanorma/metanorma/discussions[Discussions page]
or directly contact open.source@ribose.com.

The Metanorma GSoD 2021 proposal is available
link:/blog/2021-03-26-metanorma-gsod-2021[here].
