---
layout: docs-base
html-class: docs-page
title: Contributing to Metanorma
---

Metanorma is a community effort for creating better standards
for everyone -- thanks to our committed partnering organizations
and fellow authors!

== For developers

The Metanorma core code and related projects are all hosted
at the https://github.com/metanorma[Metanorma GitHub organization]
as open-source software.

Any contribution (bugfixes, enhancements) will be appreciated.

NOTE: A number of Metanorma flavors are required to follow stringent rules
set by SDO user organizations. Please understand that any changes that
may affect the applicability or validity of those rules may require
SDO approval.


== For technical writers

If you are interested in contributing to Metanorma as a technical writer,
contact us on the
https://github.com/metanorma/discussions/discussions[Discussions page]
or directly contact open.source@ribose.com.

NOTE: The previous Metanorma GSoD 2021 program that has been concluded can be
referenced link:/blog/2021-03-26-metanorma-gsod-2021/[here].
