---
layout: develop-docs
title: Developer documentation
html-class: overview
article_header_title: Developer documentation
---
:page-liquid:

To build documents with Metanorma, you need to have the Metanorma
command-line toolchain installed. See link:/install/develop[Development installation].

The toolchain consists of `metanorma-cli` Ruby gem and its dependencies.

In general, these installation methods are recommended.

This documentation is aimed at those who are using Metanorma
to build document authoring workflows for their organization.

[NOTE]
====
It is assumed that you are familiar with HTML markup, CSS styling,
and basics of programming with Ruby.
====

[TIP]
====
If you are looking for documentation about *creating documents with Metanorma*,
see link:/author/[Author's documentation].
====

Here're some of the features that make Metanorma a good match
for document publishing workflows of a standards defining organization:

[.feature-list]
* +++<abbr title="What you see is what you mean">WYSIWYM</abbr>+++ semantic authoring
  with syntax based on AsciiDoc.

* Versionable document sources.

* Validation of document contents against a set of style rules,
  and document structure against a formal schema.

* Output in HTML, PDF and DOC formats with the flexibility to tune
  the appearance of rendered documents to align with your organization's requirements
  and branding.

* Multilingual support.
