---
layout: docs-base
html-class: docs-page
title: Setting up Metanorma
redirect_from:
  - /setup/
---

= Setting up Metanorma

The Metanorma command-line toolchain can be installed with any of the following
installation methods suitable for your platform.

== Platform-specific installation

Choose your platform:

* link:/setup/macos/[macOS]
* link:/setup/windows/[Windows]
* link:/setup/linux/[Linux]

== Platform-independent installation

The following installation methods are intended for skilled Metanorma experts
who develop on Metanorma or require automated actions.

* link:/setup/docker/[Docker]
+
[TIP]
.Installing via Docker
====
Docker is a platform-independent container engine. The official
https://hub.docker.com/u/metanorma[Metanorma Docker containers on Docker Hub]
provide a simple and consistent to run Metanorma, especially on
continuous integration (CI) environments.
====

* link:/software/metanorma-cli/[Ruby gem]
+
[TIP]
.Manual installation
====
Assuming you know what you’re doing, the
https://rubygems.org/gems/metanorma-cli[metanorma-cli] gem can be manually
installed.

You will have to take care of dependencies: an appropriate Ruby version,
plus other software depending on the end documents you’re building.

Refer to link:/software/metanorma-cli/docs/installation/[Metanorma CLI installation docs]
for details.
====

== Continuous delivery environments

Metanorma is often run on continuous integration (CI) and continuous deployment
(CD) environments.

* link:/setup/cicd[Using Metanorma with CI/CD at GitHub and GitLab]
