---
layout: docs-base
html-class: docs-page
title: Setting up Metanorma
redirect_from:
  - /setup/
---

= Setting up Metanorma

To build documents with Metanorma, you need to have the Metanorma
command-line toolchain installed.

The toolchain consists of `metanorma-cli` Ruby gem and its dependencies.

In general, these installation methods are recommended.

Platform-specific methods:

* macOS: via <<homebrew,Homebrew>>
* Linux: via the <<linux,all-in-one setup script>>
* Windows: via <<chocolatey,Chocolatey>>

Platform-independent methods:

* Docker: the <<docker-setup,Metanorma Docker container>>
* Ruby: install the native Ruby <<gems,metanorma-cli gem>>

[TIP]
====
.Full manual

Assuming you know what you’re doing, you can manually install the `metanorma-cli` gem.
You will have to take care of dependencies: an appropriate Ruby version,
plus other software depending on the end documents you’re building.

Refer to link:/software/metanorma-cli/docs/installation/[Metanorma CLI installation docs]
for details.
====


[[macos-setup]]
== macOS

[[homebrew]]
=== Using https://brew.sh/[Homebrew]

[source,sh]
----
brew tap metanorma/metanorma
brew install metanorma
----

This uses Metanorma's link:/software/homebrew-metanorma[Homebrew formula].

To install using the HEAD development version of the formula, run:

[source,sh]
----
brew install --HEAD https://raw.githubusercontent.com/metanorma/homebrew-metanorma/master/metanorma.rb
----


=== All-in-one script

Run the following for an automatic install
that would prepare a fresh system to work with Metanorma.

NOTE: This installs not just the Metanorma components, but also prerequisites
such as Homebrew and basic tools like Sublime Text.

This should take less than 15 minutes depending on your machine and Internet connection:

[source,sh]
----
bash <(curl -s https://raw.githubusercontent.com/metanorma/metanorma-macos-setup/master/metanorma-setup)
----


[[linux]]
== Linux

Linux setup uses all-in-one script. You need to have `curl` installed beforehand.

TIP: For details, please see the https://github.com/metanorma/metanorma-linux-setup[metanorma-linux-setup] repository.

=== Ubuntu

[source,sh]
----
sudo bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu.sh | bash"
curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/install-gems.sh | bash
----

=== CentOS

[source,sh]
----
sudo bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/centos.sh | bash"
curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/install-gems.sh | bash
----


[[windows]]
== Windows

[[chocolatey]]
=== Using https://chocolatey.org/[Chocolatey]

Execute the following:

[source,console]
----
Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
refreshenv
cinst msys2 --params "/NoUpdate" -y # install msys2 without system update
cinst metanorma -y
refreshenv
----

[TIP]
====
For LaTeX processing, a UTF-8 compatible command line interface is necessary.
If you are using the Windows default command line interpreter `cmd.exe`,
please do run `chcp 65001` before using Metanorma.
====

[TIP]
====
See
link:/blog/12-25-2018/metanorma-on-windows-via-chocolatey/[the blog post on Metanorma Chocolatey package]
for more background.
====


=== Docker installation shortcut

Run this command in your `cmd.exe` or `PowerShell` to install
the Metanorma Docker container and all prerequisites (see <<docker-setup>>):

[source,sh]
----
bitsadmin /transfer get https://raw.githubusercontent.com/metanorma/metanorma-windows-setup/master/install.bat %cd%\install.bat & .\install.bat
----



[[docker-setup]]
== Docker setup

This setup method works for all platforms that support the Docker container
framework.

[TIP]
====
This method is the recommended way of getting Metanorma installed.

Possible reasons to _avoid_ this method:

* Performance. Using Metanorma inside Docker container may be a bit slower.
* Building PDF deliverables.
Due to a pending bug (https://github.com/metanorma/metanorma-docker/issues/42[see metanorma-docker#42]),
building in PDF doesn’t currently work with Metanorma in Docker.
====

. Pull the container:
+
[source,sh]
----
docker pull metanorma/metanorma
----

. Specify the `:local-cache-only:` AsciiDoc attribute
in document header to speed up rendering (optional)

To render the document into HTML, Word and XML,
execute from within the directory containing the Metanorma document
(replacing `{my-document-path}` with your actual document's filename):

.Running the Metanorma container on macOS and Linux
[source,console]
--
docker run -v "$(pwd)":/metanorma/ -w /metanorma metanorma/metanorma metanorma compile -t {flavor} -x {output-formats} {my-document-path}
--

.Running the Metanorma container on Windows
[source,console]
--
docker run -v "%cd%":/metanorma/ -w /metanorma metanorma/metanorma metanorma compile -t {flavor} -x {output-formats} {my-document-path}
--

[TIP]
====
See https://github.com/metanorma/metanorma-docker[metanorma-docker] for more information.
====


[[gems]]
== Installing gems separately

See link:/software/metanorma-cli/[Metanorma CLI docs]
on how to install the Ruby gem on its own.
