---
layout: learn
title: Learn Metanorma
description: A series of tutorials to get you familiar with Metanorma.
---

NOTE: If you are completely unfamiliar with Metanorma, you've come to the right
place.

This is a gentle introduction to Metanorma for first-time users.

The course is as *flavor-agnostic* as possible and serves as a general
introduction to Metanorma.

You will learn about:

* Foundations of using Metanorma
* Creating documents
* Compiling documents
* Troubleshooting basics

== Prerequisites

* https://www.metanorma.org/install/[Install Metanorma]
+
TIP: Use Metanorma in Docker to get started faster.

* Download the https://github.com/metanorma/metanorma-tutorial[Metanorma tutorial project].

link:/learn/lessons/lesson-1/">Start tutorial »</a></div>
+++

== After the course

After you've completed the course, you will be ready to create Metanorma
documents on your own.

To get started, you can download a
https://github.com/orgs/metanorma/repositories?q=mn-templates[template document].

Look up any flavor-specific rules in the the link:/flavors[flavor documentation].
