---
layout: docs-base
html-class: docs-page
title: Quickstart
redirect_from:
  - /setup/
---

= Quickstart

To build documents with Metanorma, you need to have the Metanorma
command-line toolchain installed.

The toolchain consists of `metanorma-cli` Ruby gem and its dependencies.

In general, these installation methods are recommended.

Platform-specific methods:

* macOS: via our <<homebrew,Homebrew formula>>
* Linux: via our <<snap, Snapcraft package>>
* Windows: via our <<chocolatey,Chocolatey package>>

Platform-independent methods:

* Docker: the <<docker-setup,Metanorma Docker container>>
* Ruby: install the native Ruby <<gems,metanorma-cli gem>>

[TIP]
====
.Full manual

Assuming you know what you’re doing, you can manually install the `metanorma-cli` gem.
You will have to take care of dependencies: an appropriate Ruby version,
plus other software depending on the end documents you’re building.

Refer to link:/software/metanorma-cli/docs/installation/[Metanorma CLI installation docs]
for details.
====


[[installation]]
== Installation

[[macOS]]
=== Using https://brew.sh/[Homebrew]

[source,sh]
----
brew tap metanorma/metanorma
brew install metanorma
----

or

[source,sh]
----
brew install metanorma/metanorma/metanorma
----


[[linux]]
== Linux

[[snap]]
=== Using https://snapcraft.io[Snap]

The easiest way is to install the https://snapcraft.io/metanorma[Metanorma Snap]
with a single command:

[source,sh]
----
sudo snap install metanorma
----

If `snapd` isn't available on your distribution, use the all-in-one install script
described below for various platforms.
You will need to have `curl` installed beforehand.

TIP: For details, please see the https://github.com/metanorma/metanorma-linux-setup[metanorma-linux-setup] repository.


=== Install script for Ubuntu

The `curl` command must be installed.

[source,sh]
----
sudo bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu.sh | bash"
curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/install-gems.sh | bash
----


=== Install script for CentOS

The `curl` command must be installed.

[source,sh]
----
sudo bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/centos.sh | bash"
curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/install-gems.sh | bash
----


[[windows]]
== Windows

[[chocolatey]]
=== Using https://chocolatey.org/[Chocolatey]

To install `chocolatey` follow https://chocolatey.org/install[these instructions]

Execute the following in your `cmd.exe` or `PowerShell`
to install the Metanorma Chocolatey package:

[source,console]
----
choco install metanorma -y
----

[TIP]
====
For LaTeX processing, a UTF-8 compatible command line interface is necessary.
If you are using the Windows default command line interpreter `cmd.exe`,
please do run `chcp 65001` before using Metanorma.
====

[TIP]
====
See
link:/blog/12-25-2018/metanorma-on-windows-via-chocolatey/[the blog post on Metanorma Chocolatey package]
for more background.
====


[[docker-setup]]
== Docker setup

This setup method works for all platforms that support the Docker container
framework.

[TIP]
====
This method is the recommended way of getting Metanorma installed.

Possible reasons to _avoid_ this method:

* Performance. Using Metanorma inside Docker container may be a bit slower.

====

. Pull the container:
+
[source,sh]
----
docker pull metanorma/metanorma
----

. Specify the `:local-cache-only:` AsciiDoc attribute
in document header to speed up rendering (optional)

To render the document into HTML, Word and XML,
execute from within the directory containing the Metanorma document
(replacing `{my-document-path}` with your actual document's filename):

.Running the Metanorma container on macOS and Linux
[source,console]
--
docker run -v "$(pwd)":/metanorma/ -w /metanorma metanorma/metanorma metanorma compile -t {flavor} -x {output-formats} {my-document-path}
--

.Running the Metanorma container on Windows
[source,console]
--
docker run -v "%cd%":/metanorma/ -w /metanorma metanorma/metanorma metanorma compile -t {flavor} -x {output-formats} {my-document-path}
--

[TIP]
====
See https://github.com/metanorma/metanorma-docker[metanorma-docker] for more information.
====


[[gems]]
== Installing gems separately

See link:/software/metanorma-cli/[Metanorma CLI docs]
on how to install the Ruby gem on its own.

[[usecases]]
== Use-cases
Follow the links for your level of expertise with Metanorma:
[[new]]
== New User
If you are fairly new, follow these steps to get acquainted with our tool. 

[[experienced]]
== Experienced Users
If you have already used Metanorma, then probably you'd like to directly navigate to the Authoring Guide. Follow these steps. 

[[expert]]
== Expert
If you are well-versed with the tool, probably you belong to the developer level. Follow these steps to navigate to Developer Docs. 


