---
layout: ogc-flavor
title: Authoring guide for OGC documents
---
//If the structure of the authoring guide is fine, let's find a way how we can standardize it across SDO's and reuse information.

This authoring guide introduces you to editing Metanorma documents and the specifics of OGC.
//Use variables for flavor names.
To avoid trouble when you work with the material, link:_pages/install/[install the latest version of Metanorma].

== Scope

Follow these chapters to learn how to write and publish OGC documents:

. link:author/ogc/authoring-guide/metanorma-asciidoc/[Introduction to AsciiDoc]
. link:author/ogc/authoring-guide/new-doc-template/[Creating a new document from a template]
. link:author/ogc/authoring-guide/metadata/[Assigning metadata in the document header]
. link:author/ogc/authoring-guide/sections-ogc/[Typical sections in OGC]
. link:author/ogc/authoring-guide/block-syntax/[Asciidoc markup on the block-level]
. link:author/ogc/authoring-guide/inline-syntax/[Asciidoc markup on the inline-level]
. link:author/ogc/authoring-guide/terms-definitions/[Entering terms and definitions]
. link:author/ogc/authoring-guide/cross-references/[Entering references]
. link:author/ogc/authoring-guide/bibliographic-references/[Entering bibliography]
. link:author/ogc/topics/requirements/[Entering ModSpec sections]


== References

* Metanorma AsciiDoc

* https://docs.asciidoctor.org/asciidoc/latest/[AsciiDoc Language Documentation]

* http://asciimath.org/[AsciiMath markup reference]

* https://portal.ogc.org/files/?artifact_id=34762[OGC Specification Model — ModSpec (08-131r3)][]

== Terms and definitions

Specific terms used in this guide is defined in this section.

=== admonition

Statement used to draw the attention of the reader by labeling it with a priority tag. For example: WARNING, NOTE, TIP.

=== attribute

Name-value pair separated by an equal sign (`=`) to configure a localized part of the document.

=== boilerplate
_Also known as boilerplate text._

Predefined content that is automatically inserted into the output in accordance to flavor requirements.

=== clause
Also known as _section_.
Logical group of content that is numerically identified in ascending order.

=== cross-reference

Direct link to an internal location within the current AsciiDoc document or to another external AsciiDoc document. +
Source: link:https://docs.asciidoctor.org/asciidoc/latest/macros/xref/[].

=== document attribute

Name-value pair (`:name: value`) used as to configure the AsciiDoc processor. +
Source: link:https://docs.asciidoctor.org/asciidoc/latest/attributes/document-attributes/[].

=== flavor

Formatting required to author a specific standard. It receives the name of the non-profit organization in charge of publishing. E.g.: OGC, ISO, IEC, ITU, etc.

=== lists

List of text contents related to a common subject.

=== Metanorma AsciiDoc

Extended version of AsciiDoc markup language designed to ease the authoring of standards.

=== subclause (or subsection)

Content separator embedded recursively in clauses, numerically identified in ascending order until certain level depending of the flavor.

=== template

file(s) that serve as guidance to author a specific document type in OGC flavor
