---
layout: ogc-flavor
---

= Writing OGC documents using Metanorma

== Document type and stage

[[note_general_doc_ref_doc_attrib_ogc]]
[NOTE]
====
Document attributes listed below are unique to the processing of OGC documents in Metanorma.

For _common document attributes_, see link:/author/ref/document-attributes/[Document attributes reference] in general Metanorma author’s documentation. That page describes attributes that apply to all Metanorma flavors, not just OGC.

For an _introduction to Metanorma AsciiDoc document attributes_ and how Metanorma uses them, see link:/author/topics/document-format/meta-attributes/[the corresponding topic].
====

`:doctype:`::
*Mandatory.*
Document type. Choices:
+
--
* `standard`: Standard (a document subtype is necessary, see <<ogc-docsubtype>>) (_default_)
* `abstract-specification-topic`: Abstract Specification
* `best-practice`: Best Practice (a document subtype is necessary, see <<ogc-docsubtype>>)
* `change-request-supporting-document`: Change Request Supporting Document
* `community-practice`: Community Practice
* `community-standard`: Community Standard
* `discussion-paper`: Discussion Paper
* `engineering-report`: Engineering Report
* `other`: Note, Primer, etc.
* `policy`: Policy, Policy -- Name Type Specification
* `reference-model`: Reference Model
* `release-notes`: Release Notes
* `test-suite`: Test Suite
* `user-guide`: User Guide
* `white-paper`: White Paper
--

[[ogc-docsubtype]]
`:docsubtype:`:: Document subtype.
Choices:
+
--
* For `doctype` set to `standard`:
** `implementation`: Implementation (_default_)
** `conceptual-model`: Conceptual model
** `conceptual-model-and-encoding`: Conceptual model and encoding
** `conceptual-model-and-implementation`: Conceptual model and implementation
** `encoding`: Encoding
** `extension`: Extension
** `profile`: Profile
** `profile-with-extension`: Profile with extension

* For `doctype` set to `best-practice`:
** `general`: General (_default_)
** `encoding`: Encoding
** `extension`: Extension
** `profile`: Profile
** `profile-with-extension`: Profile with extension
--

`:status:`::
Document status/stage. Synonym: `:docstage:`.
Choices:
+
--
* `swg-draft`: SWG Draft. This is the draft created after the TC approval and PC approval votes.
* `oab-review`: OAB Review. This is the intended draft for the "`OAB + OGC-NA Review`".
* `public-rfc`: Public RFC. This is the draft for the (30 days) public comment period.
* `tc-vote`: TC Vote. This is the intended draft for the TC adoption and PC adoptioin votes.
* `published`: Published. This is the document intended to be published, after comments are handled with the TC chair (after `tc-vote`).
* `deprecated`: Deprecated. This document has been deprecated.
* `retired`: Retired. This document has been retired and no longer considered normative.
--


`:keywords:`::
Comma-delimited list of the keywords associated with the document.

[NOTE]
--
Abbreviations are sometimes used to designate that a document has a
certain document type, document subtype and document stage.
This is a mapping from legacy OGC document values to the current normalized
list:

"`AS`" Abstract Specification:: Now `:doctype: abstract-specification-topic`.
"`BP`" Best Practice:: Now `:doctype: best-practice`.
"`CAN`" Candidate Standard:: Now `:doctype: standard` and `:docstage: swg-draft`.
"`CC`" Conformance Class:: Not a standalone document, but a part of a document with `:doctype: standard`. No longer exists.
"`CR`" Change Request:: Now `:doctype: change-request-supporting-document`; the actual Change Request is a database entry.
"`CS`" Community Standard:: Now `:doctype: community-standard`.
"`CP`" Community Practice:: Now `:doctype: community-practice`.
"`DP`" Discussion Paper:: Now `:doctype: discussion-paper`.
"`DP-Draft`" Draft Discussion Paper:: Now `:doctype: discussion-paper` with `:docstage: swg-draft`.
"`IPR`" Interoperability Program Report -- Engineering Specification:: Now `:doctype: engineering-report`.
"`IS`" Implementation Standard:: Now `:doctype: standard`, `:docsubtype: implementation`.
"`ISC`" Implementation Standard Corrigendum:: Now `:doctype: standard`, `:docsubtype: implementation` (TBD to indicate `corrigendum`).
"`ISx`" Extension Package Standard:: Now `:doctype: standard`, `:docsubtype: extension`.
"`Notes`" Notes:: Now `:doctype: other`, there is no specific type for "`Notes`".
"`ORM`" OGC Reference Model:: Now `:doctype: reference-model`.
"`PC`" Profile Corrigendum:: Now `:doctype: standard`, `:docsubtype: profile` (TBD to indicate `corrigendum`).
"`PER`" Public Engineering Report:: Now `:doctype: engineering-report`.
"`POL`" Policy:: Now `:doctype: policy`.
"`POL-NTS`" Policy -- Name Type Specification:: Now `:doctype: engineering-report`, there is no specific indication for "`NTS`".
"`Primer`" Primer:: Now `:doctype: other`, there is no specific type for "`Primer`".
"`Profile`" Profile:: Now `:doctype: standard`, `:docsubtype: profile`.
"`RFC`" Request for Comment:: Now `:doctype: standard` and `:docstage: public-rfc`.
"`Retired`" Retired document:: This is a document stage indicated `:docstage: retired`.
"`SAP`" Standard Application Profile:: Now `:doctype: standard`, `:docsubtype: profile`.
"`TS`":: Test Suite (TBD)
"`WhitePaper`" Whitepaper:: Now `:doctype: white-paper`.
--

=== Author info

`:committee:`::
*Mandatory.*
Name of relevant committee producing the document. Use one of:
+
--
* `technical`: Technical Committee
* `planning`: Planning Committee
* `strategic-member-advisory`: Strategic Member Advisory Committee
--

`:subcommittee-type:`::
The type of the relevant subcommittee producing the document.

`:subcommittee-number:`::
The number of the relevant subcommittee producing the document.

`:workingGroup:`::
*Mandatory.*
Name of relevant working group producing the document.

`:workgroup-type:`::
Type of the relevant workgroup producing the document.

`:workgroup-number:`::
Number of the relevant workgroup producing the document.

`:submitting-organizations:`::
Semicolon-delimited list of the submitting organizations
for this document. The organization names themselves may contain commas.
+
[example]
--
EXAMPLE: _University of Calgary, Canada; National Central University, Taiwan_
--

`:editor:`::
Same as `link:/author/ref/document-attributes/#fullname[:fullname:]`
alongside `link:/author/ref/document-attributes/#role[:role:]` specified as `editor`.


=== URIs and IDs

`:external-id:`::
External identifier referring to this document.

`:referenceURLID:`::
Identifier embedded into a document type-specific external URL.

`:previous-uri:`::
URI of previous version of the document.

=== Mapping to OGC legacy AsciiDoc

Metanorma-OGC permits legacy OGC AsciiDoc template attributes,
and are treated as synonyms of the corresponding Metanorma attributes:

|===
| OGC Metanorma AsciiDoc                    | OGC legacy AsciiDoc

| `:copyright-year:`                        | `:copyrightYear`
| `:workgroup:`                             | `:workingGroup:`
| `:published-date:`                        | `:publicationDate:`
| `:issued-date:`                           | `:approvalDate:`
| `:received-date:`                         | `:submissionDate:`
| `:docnumber:`                             | `docReference`
| `:fullname:`, with `:role:` = `editor`    | `editor`

|===

== Markup

=== Sections

The Normative References section may be named just "`References`", reflecting OGC practice.

=== Preliminary elements

==== General

The following clauses are preliminary elements, and are moved into the frontispiece
of the document (in Metanorma, the document preface):

* Abstract
* Keywords
* Preface
* Submitting Organizations
* Submitters

Note that in OGC documents, all these elements are *MANDATORY*.


==== Abstract

The abstract is recognized as the first clause with an `abstract` style attribute:

[source,asciidoc]
----
[abstract]
== Abstract

This standard describes a conceptual and logical model for the exchange
of groundwater data, as well as a GML/XML encoding with examples.
----

==== Preface

The "`Preface`" is recognized as the text after the `.Preface` label, placed
between the AsciiDoc document attributes and
the first AsciiDoc section title; it should not be given a section title of its own.

[source,asciidoc]
----
:received-date: 2019-01-01

.Preface

preface text
----

Alternatively, the "`Preface`" is recognised as a clause with the title
"Preface". [added in https://github.com/metanorma/metanorma-ogc/releases/tag/v1.0.1]

[source,asciidoc]
----
:received-date: 2019-01-01

== Preface

preface text
----


==== Keywords

"`Keywords`" are entered as document attributes as `:keywords:`, with the
value as a comma-delimited list.

Prefatory text is generated automatically.

EXAMPLE:

[source,adoc]
----
:keywords: ogcdoc, OGC document, groundwater, hydrogeology, GWML2
----


==== Submitting Organizations

"`Submitting Organizations`" are entered using the `:submitting-organizations:` document attribute.
The values are entered using a semi-colon delimited list.

Prefatory text is generated automatically.

EXAMPLE:

[source,adoc]
----
:submitting-organizations: Geological Survey of Canada (GSC), Canada; U.S. Geological Survey (USGS), United States of America
----


==== Submitters

"`Submitters`" are entered using a table, contained in a section with the title `Submitters`.

EXAMPLE:

[source,adoc]
----
== Submitters

|===
|Name |Affiliation |OGC member

|Steve Liang | University of Calgary, Canada / SensorUp Inc. | Yes
|===
----

EXAMPLE:

[source,adoc]
----
== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

|===
|Name |Affiliation

|Boyan Brodaric |GSC
|Alexander Kmoch |U Salzburg
|===
----


=== Examples

Unlike the normal case in Metanorma, examples can have captions:

[source,asciidoc]
----
[example]
.Example caption
====
Text
====
----

=== Recommendations, requirements, and permissions

In this clause we will use the term "`requirement`" to refer to the
generic class of recommendations, requirements and permissions.

NOTE: This subsection supplements
link:/author/topics/document-format/requirements-recommendations-permissions[Requirement, Recommendation, and Permission blocks]
in general Metanorma documentation.

==== Requirement verifications (tests)

A requirement with `type=verification` are cross-referenced and captioned as
a "`{Requirement} Test`", and are rendered differently from the
actual requirement itself.

NOTE: Verifications for Recommendations will be captioned as
Recommendation Tests, similarly for Requirement Tests and
Permission Tests.

Requirement verifications are excluded from the
"`Table of Requirements`" in Word output
[added in https://github.com/metanorma/metanorma-ogc/releases/tag/v0.2.10].

==== Requirement classes

A requirement with `type=class` are cross-referenced and captioned as
a "`{Requirement} Class`", and are rendered differently the actual
requirement itself
[added in https://github.com/metanorma/metanorma-ogc/releases/tag/v0.2.11].

NOTE: Classes for Recommendations will be captioned as
Recommendation Classes, similarly for Requirement Classes and
Permission Classes.

Requirement Classes must use the following Metanorma Requirement attributes:

* Target Type. Specified in the `subject` attribute.
* Name. Specified as the requirement's title.
* Dependencies (optional). Specified with the `inherit` attribute (which can take multiple semicolon-delimited values).
* Nesting (optional). Requirements contained in a class are presented as nested requirements.

[example]
========
[source,asciidoc]
--
[requirement,type="class",label="http://www.opengis.net/spec/waterml/2.0/req/xsd-xml-rules[*req/core*]",obligation="requirement",subject="Encoding of logical models",inherit="urn:iso:dis:iso:19156:clause:7.2.2;urn:iso:dis:iso:19156:clause:8;http://www.opengis.net/doc/IS/GML/3.2/clause/2.4;O&M Abstract model, OGC 10-004r3, clause D.3.4;http://www.opengis.net/spec/SWE/2.0/req/core/core-concepts-used"]
.GWML2 core logical model
====

[requirement,type="general",label="/req/core/encoding"]
======
======

[requirement,type="general",label="/req/core/quantities-uom"]
======
======

[recommendation,type="general",label="/req/core/codelist"]
======
======

[requirement,type="general",label="/req/core/codelistURI"]
======
======

[requirement,type="general",label="/req/core/identifier"]
======
======

[requirement,type="general",label="/req/core/feature"]
======
======

====
--
========

==== Legacy Metanorma AsciiDoc syntax

For legacy reasons, a second Metanorma AsciiDoc syntax is permitted for
recommendations, requirements and permissions.

In this syntax, Metanorma AsciiDoc tables are used to express the
data needed for requirements:

* Type of requirement. Specified in the first table cell,
  one of `Recommendation`, `Requirement` or `Permission`.
  Optionally followed by a number
  (which is ignored in parsing; the elements are renumbered
  automatically in rendering.)
* Internal label. First paragraph of the second table cell.
* Body of requirement. Second and subsequent paragraphs of the second table cell.

[example]
====
[source,asciidoc]
----
[[recommendation1]]
|===
|Recommendation |/ogc/recommendation/wfs/2 +

If the API definition document uses the OpenAPI Specification 3.0,
the document SHOULD conform to the
<<rc_oas30,OpenAPI Specification 3.0 requirements class>>.
|===
----
====

