---
layout: ogc-flavor
title: Entering bibliography
---
//General Bibliography
//include::/author/topics/sections/entering_bib.adoc[tag=tutorial]

Most standard documents contain two sections with bibliographic references, namely the “normative references” and the “bibliography” (informative references).
Every bibliographic section must be preceded by the style attribute `[bibliography]` so that bibliographic references are recognized as such. 

== Entering a bibliographic entry
To enter a reference entry:

. Start a new unordered list (`*`) item. 
. Enter triple square brackets (`[[[]]]`) which contain:
+
* The anchor name used to reference this entry
* A document identifier

+
.Syntax for a bibliographic entry
[source, AsciiDoc]
----
* [[[anchor,document identifier or reference tag]]], _reference list text_
----

. After the triple brackets, you may include the reference text in italics, for example the title of the document. 
+
NOTE: Metanorma uses https://www.relaton.org/[Relaton] to link:author/concepts/automatic-reference-lookup.adoc[automatically fetch resource descriptions] from the SDO's web site. If Metanorma recognizes a document identifier, it will overwrite any title you provide with the authoritative title of the reference. 

== Referencing a bibliographic entry
To cite an entry from your bibliography:app-name: 

. Enter the anchor name like this: `\<<ISO20483>>`.
. To specify a location within the cited document, you can add https://www.metanorma.org/author/topics/document-format/bibliography/#localities[localities] in the brackets like so: `\<<ISO20483, part=IV,chapter=3,paragraph=12>>`.

== Bibliography example

The following code sample illustrates how a bibliography section looks like in AsciiDoc Metanorma. 

.Example for a bibliography section
[source, AsciiDoc]
----
[bibliography]
== Normative references

* [[[ISO20483,ISO 20483:2013]]], _Cereals and cereal products -- Determination of moisture content -- Reference method_
* [[[ISO6540,ISO 6540:1980]]]. _Maize -- Determination of moisture content (on milled grains and on whole grains)_
----
Gets rendered as:

* ISO 20483:2013. _Cereals and cereal products — Determination of moisture content — Reference method_
* ISO 6540:1980. _Maize — Determination of moisture content (on milled grains and on whole grains)_


//OGC specific
== Auto-fetching OGC references

Relaton fetches bibliographic entries for OGC documents, when the syntax matches the following:

//Line 62 stems from https://www.metanorma.org/author/topics/building/reference-lookup/. To me, the parenthesis are a bit confusing. In which context do we use it?
`OGC(identifier)` (e.g. `OGC(14-083r2)`, `OGC 14-083r2`), or any identifier prefixed with `OGC`

If Relaton *can* resolve the reference, the bibliographic information from the database will be rendered.

If Relaton *can not* resolve the reference, the provided description will be rendered. 

.Example of a OGC standard reference
[source,asciidoc]
----
* [[[OGC12-080r2,OGC 12-080r2]]], OGC OWS Context Conceptual Model, 2013-09-01, https://portal.opengeospatial.org/files/?artifact_id=55182
----

it will render:
____
Roger Brackin, Pedro Gonçalves : OGC 12-080r2, OGC OWS Context Conceptual Model. Open Geospatial Consortium (2014). https://portal.ogc.org/files/?artifact_id=55182
____

.Another example 
[source,asciidoc]
----
* [[[GeoRSS,GeoRSS]]], GeoRSS Geographically Encoded Objects for RSS Feeds. (http://www.georss.org/)
----

it will render:
____
GeoRSS Geographically Encoded Objects for RSS Feeds. (http://www.georss.org/)
____

