---
layout: ogc-flavor
title: Introduction to AsciiDoc
---
// include::/author/concepts/intro_to_asciidoc/[tag=tutorial]
Each Metanorma document is written in AsciiDoc, a markup language that annotates text with processing instructions for layout. Since AsciiDoc only consists of text, you can use any editor to create AsciiDoc files (`.adoc` files). AsciiDoc is very similar to Markdown or Wiki formatting but provides more precise markup for creating text documents, for example to create a bibliography section or an index.

Because Metanorma fulfills the markup requirements of SDOs, Metanorma extends plain AsciiDoc. This version of AsciiDoc is called Metanorma AsciiDoc. 

An AsciiDoc document consists of different levels of granularity:

* The document head (also called the header)
* Sections
* Blocks
* Inline markup

== Automatic numbering in Metanorma
// include::/author/concepts/auto_numbering/[tag=auto-num-intro]
Typical AsciiDoc already supports auto-numbering for some block types, such as tables and figures.
Metanorma extends auto-numbering to formulas (which are encoded as `stem` blocks) and notes.

Metanorma auto-numbers these document elements, so you do not need to specify any numbering for them:

* figures
* tables
* examples
* formulas
* sourcecode, pseudocode
* permissions, recommendations and requirements.

The conventions for numbering vary by Metanorma flavour, but the
default is to number all elements consecutively in the main body of a document, and
separately in each Annex/Appendix, prefixed bt the Annex/Appendix number.