---
layout: ogc-flavor
title: Writing Metanorma AsciiDoc
---
// include::/author/concepts/intro_to_asciidoc/[tag=tutorial]
Metanorma documents are typically written in a
https://en.wikipedia.org/wiki/Markup_language[markup language] called
"`Metanorma AsciiDoc`".

Metanorma AsciiDoc is created as an extended superset of the normal
https://asciidoc.org[AsciiDoc] markup language in order to support the complex
requirements of standards and model-based content creation.

NOTE: A markup language allows applying processing instructions to textual
content.

Metanorma AsciiDoc inherits the ease of use of normal AsciiDoc but lets you do
much more.
AsciiDoc is very similar to Markdown or Wiki formatting but provides more
precise markup for creating text documents, for example to create a bibliography
section or an index.
Since it is a "`plain text`" markup language, you can use any plain
text editor to create its files (`.adoc` files).

A Metanorma AsciiDoc document consists of several basic components:

* Document header
* Clauses or sections
* Blocks
* Inline markup

== Automatic numbering in Metanorma
// include::/author/concepts/auto_numbering/[tag=auto-num-intro]

Metanorma supports auto-numbering for  block types, such as tables and figures.
Metanorma extends auto-numbering to formulas (which are encoded as `stem` blocks) and notes.

Metanorma auto-numbers these document elements, so you do not need to specify any numbering for them:

* figures
* tables
* examples
* formulas
* sourcecode, pseudocode
* permissions, recommendations and requirements.

The conventions for numbering vary by Metanorma flavour, but the
default is to number all elements consecutively in the main body of a document, and
separately in each Annex/Appendix, prefixed bt the Annex/Appendix number.
