# frozen_string_literal: true

module ExtractAttributes
  # Collects per-flavor extraction statistics and renders the plain-text
  # report written to attributes/extraction-report.txt.
  class Report
    def initialize
      @flavors = {} # key => hash of collected facts
    end

    def [](key)
      @flavors[key] ||= {
        entries: 0, satellites: 0, enums: 0, values: 0, added_in: 0,
        examples: 0, required: [], defaults: 0, deprecated: [],
        repeatable: 0, merged: [], recovered: [], anchors: [],
        dropped_duplicate_terms: [], comments_dropped: 0,
        value_lines: 0, bullet_values: 0, inline_values: 0,
        amendments: [], prose_blocks: [], prose_lines: 0,
        spillover: [], crosscheck: [], notes: [],
      }
    end

    def render
      out = ["Metanorma attribute-manifest extraction report",
             "Generated by scripts/extract-attributes.rb on #{Date.today}",
             "=" * 72, ""]
      @flavors.each do |key, f|
        out << "## #{key}"
        out << "entries: #{f[:entries]} (+#{f[:satellites]} alias/see satellites)"
        out << "enums: #{f[:enums]} (#{f[:values]} values captured: #{f[:value_lines]} line, #{f[:bullet_values]} bullet, #{f[:inline_values]} inline); " \
               "added_in macros: #{f[:added_in]}; examples: #{f[:examples]}; " \
               "repeatable: #{f[:repeatable]}; defaults: #{f[:defaults]}"
        out << "required: #{f[:required].join(', ')}" if f[:required].any?
        out << "deprecated: #{f[:deprecated].join(', ')}" if f[:deprecated].any?
        out << "anchors recorded: #{f[:anchors].join(', ')}" if f[:anchors].any?
        if f[:recovered].any?
          out << "recovered/normalized terms: #{f[:recovered].join('; ')}"
        end
        if f[:dropped_duplicate_terms].any?
          out << "duplicated term lines dropped: #{f[:dropped_duplicate_terms].join('; ')}"
        end
        if f[:merged].any?
          out << "duplicate entries merged:"
          f[:merged].each { |m| out << "  - #{m}" }
        end
        if f[:amendments].any?
          out << "validator amendments:"
          f[:amendments].each { |a| out << "  - #{a}" }
        end
        out << "comment lines dropped: #{f[:comments_dropped]}" if f[:comments_dropped].positive?
        out << "prose-only blocks: #{f[:prose_blocks].size} blocks, #{f[:prose_lines]} lines #{f[:prose_target]}"
        f[:prose_blocks].each_with_index do |b, i|
          out << "  [prose #{i + 1}] (#{b[:where]})"
          out << b[:text].split("\n").map { |l| "    #{l}" }
        end
        if f[:spillover].any?
          out << "section-level spillover blocks (prose/examples to companion or sections): #{f[:spillover].size}"
          f[:spillover].each_with_index do |b, i|
            out << "  [spill #{i + 1}]"
            out << b.split("\n").map { |l| "    #{l}" }
          end
        end
        out << "AST cross-check:" 
        if f[:crosscheck].empty?
          out << "  clean (entries and nested values match the coradoc AST)"
        else
          f[:crosscheck].each { |c| out << "  #{c}" }
        end
        f[:notes].each { |n| out << "note: #{n}" }
        out << ""
      end
      out.join("\n") + "\n"
    end
  end
end
