---
layout: iso-flavor
---

= Docuemnt Attributes

The following document attributes are specific to ISO:

== Document info

`:tc-docnumber:`:: The document number assigned by the Technical committee

`:partnumber:`:: The ISO document part number. (This can be "part-subpart" if this is an IEC document.)

`:doctype:`:: Has its possible values defined by
https://www.iso.org/deliverables-all.html[ISO deliverables: The different types of ISO publications]
(mandatory). The permitted types are:
`international-standard, technical-specification, technical-report,
publicly-available-specification, international-workshop-agreement, guide`.

`:docstage:`:: The stage code for the document status (see
https://www.iso.org/stage-codes.html[International harmonized stage codes]).
Synonym of `:status:`.

`:docsubstage:`:: The substage code for the document status (see
https://www.iso.org/stage-codes.html[International harmonized stage codes])

=== Title


`:title-intro-en:`:: The introductory component of the English title of the
document. This and the other `:title-*` document attributes are used instead
of the metanorma-standoc `:title:` attribute and the default Asciidoctor title
(the first line of the document header, prefixed with `=`).

`:title-main-en:`:: The main component of the English title of the document
(mandatory).

`:title-part-en:`:: The English title of the document part

`:title-intro-fr:`:: The introductory component of the French title of the
document. (This document template presupposes authoring in English; a different
template will be needed for French, including French titles of document
components such as annexes.)

`:title-main-fr:`:: The main component of the French title of the document
(mandatory).

`:title-part-fr:`:: The French title of the document part

== Author info

`:secretariat:`:: The national body acting as the secretariat for the document
in the deafting stage

`:technical-committee-number:`:: The number of the relevant ISO technical
committee (also `:technical-committee-number_2:`, `:technical-committee-number_3:`...;
the same applies for all technical-committee, subcommittee and workgroup attributes)

`:technical-committee-type:``:: The type of the relevant technical committee. Defaults
to `TC` if not supplied. Values: `TC1, `PC`, `JTC`, `JPC`.

`:technical-committee:`:: The name of the relevant ISO technical committee
(mandatory)

`:subcommittee-number:`:: The number of the relevant ISO subcommittee

`:subcommittee-type:`:: The type of the relevant ISO subcommittee. Defaults to
`SC` if not supplied. Values: `SC`, `JSC`.

`:subcommittee:`:: The name of the relevant ISO subcommittee

`:workgroup-number:`:: The number of the relevant ISO workgroup

`:workgroup-type:`:: The type of the relevant ISO workgroup. Defaults to `WG` if
not supplied. Example values: `JWG`, `JAG`, `AG` (advisory group), `AHG`, `SWG`,
`SG`, `MA` (maintenance agency), `CORG`, `JCG`, `CAG`

`:workgroup:`:: The name of the relevant ISO workgroup

