---
layout: iso-flavor
---

= Metanorma ISO document attributes

[[note_general_doc_ref_doc_attrib]]
[NOTE]
====
The document attributes listed below are unique to Metanorma’s processing of ISO documents.

For _common document attributes_, see link:/author/ref/document-attributes[Document attributes reference] in general Metanorma author’s documentation. That page describes attributes that apply to all Metanorma flavors, not just ISO.

For an _introduction to Metanorma AsciiDoc document attributes_ and how Metanorma uses them, see link:/author/topics/document-format/meta-attributes/[the corresponding topic].
====

== Document info

`:tc-docnumber:`:: The document number assigned by the Technical committee

`:partnumber:`:: The ISO document part number. This can be "`part-subpart`" if this is an ISO/IEC or IEC document.

`:doctype:`:: Has its possible values defined by
https://www.iso.org/deliverables-all.html[ISO deliverables: The different types of ISO publications]
(mandatory). Permitted types are: +
+
** `international-standard`
** `technical-specification`
** `technical-report`
** `publicly-available-specification`
** `international-workshop-agreement`
** `guide`
** `technical-corrigendum` [added in https://github.com/metanorma/isodoc/releases/tag/v1.3.25]
** `amendment` [added in https://github.com/metanorma/isodoc/releases/tag/v1.3.25].

`:updates-document-type:`:: (only when `doctype` is set to `amendment` or `technical-corrigendum`)
The document type that this amendment or technical corrigendum is
updating [added in https://github.com/metanorma/isodoc/releases/tag/v1.3.25].

`:docsubtype:`:: A subclass of doctype for which special processing rules apply:
+
** `vocabulary`: [added in https://github.com/metanorma/metanorma-iso/releases/tag/v1.8.2]
The "vocabulary" document type is defined in the
https://www.iso.org/ISO-house-style.html[ISO House Rules]
and title requirements defined in the ISO/IEC Directives, Part 2, 2018, 11.5.2.
The initial clause of the terms section,
"`For the purposes of this document, the following terms and definitions apply`",
is deleted; terminological entries are permitted outside of Clause 3.

`:docstage:`:: The stage code for the document status (see
https://www.iso.org/stage-codes.html[International harmonized stage codes]).
Synonym of `:status:`.
+
--
NOTE: ISO authors usually create Metanorma documents at stages `00` through `40`
(PWI `00.`, AWI, NP, WD, CD, DIS).
Documents at the final stages, `50` and `60` (FDIS, PRF, IS), are created by
ISO Editorial Program Managers at ISO/CS (aka ISO EPMs, ISO Editors).
Authors using Metanorma are not expected to edit documents at those stages, and
are not necessary in a normal submission process.
These stages, however, can be used for mirroring and tracking of final stage
and published standards, which many authors do.
-- 
//Note contains process information. Do not explain process in Ref but link to ISO Flavor page.

`:docsubstage:`:: The substage code for the document status (see
https://www.iso.org/stage-codes.html[International harmonized stage codes]).
If this is left out, a substage of "`00`" is assumed, with the exception of
stage "`60`" (published), where a substage of "`60`" is assumed.
("`60.00`" is the final proof "`PRF stage`", "`60.60`" the published document "`published`".)

`:horizontal:`:: Document is a horizontal standard (true/false) [added in https://github.com/metanorma/metanorma-iso/releases/tag/v1.5.13].

=== Document identifier

==== General

The ISO document identifier is assembled out of these metadata elements:

publisher:: publisher of the document
document stage:: stage of development of document, according to the Harmonized Stage Codes
document number:: numeric identifier of document
update number:: serial number of update (for amendments and technical corrigenda)
document type:: type of ISO deliverable
copyright year:: year of publication of document
language:: language of document

==== Publisher

This is the abbreviation of the publishing organization, typically `ISO`. If the document is published under co-publishing agreements, it can contain the abbreviations of other publishing SDOs, delimited by `/` after `ISO`. An `IWA` document has publisher abbreviation of `IWA`.

EXAMPLE: `ISO`, `ISO/IEC`, `ISO/IEC/IEEE`, `ISO/IEEE`, `ISO/SAE`, `IWA`

==== Document type and stage

ISO document stages in document identifiers are mapped as follows.

International Standard::

`00.00` to `00.99`::: "`PWI`"
`10.00` to `10.98`::: "`NP`"
`10.99` to `10.98`::: "`AWI`"
`20.00` to `20.99`::: "`WD`"
`30.00` to `30.99`::: "`CD`"
`40.00` to `40.99`::: "`DIS`"
`50.00` to `50.99`::: "`FDIS`"
`60.00`::: "`PRF`"
`60.60`::: empty designation

Technical Specification, Technical Report::

`00.00` to `00.99`::: "`PWI {TR,TS}`"
`10.00` to `10.98`::: "`NP {TR,TS}`"
`10.99` to `10.98`::: "`AWI {TR,TS}`"
`20.00` to `20.99`::: "`WD {TR,TS}`"
`30.00` to `30.99`::: "`CD {TR,TS}`"
`40.00` to `40.99`::: TS/TRs do not have DIS stage because they are not international standards.
`50.00` to `50.99`::: TS/TRs do not have FDIS stage because they are not international standards.
`60.00`::: "`PRF {TR,TS}`"
`60.60`::: "`{TR,TS}`"

//The stage abbreviations DIS and FDIS change to DTS and FDTS

Amendment::

`00.00` to `00.99`::: "`{base-document-id}/PWI Amd {num}`"
`10.00` to `10.98`::: "`{base-document-id}/NP Amd {num}`"
`10.99` to `10.98`::: "`{base-document-id}/AWI Amd {num}`"
`20.00` to `20.99`::: "`{base-document-id}/WD Amd {num}`"
`30.00` to `30.99`::: "`{base-document-id}/CD Amd {num}`"
`40.00` to `40.99`::: "`{base-document-id}/DAmd {num}`"
`50.00` to `50.99`::: "`{base-document-id}/FDAmd {num}`"
`60.00`::: "`{base-document-id}/PRF Amd {num}`"
`60.60`::: "`{base-document-id}/Amd {num}`"

Technical Corrigendum::

`00.00` to `00.99`::: "`{base-document-id}/PWI Cor {num}`"
`10.00` to `10.98`::: "`{base-document-id}/NP Cor {num}`"
`10.99` to `10.98`::: "`{base-document-id}/AWI Cor {num}`"
`20.00` to `20.99`::: "`{base-document-id}/WD Cor {num}`"
`30.00` to `30.99`::: "`{base-document-id}/CD Cor {num}`"
`40.00` to `40.99`::: "`{base-document-id}/DIS Cor {num}`"
`50.00` to `50.99`::: "`{base-document-id}/FDCor {num}`"
`60.00`::: "`{base-document-id}/PRF Cor {num}`"
`60.60`::: "`{base-document-id}/Cor {num}`"


When the Publisher element contains a "`slash`" ("`/`"), the separation in front of the document stage will be converted into an empty space.

EXAMPLE: `ISO/NP 33333` but `ISO/IEC NP 33333`; `ISO/NP TR 33333` but `ISO/IEC NP TR 33333`.


According to ISO Directives Part 1 (11ed), SE.2 "`Working drafts (WD), committee drafts (CD), draft International Standards (DIS), final draft International Standards (FDIS) and International Standards`", "`Successive DIS on the same subject will carry the same number but will be distinguished by a numerical suffix (.2, .3, etc.).`"

Metanorma names the stage iteration number accordingly for all stages, which is patterned as:
`{document stage}` (no suffix if iteration is 1), `{document stage}.{iteration number}` (suffix including iteration number after 1).

Once the document is published (stage 60 substage 60), no status abbreviation is given.


==== Full document identifier patterns

The patterns are as follows:

*International Standard*::
`{publisher} (/{document type and stage})? ({document number}) (- {part number})? (: {copyright year}) ({ISO 639 language code})?` +
+
EXAMPLE: `ISO/IEEE/FDIS 33333-2`, `ISO/IEEE 33333-2:2030(E)`

*Technical Report*, *Technical Specification*::
`{publisher} (/{document type and stage}) ({document number}) (- {part number})? (: {copyright year}) ({ISO 639 language code})?` +
+
EXAMPLE: `ISO/IEC/FDIS TS 33333-2`, `ISO/TR 33333-2:2030(E)`, `ISO/IEC TR 33333-2:2030(E)`

*Amendments*, *Technical Corrigendum*::
`{source document ID}/{document type and stage} {update number} (: {copyright year}) ({ISO 639 language code})?` +
+
EXAMPLE: `ISO 33333-2:2030/DIS Cor 2:2031`, `ISO 33333-2:2030/Cor 2:2032`, `ISO/IEC 33333-2:2030/Cor 2:2032`


=== Title

`:title-intro-{en,fr}:`:: The introductory component of the English or French title of the
document.

`:title-main-{en,fr}:`:: The main component of the English or French title
of the document (mandatory).

`:title-part-{en,fr}:`:: The English or French title of the document part.

`:title-amendment-{en,fr}:`:: (only when `doctype` is set to `amendment` or `technical-corrigendum`)
The English or French title of the amendment [added in https://github.com/metanorma/isodoc/releases/tag/v1.3.25]

`:amendment-number:`:: (only when `doctype` is set to `amendment`)
The number of the amendment [added in https://github.com/metanorma/isodoc/releases/tag/v1.3.25]

`:corrigendum-number:`:: (only when `doctype` is set to `technical-corrigendum`)
The number of the technical corrigendum [added in https://github.com/metanorma/isodoc/releases/tag/v1.3.25]

NOTE: These `:title-*` document attributes are used instead
of the `metanorma-standoc` `:title:` attribute and the default AsciiDoc title
(the first line of the document header, prefixed with `=`),
due to the complexity of ISO deliverable titles.

NOTE: This document template presupposes authoring in English; a different
template will be needed for French, including French titles of document
components such as annexes.


== Author info

`:secretariat:`:: The national body acting as the secretariat for the document
in the drafting stage.

`:technical-committee-number:`:: The number of the relevant ISO technical
committee.

`:technical-committee-type:`:: The type of the relevant technical committee. Defaults
to `TC` if not supplied. Typical values: `TC`, `PC`, `JTC`, `JPC`.

`:technical-committee:`:: The name of the relevant ISO technical committee
(mandatory)

`:subcommittee-number:`:: The number of the relevant ISO subcommittee.

`:subcommittee-type:`:: The type of the relevant ISO subcommittee. Defaults to
`SC` if not supplied. Typical values: `SC`, `JSC`.

`:subcommittee:`:: The name of the relevant ISO subcommittee

`:workgroup-number:`:: The number of the relevant ISO working group

`:workgroup-type:`:: The type of the relevant ISO working group. Defaults to `WG` if
not supplied. +
+
EXAMPLE: `JWG`, `JAG`, `AG` (advisory group), `AHG`, `SWG`,
`SG`, `MA` (maintenance agency), `CORG`, `JCG`, `CAG`

`:workgroup:`:: The name of the relevant ISO working group

In the case of multiple responsible groups (technical committees, subcommittees, working groups),
the `:technical-committee:`, `:subcommittee:` and `:workgroup:` attributes can be used to encode multiple groups by suffixing `_n` to the attribute where `n` is a sequential number after 1.

EXAMPLE: `:technical-committee_2:` and `:technical-committee-number_2:`; `:subcommittee:` and `:subcommittee-number_2:`.
