---
layout: iso-flavor
---

= Metanorma ISO document attributes

[[note_general_doc_ref_doc_attrib]]
[NOTE]
====
The document attributes listed below are unique to Metanorma’s processing of ISO documents.

For _common document attributes_, see link:/author/ref/document-attributes[Document attributes reference] in general Metanorma author’s documentation. That page describes attributes that apply to all Metanorma flavors, not just ISO.

For an _introduction to Metanorma AsciiDoc document attributes_ and how Metanorma uses them, see link:/author/topics/document-format/meta-attributes/[the corresponding topic].
====

== Document info

`:tc-docnumber:`:: The document number assigned by the Technical committee

`:partnumber:`:: The ISO document part number. This can be "`part-subpart`" if this is an ISO/IEC or IEC document.

`:doctype:`:: Has its possible values defined by
https://www.iso.org/deliverables-all.html[ISO deliverables: The different types of ISO publications]
(mandatory). Permitted types are: +
+
** `international-standard`
** `technical-specification`
** `technical-report`
** `publicly-available-specification`
** `international-workshop-agreement`
** `guide`
** `technical-corrigendum` [added in https://github.com/metanorma/isodoc/releases/tag/v1.3.25]
** `amendment` [added in https://github.com/metanorma/isodoc/releases/tag/v1.3.25].

`:updates-document-type:`:: (only when `doctype` is set to `amendment` or `technical-corrigendum`)
The document type that this amendment or technical corrigendum is
updating [added in https://github.com/metanorma/isodoc/releases/tag/v1.3.25].

`:docstage:`:: The stage code for the document status (see
https://www.iso.org/stage-codes.html[International harmonized stage codes]).
Synonym of `:status:`.
+
--
NOTE: ISO authors usually create Metanorma documents at stages `00` through `40`
(PWI `00.`, AWI, NP, WD, CD, DIS).
Documents at the final stages, `50` and `60` (FDIS, PRF, IS), are created by
ISO Editorial Program Managers at ISO/CS (aka ISO EPMs, ISO Editors).
Authors using Metanorma are not expected to edit documents at those stages, and
are not necessary in a normal submission process.
These stages, however, can be used for mirroring and tracking of final stage
and published standards, which many authors do.
--

`:docsubstage:`:: The substage code for the document status (see
https://www.iso.org/stage-codes.html[International harmonized stage codes]).
If this is left out, a substage of "`00`" is assumed, with the exception of
stage "`60`" (published), where a substage of "`60`" is assumed.
("`60.00`" is the final proof "`PRF stage`", "`60.60`" the published document "`published`".)


ISO document stages in document identifiers are mapped as follows.

`international-standard`:

* `00.00` to `00.99` "`ISO/PWI`"
* `10.00` to `10.98` "`ISO/NP`"
* `10.99` to `10.98` "`ISO/AWI`"
* `20.00` to `20.99` "`ISO/WD`"
* `30.00` to `30.99` "`ISO/CD`"
* `40.00` to `40.99` "`ISO/DIS`"
* `50.00` to `50.99` "`ISO/FDIS`"
* `60.00` "`ISO/PRF`"
* `60.60` Final stage, empty designation "`ISO`"

`amendment`:

* `00.00` to `00.99` "`{base-document-id}/PWI Amd {num}`"
* `10.00` to `10.98` "`{base-document-id}/NP Amd {num}`"
* `10.99` to `10.98` "`{base-document-id}/AWI Amd {num}`"
* `20.00` to `20.99` "`{base-document-id}/WD Amd {num}`"
* `30.00` to `30.99` "`{base-document-id}/CD Amd {num}`"
* `40.00` to `40.99` "`{base-document-id}/DAmd {num}`"
* `50.00` to `50.99` "`{base-document-id}/FDAmd {num}`"
* `60.00` "`{base-document-id}/PRF Amd {num}`"
* `60.60` Final stage, empty designation "`{base-document-id}/Amd {num}`"

`technical-corrigendum`:

* `00.00` to `00.99` "`{base-document-id}/PWI Cor {num}`"
* `10.00` to `10.98` "`{base-document-id}/NP Cor {num}`"
* `10.99` to `10.98` "`{base-document-id}/AWI Cor {num}`"
* `20.00` to `20.99` "`{base-document-id}/WD Cor {num}`"
* `30.00` to `30.99` "`{base-document-id}/CD Cor {num}`"
* `40.00` to `40.99` "`{base-document-id}/DIS Cor {num}`"
* `50.00` to `50.99` "`{base-document-id}/FDCor {num}`"
* `60.00` "`{base-document-id}/PRF Cor {num}`"
* `60.60` Final stage, empty designation "`{base-document-id}/Cor {num}`"

`technical-specification`, `technical-report`:

* `00.00` to `00.99` "`ISO/PWI {TR,TS}`"
* `10.00` to `10.98` "`ISO/NP {TR,TS}`"
* `10.99` to `10.98` "`ISO/AWI {TR,TS}`"
* `20.00` to `20.99` "`ISO/WD {TR,TS}`"
* `30.00` to `30.99` "`ISO/CD {TR,TS}`"
* `40.00` to `40.99` "`ISO/{DTR,DTS}`"
* `50.00` to `50.99`: TS/TRs do not have FDIS stage because they are not standards.
* `60.00` "`ISO/PRF`"
* `60.60` Final stage, empty designation "`ISO/{TR,TS}`"

=== Title

NOTE: This document template presupposes authoring in English; a different
template will be needed for French, including French titles of document
components such as annexes.

`:title-intro-{en,fr}:`:: The introductory component of the English or French title of the
document. This and the other `:title-*` document attributes are used instead
of the `metanorma-standoc` `:title:` attribute and the default AsciiDoc title
(the first line of the document header, prefixed with `=`).

`:title-main-{en,fr}:`:: The main component of the English or French title
of the document (mandatory).

`:title-part-{en,fr}:`:: The English or French title of the document part.

`:title-amendment-{en,fr}:`:: (only when `doctype` is set to `amendment` or `technical-corrigendum`)
The English or French title of the amendment [added in https://github.com/metanorma/isodoc/releases/tag/v1.3.25]

`:amendment-number:`:: (only when `doctype` is set to `amendment`)
The number of the amendment [added in https://github.com/metanorma/isodoc/releases/tag/v1.3.25]

`:corrigendum-number:`:: (only when `doctype` is set to `technical-corrigendum`)
The number of the technical corrigendum [added in https://github.com/metanorma/isodoc/releases/tag/v1.3.25]


== Author info

`:secretariat:`:: The national body acting as the secretariat for the document
in the deafting stage

`:technical-committee-number:`:: The number of the relevant ISO technical
committee (also `:technical-committee-number_2:`, `:technical-committee-number_3:`...;
the same applies for all `technical-committee`, `subcommittee` and `workgroup` attributes)

`:technical-committee-type:``:: The type of the relevant technical committee. Defaults
to `TC` if not supplied. Values: `TC`, `PC`, `JTC`, `JPC`.

`:technical-committee:`:: The name of the relevant ISO technical committee
(mandatory)

`:subcommittee-number:`:: The number of the relevant ISO subcommittee

`:subcommittee-type:`:: The type of the relevant ISO subcommittee. Defaults to
`SC` if not supplied. Values: `SC`, `JSC`.

`:subcommittee:`:: The name of the relevant ISO subcommittee

`:workgroup-number:`:: The number of the relevant ISO workgroup

`:workgroup-type:`:: The type of the relevant ISO workgroup. Defaults to `WG` if
not supplied. Example values: `JWG`, `JAG`, `AG` (advisory group), `AHG`, `SWG`,
`SG`, `MA` (maintenance agency), `CORG`, `JCG`, `CAG`

`:workgroup:`:: The name of the relevant ISO workgroup

