---
layout: gb-flavour
---

= GB/T 1.1 Compliance

GB/T 1.1-2009 prescribes the format of GB standards meticulously, and is based on ISO/IEC DIR 2-2004
(though it is not equivalent, and ISO/EIC DIR 2 is less prescriptive about layout). 
GB issued a template program for generating compliant Word documents
in 2010; this program no longer executes on Windows. (Metanorma-GB has extracted its stylesheet for
use in formatting output, but the stylesheet itself had to be modified in places to comply with
GB/T 1.1.)

Compliance of GB standards with GB/T 1.1 has been patchy. This has been exacerbated by the fact that
ISO/IEC DIR 2 was substantially revised in 2011 and again in 2016. Although GB/T 1.1 has not been
updated to align with ISO/IEC DIR 2-2016, published GB standards increasingly are formatted according
to ISO in most areas where ISO and GB now conflict.

Metanorma-GB attempts to align with current best practice of GB standards, and does so in consultation with
GB. GB/T 19018-2017 has been used as the exemplar standard.

The following area the areas where the Metanorma’s MS Word output aligns with or deviates from GB/T 1.1-2009.

* https://github.com/riboseinc/metanorma-gb/issues/58[Measurements (GB/T 1.1 Annex I.)] Metanorma-GB
scrupulously aligns with the measurements prescribed in GB/T, to a greater extent than the 2010
template tool. As already noted, it makes extensive use of frames to ensure correct vertical positioning
of headers, and of elements on the cover page.

* https://github.com/riboseinc/metanorma-gb/issues/56[Fonts (GB/T 1.1 Annex J.)] Metanorma-GB aligns
with the fonts and font sizes prescribed in GB/T. (The only exception is the standard name, for which a
point size of 72 is quite unrealistic: 26pt is used instead, in compliance with the preexisting Word 
template.) For Simplified Chinese script, Metanorma-GB uses by default SimSun as its "serif" font, and SimHei 
has its "sans-serif" font; this reflects practice in the 
Word templates used for GB. For Latin script, it uses Cambria as its serif font, and Calibri as its
sans-serif font; this is to minimise disruption moving between scripts. (Note that the stylesheets
make minimal use of boldface and italics, as these are not well-matched with Chinese typography;
the sans-serif font occupies the niche that boldface occupies in ISO Latin-script documents.)
+
GB/T 1.1 prescribes a "custom font" for the standard class and standard issuer on the cover page.
By default, this is the serif font for standards with national scope, and the sans-serif font for
all other scopes. All font selections can be overriden in the document attributes (`:bodyfont:`,
`:headerfont:`, `:titlefont:`.)`

* https://github.com/riboseinc/metanorma-gb/issues/57[Layout (GB/T 1.1 Clause 9.)]. Metanorma-GB complies
with GB/T 1.1, with the following exceptions where it follows ISO/IEC DIR 2-2016 practice instead:

** 9.3: There are no separate tables of figures, tables of tables, or tables of annexes. Table of Contents
indentation in the 2010 stylesheet did not comply with GB/T 1.1.

** 9.5.2: Normal references and Bibliography references are indented like normal paragraphs, instead of
having a hanging indent ("on overflow they should be indented to the top level"); in fact, GB/T 1.1
does not follow this in its own references list.

** 9.5.3: Terms and Definitions is aligned with ISO/IEC DIR 2: there is provision for alternate and
deprecated terms, and term sources are notated in brackets whether they are modified or direct citations
from the source document, instead of being treated as a note in the latter case. 
(https://github.com/riboseinc/metanorma-gb/issues/67) Clauses numbers are separated from the term
source reference by a dash. References to terms defined elsewhere in the Terms and Definitions clause
are accompanied with clause references.

** 9.9.3: Figure footnotes are not longer treated as footnotes, but are instead merged into the figure
key, as is done in ISO/IEC DIR 2. Footnote indentation and note indentation in the 2010 stylesheet 
did not comply with GB/T 1.1.

** 9.9.4: Example labels do not appear on a separate line. Examples like notes have a hanging indent,
so that their content is left-aligned.

** 9.9.5: Formulas are centered in the page, but are not connected with the formula number with a
dotted tab.

