---
layout: author-docs
---
= Introduction to Metanorma AsciiDoc

tag::tutorial[]
Each Metanorma document is written in AsciiDoc, a markup language that annotates text with processing instructions for layout. Since AsciiDoc only consists of text, you can use any editor to create AsciiDoc files (`.adoc` files). AsciiDoc is very similar to Markdown or Wiki formatting but provides more precise markup for creating text documents, for example to create a bibliography section or an index.

Because Metanorma fulfills the markup requirements of SDOs, Metanorma extends plain AsciiDoc. This version of AsciiDoc is called Metanorma AsciiDoc. 

An AsciiDoc document consists of different levels of granularity:

* The document head (also called the header)
* Sections
* Blocks
* Inline markup
end::tutorial[]

The https://asciidoctor.org/docs/user-manual/[Asciidoctor manual] provides ample information about the general markup mechanisms of typical AsciiDoc.

== Unsupported AsciiDoc features
While Metanorma mostly *adds* functionality to the AsciiDoc markup language, there are also some mechanisms, that Metanorma does not support:

* Sidebars (``aside``s) are not supported. Instead, they are used for link:./reviewer-notes/[reviewer comments].
* Page breaks (`thematic break`) are not supported.
* ASCII art/preformatted text (`literal`) are not supported in most Metanorma flavors.

