---
layout: author-docs
description: >-
  <p>
  This is a general guidance for authoring Metanorma documents using Metanorma AsciiDoc.

  <p>
  Since Metanorma uses AsciiDoc markup
  (see <a href="/author/approach/">Approach</a> for technical background),
  this section details the specific ways in which Metanorma interprets AsciiDoc markup,
  as well as custom markup directives.

  <p>
  This section applies across most of the
  <a href="/flavors/">officially supported flavors of Metanorma</a>.
  If you are using one of those flavors,
  be sure to also check out guidelines for your flavor.
---
// Add tutorial content & merge this information

= Metanorma AsciiDoc

== Basic AsciiDoc syntax

Metanorma AsciiDoc is based on the AsciiDoc syntax used by Asciidoctor.

Please refer to the https://asciidoctor.org/docs/user-manual/[Asciidoctor manual]
for general markup mechanisms offered in typical AsciiDoc.


== Unsupported AsciiDoc features

* Sidebars (``aside``s) are not supported. Instead, they are used for link:./reviewer-notes/[reviewer comments].
* Page breaks (`thematic break`) are not supported.
* ASCII art/preformatted text (`literal`) are not supported in most Metanorma flavors.


== Auto-numbering

In addition to the blocks that typical AsciiDoc already supports auto-numbering for (such as tables
and figures),
auto-numbering in Metanorma extends to formulas (which are encoded as `stem` blocks) and notes.

Auto-numbering is applied in the conversion from Metanorma XML to output formats (`isodoc`);
by default it restarts for each annex, but is continuous within the main body of text.
