---
layout: learn
title: Summary of lesson 4
---

Let's summarize what we've learnt in this lesson:

* To generate a Metanorma document, enter the following command: 
+
.Local installation
[source, shell]
----
metanorma document.adoc
----
+
.Using Docker on Linux/ macOS
[source, shell]
----
docker run -v "$(pwd)":/metanorma/ -w /metanorma metanorma/metanorma metanorma document.adoc
----
+
.Using Docker on Windows
[source, shell]
----
docker run -v "%cd%":/metanorma/ -w /metanorma metanorma/metanorma metanorma document.adoc
----


* More often than not, we encounter errors that we need to fix:

** Metadata errors: Provide all metadata that your organization mandates; include the flavor type and document type either in the header or in the build command.
** Markup errors: Make sure you've entered the correct syntax for blocks or inline macros and provided the correct filenames and paths. 
** Reference errors: If a reference can't be resolved, make sure that the anchor name follows the naming rules; The anchor and the reference need to be identical. 
** Bugs: Sometimes, when you can't solve an error, you might have discovered a bug. Feel free to raise an issue in your organization's repository on the https://github.com/Metanorma[Metanorma Github page].


Great work! You've completed the Metanorma fundamentals tutorial! 

You're ready to create Metanorma documents on your own. 
To get started, you can download a https://github.com/orgs/metanorma/repositories?q=mn-templates[template document]. 
Look up any flavor-specific rules in the the link:/flavors[flavor documentation].

//////

Maybe include a page after the tutorial where a user can type in their name and a certificate (PDF) will be generated + downloaded? :)
+++
<div class="cta tutorial"><a class="button" href="/">Finish»</a></div>
+++

//////
