---
layout: learn
title: Term definitions
---
:page-liquid:

If you want to cite a term throughout the standard, include it in the terms and definitions section. Term definitions vary from definition lists, as they are more granular and provide metadata to mark features such as alternative terms or deprecated terms. 
Let’s have a look at a term entry:

[source, AsciiDoc]
----
== Terms and Definitions <1>

=== dataset <2>

collection of data, published or curated by a single agent, and available for access or download in one or more formats <3>

=== feature 
alt:[characteristic] <4>
deprecated:[character] <5>
domain:[software] <6>

abstraction of real world phenomena 

[.source] <7>
<<dcat>>

[example] <8>
a downloadable file, an RSS feed or an API.
term:[dataset] which contains GPS coordinates. <9>
----
<1> The start of the terms and definitions section
<2> The term that should be defined is marked as a subheading using three equal signs. `===`.
<3> Definition for the term. If a term has macros, like `deprecated:[]`, the term definition is the first paragraph after the macros.
<4> `alt:[]` indicates an alternative term. 
<5> The term `feature` supersedes `character`. To document the old term, use the annotation `deprecated:[term]`.
<6> Terms that do not obviously belong to a certain domain can be annotated with `domain:[]`.
<7> The `[.source]` attribute indicates that a citation follows, indicating where the term definition has been taken from. Make sure to include the dot `.` before source, so that the citation will be rendered correctly. 
<8> If you provide an example, use the `[example]` attribute so that it renders according to the styling rules of your SDO.
<9> `term:[]` cites the previously introduced term.


== Practice time

{% include_relative /exercises.adoc content="exercise-2-3-2" %}

The next type of block we will cover are tables.

+++
<div class="cta tutorial"><a class="button" href="/learn/lessons/lesson-2-3-3/">Start next lesson »</a></div>
+++