---
layout: learn
title: Summary of lesson 2
---
//:page-liquid:
We’ve covered a lot of ground, so here is a quick summary for you:

* Each Metanorma document contains metadata in the header using the colon notation `:attribute:`.
* A Metanorma document consists of several predefined sections. The document model of your organization dictates which are optional and which are mandatory. Sections are invoked using equal signs `=`.
* Blocks are entities that belong together, such as paragraphs, lists, tables, etc. Paragraphs and lists do not need to be marked by delimiters. The remaining block types begin and end with a delimiter, for example four dashes `----`.
* Inline markup is used for text formatting and references. You can reference:
** an external source (`URL[Link text]`) 
** Metadata (`{attribute}`)
** Places in the document by setting an anchor (`[[anchor-id]]`) and referencing the anchor (`<<anchor-id>>`)
** Bibliographic entries + 
[source, AsciiDoc]
----
* [[[anchor,document identifier or reference tag]]], _reference list text_
<<anchor>>
----

You did a great job so far! Let’s talk about reviewing documents in the next lesson. 

+++
<div class="cta tutorial"><a class="button" href="/learn/lessons/lesson-3/">Start next lesson »</a></div>
+++