---
layout: learn
title: Lists
---
:page-liquid:

Metanorma AsciiDoc supports three types of lists:

* Unordered lists
* Ordered lists
* Definition lists

== Unordered lists

Unordered lists are bulleted and can be nested by adding asterisks. They look like this:

[source, AsciiDoc]
----
The main changes compared to the previous edition are:

* updated normative references;
* deletions:
** deletion of 4.3. [nested list item]
** deletion of 4.4. [nested list item]
----

== Ordered lists

Ordered lists are invoked by beginning the line with a dot `.`. The list items are numbered automatically. The default list arabic numbers but can vary depending on the stylesheet of your organization. 

[source, AsciiDoc]
----
. First Step
. Second Step
. Third Step
----

== Definition lists

Definition lists (also called https://docs.asciidoctor.org/asciidoc/latest/lists/description/[description lists] pair a term and a description together. They are often used in a "Definitions" section to define units or terms. Definition lists can appear in other sections as well, *except* for the Terms section, which provides a special syntax for defining terms. 

Definition lists follow the syntax of: 
----
`term:: Definition`
----

// In Metanorma PDFs stem:[w] compiled to a lowercase omega. How to determine which alphabet to use?
.Example of definitions for units
[source, AsciiDoc]
----
stem:[w]:: is the mass fraction of grains with a particular defect in the test sample;
stem:[m_D]:: is the mass, in grams, of grains with that defect;
stem:[m_S]:: is the mass, in grams, of the test sample.
----

NOTE: `\stem:[]` is used for mathematical formatting, and results in italics. So `stem:[w]` is an italic w, _w_; `\stem:[m_D]` is an italic m with a D subscript: _m~D~_.


=== Practice time

{% include_relative /exercises.adoc content="exercise-2-3-1" %}

Great work! Let’s have a look at term definitions in the next lesson.

+++
<div class="cta tutorial"><a class="button" href="/learn/lessons/lesson-2-3-2/">Start next lesson »</a></div>
+++