{% if include.flavor.experimental %}
[WARNING]
====
.Experimental flavor
Metanorma for {{ include.flavor.title }} is currently under heavy development.

While it could be used for document submission to {{ include.flavor.title }},
some glitches are possible.

We would greatly appreciate any such issues filed to its GitHub repository here
link:/software/{{ include.flavor.implemented_by }}[{{ include.flavor.implemented_by }}].
====
{% endif %}

== Quick start

{% if include.flavor.docs_entry_points %}
* Check out the
  {%- for p in include.flavor.docs_entry_points %}
  link:{{ p.path }}[{{ p.title }}]{%- unless forloop.last -%},{%- endunless -%}
  {%- endfor %}
  for authoring {{ include.flavor.title_org | default: include.flavor.title }}
  documents
{% endif %}

{% if include.flavor.sample %}
* Look at the link:./sample/[sample Metanorma {{ include.flavor.title }} project]
{% endif %}

* Build Metanorma for {{ include.flavor.title }} documents with a command like this:
+
[source,console]
--
metanorma {{ include.flavor.build.cli_flags }} {my-document-filename.adoc}
--

[IMPORTANT]
====
.New to Metanorma?
Documentation for Metanorma-{{ include.flavor.title }} is meant to
supplement the general Metanorma documentation.

Please first familiarize yourself with the general Metanorma documentation
as well as the AsciiDoc syntax reference.

- link:/author/getting-started/[Start authoring with Metanorma]

- Understand link:/basics/approach/[Metanorma's approach to creating standardization documents]

- Learn about link:/author/topics/document-format/[Metanorma AsciiDoc]
====

{% if include.flavor.implemented_by or include.flavor.data_models or include.flavor.markup_spec %}
== Implementation

{% if include.flavor.implemented_by %}
* link:/software/{{ include.flavor.implemented_by }}/[Ruby gem "{{ include.flavor.implemented_by }}"]
  implements the {{ include.flavor.title }} flavor of Metanorma,
  building on top of link:/software/metanorma/[core Metanorma library].
{% endif %}

{% if include.flavor.data_models %}
* link:/specs/{{ include.flavor.data_models }}/[Metanorma-{{ include.flavor.title }} data models]
  describe document schema.
{% endif %}

{% if include.flavor.markup_spec %}
* link:/specs/{{ include.flavor.markup_spec }}/[{{ include.flavor.markup_name }} markup language specification]
  describes AsciiDoc syntax extension
  designed for authoring {{ include.flavor.title_org | default: include.flavor.title }} documents
  with Metanorma.
{% endif %}

{% endif %}
