{% if include.flavour.experimental %}
[WARNING]
====
.Beta flavour
The {{ include.flavour.title }} flavour of Metanorma is currently
experimental and under active development.

While you could use it in production, some glitches are possible.
We would greatly appreciate any such issues filed against the GitHub repository of
link:/software/{{ include.flavour.implemented_by }}[{{ include.flavour.implemented_by }}]
gem.
====
{% endif %}

== Quick start

{% if include.flavour.sample %}
- Play with a link:./sample/[sample Metanorma-{{ include.flavour.title }} project]
{% endif %}

- Build Metanorma-{{ include.flavour.title }} documents with a command like this:
+
[source,console]
--
metanorma {{ include.flavour.build.cli_flags }} {my-document-filename.adoc}
--

{% if include.flavour.docs_entry_points %}
- Check out
  {%- for p in include.flavour.docs_entry_points %}
  link:.{{ p.path }}[{{ p.title }}]{%- unless forloop.last -%},{%- endunless -%}
  {%- endfor %}
  for authoring {{ include.flavour.title_org | default: include.flavour.title }} documents
  with Metanorma and {{ include.flavour.markup_name }} markup language
{% endif %}

[IMPORTANT]
====
.If you’re new to Metanorma or AsciiDoc
Metanorma-{{ include.flavour.title }} flavour documentation
should be treated in addition to general Metanorma documentation,
and in addition to AsciiDoc format reference.

- link:/author/getting-started/[Get started authoring with Metanorma]

- Get familiar with link:/author/approach/[Metanorma’s approach to creating standards documents]

- Learn about link:/author/topics/document-format/[document file format]

- Read https://asciidoctor.org/docs/user-manual/[the Asciidoctor manual]
====

{% if include.flavour.implemented_by or include.flavour.data_models or include.flavour.markup_spec %}
== Implementation

{% if include.flavour.implemented_by %}
* link:/software/{{ include.flavour.implemented_by }}/[{{ include.flavour.implemented_by }} Ruby gem]
  implements {{ include.flavour.title }} flavour of Metanorma,
  building on top of link:/software/metanorma/[core Metanorma library].
{% endif %}

{% if include.flavour.data_models %}
* link:/specs/{{ include.flavour.data_models }}/[Metanorma-{{ include.flavour.title }} data models]
  describe document schema.
{% endif %}

{% if include.flavour.markup_spec %}
* link:/specs/{{ include.flavour.markup_spec }}/[{{ include.flavour.markup_name }} markup language specification]
  describes AsciiDoc syntax extension
  designed for authoring {{ include.flavour.title_org | default: include.flavour.title }} documents
  with Metanorma.
{% endif %}

{% endif %}
