---
layout: ogc-flavor
---

= Metanorma for OGC document attributes

== Document type and stage

[[note_general_doc_ref_doc_attrib_ogc]]
[NOTE]
====
Document attributes listed below are unique to the processing of OGC documents
in Metanorma.

For _common document attributes_, see
link:/author/ref/document-attributes/[Document attributes reference] which
describes attributes that apply across all Metanorma flavors.

For an _introduction to Metanorma document attributes_ and how Metanorma uses
them, see
link:/author/ref/document-attributes/[the corresponding topic].
====

`:abbrev:`::
The standard abbreviation of the document, used e.g. in URIs

[[ogc-doctype]]
`:doctype:`::
*Mandatory.*
Document type.
+
--
Values:

* `standard`: Standard (a document subtype is necessary, see <<ogc-docsubtype>>) (_default_)
* `draft-standard`: Standard (a document subtype is necessary, see <<ogc-docsubtype>>) [added in https://github.com/metanorma/metanorma-ogc/releases/tag/v2.2.6]
* `abstract-specification-topic`: Abstract Specification
* `best-practice`: Best Practice (a document subtype is necessary, see <<ogc-docsubtype>>)
* `change-request-supporting-document`: Change Request Supporting Document
* `community-practice`: Community Practice
* `community-standard`: Community Standard
* `discussion-paper`: Discussion Paper
* `engineering-report`: Engineering Report
* `other`: Note, Primer, etc.
* `policy`: Policy, Policy -- Name Type Specification
* `reference-model`: Reference Model
* `release-notes`: Release Notes
* `test-suite`: Test Suite
* `user-guide`: User Guide
* `technical-paper`: Technical Paper
  (for documents issued/published on or after 2021-12-16) [added in https://github.com/metanorma/metanorma-ogc/releases/tag/v1.5.5].

Deprecated values:

* `white-paper`: White Paper. Superseded by the "`Technical Paper`" document
  type for a publication date on and after 2021-12-16. See <<legacy-ogc-whitepaper>> for further information.
--

[[ogc-docsubtype]]
`:docsubtype:`:: Document subtype.
Choices:
+
--
* For `doctype` set to `standard`:
** `implementation`: Implementation (_default_)
** `conceptual-model`: Conceptual model
** `conceptual-model-and-encoding`: Conceptual model and encoding
** `conceptual-model-and-implementation`: Conceptual model and implementation
** `encoding`: Encoding
** `extension`: Extension
** `profile`: Profile
** `profile-with-extension`: Profile with extension

* For `doctype` set to `best-practice`:
** `general`: General (_default_)
** `encoding`: Encoding
** `extension`: Extension
** `profile`: Profile
** `profile-with-extension`: Profile with extension
--

`:status:`:: Document status/stage. Synonym: `:docstage:`.
+
--
Choices:

* `draft`: Draft. This is the only draft stage for document types that are not
  `standard`, `draft-standard`, `abstract-specification-topic`, `community-standard`.

* `work-item-draft`: Work item draft. This is the first stage for a
  `community-standard`.

* `swg-draft`: Candidate SWG Draft. This is the first stage for a
  `standard` or `draft-standard`.

* `oab-review`: Candidate OAB Review Draft. This is the intended draft for the
  "`OAB + OGC-NA Review`".
  This stage is only valid for `standard`, `draft-standard`, `abstract-specification-topic` and
  `community-standard`.

* `public-rfc`: Public RFC. This is the draft for the (30 days) public comment period.
  This stage is only valid for `standard`, `draft-standard`, `abstract-specification-topic`,
  `community-standard`, `best-practice` and `community-practice`.

* `tc-vote`: Candidate TC Vote Draft. This is the intended draft for the TC adoption and PC adoption votes.
  This stage is only valid for `standard`, `draft-standard`, `abstract-specification-topic`,
  `community-standard`, `best-practice` and `community-practice`.

* `approved`: Published. This is the document intended to be published.
  This status is to be set after comments are handled with the TC chair (after `tc-vote`).
  `published` is an allowed synonym of `approved` [added in https://github.com/metanorma/metanorma-ogc/releases/tag/v1.2.5].

* `deprecated`: Deprecated. This document has been deprecated.

* `rescinded`: Rescinded. This document has been rescinded as inaccurate [added in https://github.com/metanorma/metanorma-ogc/releases/tag/v1.5.1].

* `retired`: Retired. This document has been retired and no longer considered normative.

* `legacy`: Legacy. This document has been retired and replaced by a completely new standard [added in https://github.com/metanorma/metanorma-ogc/releases/tag/v2.4.7].

[NOTE]
The following figure and table shows available document statuses for each
document type [added in https://github.com/metanorma/metanorma-ogc/releases/tag/v1.5.1].

.OGC document type and document stage publication flows
image::/assets/author/ogc/ogc-doctype-pub-process.svg[]

// Editable diagram at https://lucid.app/lucidchart/19ed6874-34fe-4444-8baf-08a2b0196930

.Document statuses available for various OGC document types
|===
| | draft | work-item-draft | swg-draft | oab-review | public-rfc | tc-vote | approved (published) | deprecated | rescinded | retired

h| standard, draft-stadard, abstract-specification-topic |   |   | x | x | x | x | x | x | x | x
h| community-standard                                    |   | x |   | x | x | x | x | x | x | x
h| best-practice, community-practice                     |   | x |   |   | x | x | x | x | x | x
h| _all other types_                                     | x |   |   |   |   |   | x |   |   | x

|===
--

`:edition:`::
The version number of the document. Dot-delimited, consists of a major version
number, a minor version number, and an optional patch version number.
+
[example]
`2.3.1` means: major version 2, minor version 3, patch version 1.

`:keywords:`::
Comma-delimited list of the keywords associated with the document.

[NOTE]
--
Abbreviations are sometimes used to designate that a document has a
certain document type, document subtype and document stage.
This is a mapping from legacy OGC document values to the current normalized
list:

"`AS`" Abstract Specification:: Now `:doctype: abstract-specification-topic`.
"`BP`" Best Practice:: Now `:doctype: best-practice`.
"`CAN`" Candidate Standard:: Now `:doctype: standard` and `:docstage: swg-draft`.
"`CC`" Conformance Class:: Not a standalone document, but a part of a document with `:doctype: standard`. No longer exists.
"`CR`" Change Request:: Now `:doctype: change-request-supporting-document`; the actual Change Request is a database entry.
"`CS`" Community Standard:: Now `:doctype: community-standard`.
"`CP`" Community Practice:: Now `:doctype: community-practice`.
"`DP`" Discussion Paper:: Now `:doctype: discussion-paper`.
"`DP-Draft`" Draft Discussion Paper:: Now `:doctype: discussion-paper` with `:docstage: swg-draft`.
"`IPR`" Interoperability Program Report -- Engineering Specification:: Now `:doctype: engineering-report`.
"`IS`" Implementation Standard:: Now `:doctype: standard`, `:docsubtype: implementation`.
"`ISC`" Implementation Standard Corrigendum:: Now `:doctype: standard`, `:docsubtype: implementation` (TBD to indicate `corrigendum`).
"`ISx`" Extension Package Standard:: Now `:doctype: standard`, `:docsubtype: extension`.
"`Notes`" Notes:: Now `:doctype: other`, there is no specific type for "`Notes`".
"`ORM`" OGC Reference Model:: Now `:doctype: reference-model`.
"`PC`" Profile Corrigendum:: Now `:doctype: standard`, `:docsubtype: profile` (TBD to indicate `corrigendum`).
"`PER`" Public Engineering Report:: Now `:doctype: engineering-report`.
"`POL`" Policy:: Now `:doctype: policy`.
"`POL-NTS`" Policy -- Name Type Specification:: Now `:doctype: engineering-report`, there is no specific indication for "`NTS`".
"`Primer`" Primer:: Now `:doctype: other`, there is no specific type for "`Primer`".
"`Profile`" Profile:: Now `:doctype: standard`, `:docsubtype: profile`.
"`RFC`" Request for Comment:: Now `:doctype: standard` and `:docstage: public-rfc`.
"`Retired`" Retired document:: This is a document stage indicated `:docstage: retired`.
"`SAP`" Standard Application Profile:: Now `:doctype: standard`, `:docsubtype: profile`.
"`TS`":: Test Suite (TBD)
"`WhitePaper`" Whitepaper:: Was `:doctype: white-paper`, but now `:doctype: technical-paper`.
Please refer to the description of `technical-paper` in <<ogc-doctype>>.
--

== Author info

`:committee:`::
*Mandatory.*
Name of relevant committee producing the document. Use one of:
+
--
* `technical`: Technical Committee
* `planning`: Planning Committee
* `strategic-member-advisory`: Strategic Member Advisory Committee
--

`:subcommittee-type:`::
The type of the relevant subcommittee producing the document.

`:subcommittee-number:`::
The number of the relevant subcommittee producing the document.

`:workgroup:`::
*Mandatory.*
Name of relevant working group producing the document.

`:workgroup-type:`::
Type of the relevant workgroup producing the document.

`:workgroup-number:`::
Number of the relevant workgroup producing the document.

`:submitting-organizations:`::
Semicolon-delimited list of the submitting organizations
for this document. The organization names themselves may contain commas.
+
[example]
.Example of setting submitting organizations
====
_University of Calgary, Canada; National Central University, Taiwan_
====

`:role:`::
Role of contributor (`link:/author/ref/document-attributes/#role[:role:]`).
Legal values are `author`, `editor`, and [added in https://github.com/metanorma/metanorma-ogc/releases/tag/v2.0.2]
`contributor`.

`:editor:`::
Same as `link:/author/ref/document-attributes/#fullname[:fullname:]`
alongside `link:/author/ref/document-attributes/#role[:role:]` specified as `editor`.


== URIs and IDs

`:external-id:`::
External identifier referring to this document. If not supplied, a default value is
generated: `http://www.opengis.net/doc/{abbreviation of doctype}/{abbrev}/{version}`.
(Version is omitted if not provided. If `:abbrev:` and `:doctype:` are not provided,
the default value is not generated.

`:referenceURLID:`::
Identifier embedded into a document type-specific external URL.

`:previous-uri:`::
URI of previous version of the document.

`:docnumber:`::
The document number assigned to the OGC document (without the "`OGC`" prefix).
+
--
NOTE: A new document number is obtained through the
https://portal.ogc.org/?m=public&subtab=instructions&tab=1["`OGC Pending Documents`"]
page at the OGC portal.

The number is of the pattern `YY-NNN{rM}` formulated following the following rules:

* `YY` represents the final two digits of the year this document number was first reserved.

* `NNN` is a three digit number is assigned sequentially for each document in the year.

* `{rM}` is only for revisions:

** The first edition of a document has the document number `YY-NNN`. e.g., `00-027` is OGC document 027 first published in 2000.

** Minor editorial changes and corrigenda do not result in a change to the document number.

** The `YY-NNN` identifier portion is maintained if the document undergoes content changes (revisions).

** A revised document will have its identifier suffixed with `r` followed by the revision number `M`, a sequential number indicating the number of revisions. So `05-020r27` is revision 27 of OGC document 020 first published in 2005. (Revision 27 may appear years later than 2005.)

* A new major version of a document receives a new document number, including likely a new year.
--


== Legacy information

[[legacy-ogc-whitepaper]]
=== OGC White Paper now renamed as Technical Paper

The OGC Planning Committee at the 121st OGC Member Meeting has approved the
rename of the document type "`White Paper`" to "`Technical Paper`".

All documents issued or published before 2021-12-16 will remain with the
document type "`White Paper`", and documents published on or after that date
will have the document type "`Technical Paper".

The two document types are treated identically, and are rendered differently
depending on the date published or issued.


=== OGC identity design

OGC has launched its current identity together with its new logo and color
scheme on 2021-11-08.

Both current and previous identity designs are supported in Metanorma-OGC.
The differences include:

* OGC logo
* PDF color scheme

Application of the branding design depends solely on the publication date
of an OGC deliverable:

* a deliverable with a publication date on or after 2021-11-08 will use the
  new branding. This will also be used if `:document-scheme: 2022` is provided.

* a deliverable dated prior to 2021-11-08 will utilize the previous branding.
  This will also be used if `:document-scheme: 2018` is provided.

==== PDF color scheme

The PDF color scheme can be redefined via these attributes:

`:presentation-metadata-color-text:`::
Color of the document body text.

`:presentation-metadata-color-secondary-shade-1:`::
Color of the text on the cover page, unordered list labels, 'crossing lines' design element, color of the circle for section's number, ToC.

`:presentation-metadata-color-secondary-shade-2:`::
Color of the 'crossing lines' design element on the preface pages.

`:presentation-metadata-color-background-definition-term:`::
Color of the background of definition term.

`:presentation-metadata-color-background-definition-description:`::
Color of the background of definition description.

`:presentation-metadata-color-text-title:`::
Color of the clause, table, figure, list titles.

`:presentation-metadata-color-background-page:`::
Color of the cover page and section pages background.

`:presentation-metadata-color-background-text-label-legacy:`::
Color of the background of the label 'Legacy' and bottom text about 'legacy' document on the cover page.

`:presentation-metadata-color-background-term-preferred-label:`::
Color of the background of the label 'PREFERRED'.

`:presentation-metadata-color-background-term-deprecated-label:`::
Color of the background of the label 'DEPRECATED`.

`:presentation-metadata-color-background-term-admitted-label:`::
Color of the background of the label 'ADMITTED`

`:presentation-metadata-color-background-table-header:`::
Color of the table header background.

`:presentation-metadata-color-background-table-row-even:`::
Color of the 'even' table rows background.

`:presentation-metadata-color-background-table-row-odd:`::
Color of the 'odd' table rows background.


=== Mapping to OGC legacy AsciiDoc

Metanorma-OGC permits legacy OGC AsciiDoc template attributes,
and are treated as synonyms of the corresponding Metanorma attributes:

|===
| OGC Metanorma AsciiDoc                    | OGC legacy AsciiDoc

| `:copyright-year:`                        | `:copyrightYear`
| `:workgroup:`                             | `:workingGroup:`
| `:published-date:`                        | `:publicationDate:`
| `:issued-date:`                           | `:approvalDate:`
| `:received-date:`                         | `:submissionDate:`
| `:docnumber:`                             | `:docReference:`
| `:fullname:`, with `:role:` = `editor`    | `:editor:`
| `:edition:`                               | `:version:`

|===

