---
layout: builder-docs
---

= Metadata and Boilerplate

The front material of documents generated by Metanorma routintely involves templated text, including both the front page, and "boilerplate"
about legal and other obligations surrounding the document. Those text templates in turn are routinely populated using metadata extracted
from the document.

== Metadata

The `bibdata` element in a Metanorma document contains various metadata elements about the document, as a bibliographic description.
Those elements are populated either from the document attributes in the Asciidoctor input, or with default values. The `bibdata`
element is populated through the `Asciidoctor::Standoc::Converter.metadata` method, and its inheritors.

The `bibdata` element is not rendered directly as the document front page. Instead, the document front page, and other 
templated texts, are populated wth elements extracted from the `bibdata` element. That extraction takes place using the
`Isodoc.info` method and its inheritors, which invoke the `Isodoc::Metadata` class and its inheritors. The extraction results in
a hash of metadata keys and values, which is used to populate any templated text.

For example, in the ISO flavour, the document header

[source,asciidoctor]
--
= Doc
:docnumber: 1000
:edition: 2
:technical-committee: TC
:technical-committee-number: 1
:technical-committee-type: A
:docstage: 10
:docsubstage: 20
:title-main-en: Main Title -- Title
--

generates the `bibdata` element

[source,xml]
--
  <bibdata type="standard">
    <title language="en" format="text/plain" type="main">Main Title — Title</title>
    <title language="en" format="text/plain" type="title-main">Main Title — Title</title>
    <docidentifier type="iso">ISO/NWIP 1000</docidentifier>
    <docidentifier type="iso-with-lang">ISO/NWIP 1000 (E)</docidentifier>
    <docnumber>1000</docnumber>
    <contributor>
      <role type="author"/>
      <organization>
        <name>International Organization for Standardization</name>
        <abbreviation>ISO</abbreviation>
      </organization>
    </contributor>
    <contributor>
      <role type="publisher"/>
      <organization>
        <name>International Organization for Standardization</name>
        <abbreviation>ISO</abbreviation>
      </organization>
    </contributor>
    <edition>2</edition>
    <language>en</language>
    <script>Latn</script>
    <status>
      <stage>10</stage>
      <substage>20</substage>
    </status>
    <copyright>
      <from>2020</from>
      <owner>
        <organization>
          <name>International Organization for Standardization</name>
          <abbreviation>ISO</abbreviation>
        </organization>
      </owner>
    </copyright>
    <ext>
      <doctype>article</doctype>
      <editorialgroup>
        <technical-committee number="1" type="A">TC</technical-committee>
        <subcommittee/>
        <workgroup/>
      </editorialgroup>
      <structuredidentifier>
        <project-number>ISO 1000</project-number>
      </structuredidentifier>
    </ext>
  </bibdata>
--

In turn, that generates the metadata hash

[source,ruby]
--
{
:agency => "ISO",
:authors => [],
:authors_affiliations => {},
:docnumber => "ISO/NWIP 1000",
:docsubtitle => "",
:docsubtitlemain => "",
:docsubtitlepartlabel => "Partie&nbsp;",
:doctitle => "Main Title&#x2009;&#x2014;&#x2009;Title",
:doctitlemain => "Main Title&#x2009;&#x2014;&#x2009;Title",
:doctitlepartlabel => "Part&nbsp;",
:doctype => "Article",
:docyear => "2020",
:draft => nil,
:draftinfo => "",
:edition => "2",
:editorialgroup => ["A 1"],
:ics => "XXX",
:obsoletes => nil,
:obsoletes_part => nil,
:revdate => nil,
:sc => "XXXX",
:secretariat => "XXXX",
:stage => "10",
:stage_int => 10,
:stageabbr => "NWIP",
:tc => "A 1",
:tc_docnumber => [],
:unpublished => true,
:wg => "XXXX",
}
--

Some metadata hash values are normalised, especially as the contents of the hash are intended for display;
dates for example are often resolved from ISO-8601 format to formats with the month spelled out.

== Boilerplate processing

The metadata hash is used by the `Isodoc::Convert.populate` method, to populate all
templated text. Templated text is expected to be in https://shopify.github.io/liquid/[Liquid template language].
The keys of the metadata hash are the variable names passed into Liquid. So given
the metadata hash above, the templated text

[source,html]
--
<div class="doctitle-en"><div><span class="title">{{ doctitleintro }}{% if doctitleintro and doctitlemain %} &mdash; {% endif %}</span><span class="subtitle">{{ doctitlemain }}{% if doctitlemain and doctitlepart %} &mdash;{% endif %}</span>
  {% if doctitlepart %}
</div><div class="doctitle-part">
  {% if doctitlepartlabel %}<span class="partlabel">{{ doctitlepartlabel }}: </span>{% endif %}
  <span class="part">{{ doctitlepart }}</span>
  {% endif %}
</div></div>
--

is populated as

[source,html]
--
<div class="doctitle-en"><div><span class="title"></span><span class="subtitle">Main Title&#x2009;&#x2014;&#x2009;Title</span>
</div></div>
--

and all the conditional output is ignored, because the document has neither a part component nor an introductory componet to its 
title: only `{{ doctitlemain}}` ends up populated.

The `Isodoc::Convert.populate` method merges the metadara hash with the
`@labels` hash used for internationalisation (see link:/builder/howto/localizing-output/[Localization how-to guide]).
This is so that any templated text can also access localised labels defined for the current language.

The metadata hash for a flavour is also populated with the absolute file locations of the gem's copy of any logo images.
That means that any logos are populated in templated text using the metadata hash. For example, the HTML and Word
logo images for the M3D flavour of metanorma are defined in `IsoDoc::M3d::Metadata.initialize` as

[source,ruby]
--
      def initialize(lang, script, labels)
        super
        here = File.dirname(__FILE__)
        set(:logo_html,
            File.expand_path(File.join(here, "html", "m3-logo.png")))
        set(:logo_word,
            File.expand_path(File.join(here, "html", "logo.jpg")))
      end
--

That means that the HTML logo image is populated in the HTML cover page for M3D through a Liquid variable:

[source,html]
--
<img src="{{ logo_html }}" alt="m3 logo"/>
--

NOTE: Although the absolute file location of the image inside the gem is used, postprocessing replaces this
with either a local copy or a Data URI, in the case of HTML, and a MIME embedded attachment containing the image,
in the case of Word.

The templated text populated through metadata can include:

* Under the `isodoc/*/html` directory of the gem:
** The HTML cover page (`html_*_titlepage.html`) and Word cover page (`word_*_titlepage.html`), which are the
main destination for `bibdata` metadata.
** The introductory page for HTML and Word (`html_*_intro.html`, `word_*_intro.html`), although this is usually populated
instead via Metanorma boilerplate (see below).
** The Word header (`header.html`).
** The HTML and Word Stylesheets (`*.scss`). This is in case any variables are used to either populate the stylesheet,
or to conditionally include text; NIST and IEC use the current document status to turn line numbering on or off
in the Word stylesheet.
(Draft documents are line-numbered, and whether a document is in draft or not depends on the value of `bibdata/status`.)
* Under the `asciidoctor/*` directory of the gem:
** The Metanorma boilerplate file (boilerplate.xml)

[boilerplate]
== Boilerplate

The `boilerplate` element in Metanorma XML follows after `bibdata`, and contains text that is repeatedly included
in each instance of the document class, and that outlines the rules under which the document may be used. By
default, the `boilerplate` element contains up to four elements: `copyright-statement`, `license-statement`,
`legal-statement`, and `feedback-statement`. Each of those statements is a Metanorma clause, which can contain
a title, multiple paragraphs, and subclauses.

Because the boilerplate content is repeated for each document in its class, it is not expected to be supplied by the
user (although the user can supply their own boilerplate file using the `:boilerplate-authority:` document attribute).
Instead, the boilerplate content is included as a Metanorma XML file in the gem; by default, it is called
`boilerplate.xml`. Some of the boilerplate may be populate with metadata specific to the current document,
so the boilerplate file is a Liquid template, populated with variables from the current flavour metadata hash
as with other templated text.

The content in the `boilerplate` element is processed as part of the document preface, and converted to HTML or
Word like the rest of the Metanorma XML. However, boilerplate content usually ends up in the cover page or
introductory page of the document instead. The following are the default conventions in Metanorma, although
they can be overridden in the `IsoDoc::*::Converter.authority_cleanup` method (as is currently done in NIST):

* Content in the `copyright-statement` element is rendered in a `<div class="boilerplate-copyright">` container.
* The `authority_cleanup` method, defined in postprocessing for both the HTML and the Word converters,
looks for a single element with `id` attribute `boilerplate-copyright-destination`.
* If it finds such an element, it moves the `<div class="boilerplate-copyright">` container and its contents
to replace that element. This is how boilerplate content can populate the cover page or introductory page,
instead of occurring within the document body.
* This is repeated for each of `license-statement`, `legal-statement`, and `feedback-statement`. 

For example, in the ISO flavour, the license statement is the warning present if the document is in draft, and
`<div id="boilerplate-license-destination"/>` appears in the title page template for the flavour; the CSS styling
for the front page draft warning is styled as `boilerplate-license`. The copyright statement for ISO
occurs on the second page, and `<div id="boilerplate-copyright-destination"/>` appears accordingly in the
introductory page template for the flavour.

