---
layout: ogc-flavor
title: Terms and definitions
---

Specific terms used in this guide is defined in this section.

== admonition

statement used to draw the attention of the reader by labeling it with a
priority tag

[example]
WARNING, NOTE, TIP.

== boilerplate (also _boilerplate text_)

predefined content that is automatically inserted into the output in accordance
to flavor requirements

== clause (also _section_)

logical group of content that is numerically identified in ascending order

== subclause (also _subsection_)

clause that belongs to a top-level clause or another subclause

== cross-reference

link to a location in the current document or in another external document

== document attribute

key-value pair that specifies execution configuration or
provides metadata at the document level

NOTE: A Metanorma document attribute key-value pair is implemented using the
syntax of `:{key}: {value}`.

== block attribute

key-value pair that specifies execution configuration or provides metadata at
the block level

NOTE: A Metanorma document attribute key-value pair is implemented using the
syntax of `{key}={value}`.

== Metanorma flavor

Metanorma implementation that conforms to a publishing organization's content
model

NOTE: Conformance of content covers validity of content, the content generation
process, and formatting of deliverables.

== Metanorma AsciiDoc

markup syntax for the authoring of standards based on AsciiDoc

== Metanorma template

files that serve as guidance to author a specific document type in OGC flavor
