---
layout: author-docs
title: Lists
---
tag::tutorial[]
Metanorma AsciiDoc supports three types of lists:

* Unordered lists
* Ordered lists
* Definition lists

== Unordered lists

Unordered lists are bulleted and can be nested by adding asterisks. They look like this:

[source, AsciiDoc]
----
The main changes compared to the previous edition are:

* updated normative references;
* deletions:
** deletion of 4.3. [nested list item]
** deletion of 4.4. [nested list item]
----

== Ordered lists

Ordered lists are invoked by beginning the line with a dot `.`. The list items are numbered automatically. The default list arabic numbers but can vary depending on the stylesheet of your organization. 

[source, AsciiDoc]
----
. First Step
. Second Step
. Third Step
----

== Definition lists

Definition lists (also called https://docs.asciidoctor.org/asciidoc/latest/lists/description/[description lists] pair a term and a description together. They are often used in a "Definitions" section to define units or terms. Definition lists can appear in other sections as well, *except* for the Terms section, which provides a special syntax for defining terms. 
Definition lists follow the syntax of `term:: Definition`. The following example defines units that are used in the document.

NOTE: `\stem:[]` is used for mathematical formatting, and results in italics. So `stem:[w]` is an italic w, _w_; `\stem:[m_D]` is an italic m with a D subscript: _m~D~_.

// In Metanorma PDFs stem:[w] compiled to a lowercase omega. How to determine which alphabet to use?

[source, AsciiDoc]
----
stem:[w]:: is the mass fraction of grains with a particular defect in the test sample;
stem:[m_D]:: is the mass, in grams, of grains with that defect;
stem:[m_S]:: is the mass, in grams, of the test sample.
----
end::tutorial[]

== List styling

=== Unordered list styling
The default styling for unordered lists are bullets. Metanorma does not support other styles for unordered lists.

=== Ordered list styling

The default styling for ordered lists follow the specifications of ISO/IEC DIR 2 and is the same for each output type:

- level 1: _a), b), c)_ (`alphabetic`),
- level 2: _1), 2), 3)_ (`arabic`),
- level 3: _i), ii), iii)_ (`roman`),
- level 4: _A), B), C)_ (`alphabetic_upper`),
- level 5: _I), II), III)_ (`roman_upper`).

However, if you want to tweak how your list looks like, you can use the `type` attribute and the values from above.

.Example for a manually styled list
[source, AsciiDoc]
----
[type="alphabetic_upper"]
. First as "A"
. Second as "B"

[type="roman_upper"]
. First as "I"
. Second as "II"
----

NOTE: In Word rendering the `type` attribute is always ignored in favor of ISO/IEC DIR 2 compliant labelling.

NOTE: Manually styled lists are not supported by all flavors. 


=== Definition list styling

Definition lists are rendered by default horizontally, with the definition in the same line as the term. 

In Word, definition lists are rendered as true tables. 
Word defines the width of the term column using the auto-width algorithm, and might cause words to break.

To ensure that terms are rendered in a single line in Word, you need to use non-breaking spaces and non-breaking hyphens in HTML escape notation. 

* Non-breaking spaces: `\&nbsp;` or `\&#xa0;`
* Non-breaking hyphens `\&#x2011;` 

.Example for a non-breaking sentence
[source, asciidoc]
====
Instead of entering "This is a non-breaking term"

Enter:
This\&nbsp;is\&nbsp;a\&nbsp;non\&#x2011;breaking\&nbsp;term
====


=== List items with more than one paragraph

Metanorma XML and HTML support multiple paragraphs within a single list item (see https://asciidoctor.org/docs/user-manual/#list-continuation[list continuation]). In HTML output, all the paragraphs within a list item will be aligned.

[NOTE]
====
.Microsoft Word caveats

- For list items containing multiple paragraphs,
  Metanorma attempts to format them appropriately by using custom
  list continuation styles (`ListContLevel1` etc.) applied to groups
  of paragraphs; however, you should check the output document and
  may need to manually intervene.

- In Microsoft Word, each list entry must be a single paragraph.
  Metanorma is employing a workaround through list continuation styles,
  and results may be unexpected if the list is edited.
====
