---
layout: author-docs
title: Passthrough to output formats
---
= Passthrough to output formats

== Skip Metanorma processing of markup

Metanorma uses Asciidoc markup with some additions, such as `{{...}}` for concepts.
Metanorma will render markup as it finds it. If you wish to ignore Metanorma processing
of markup, you will need to use pass-through markup: `&#x2b;&#x2b;&#x2b;&#x2b;` for blocks, `&#x2b;&#x2b;` for inline
markup. For example, if you want `{{A}}` to display in a document, you will need to
enter it as `&#x2b;+{{A}}&#x2b;+`. 

If you have more complex markup, `&#x2b;&#x2b;` may not be adequate; the Unicode Zero-Width joiner, `&amp;#x200d;`,
may be necessary to force Metanorma not to process the markup. (Asciidoctor's underlying
processor uses backslash to escape some characters, but it is not consistent.) For example,
if you want `++{{A}}++` to display in a document, `&#x5c;&#x2b;+{{A}}&#x2b;+` ends up displaying
_&#x2b;{A}&#x2b;_. You can obtain a display of `&#x2b;+{{A}}&#x2b;+` by writing `&#x2b;&amp;#x200d;+{{A}}&#x2b;+` instead:
`&amp;#x200d;` does not display, but is a character which prevents Metanorma from recognising
`&#x2b;&#x2b;` as markup.

Note that backquotes for monospace formatting always prevent recognition of markup:
`&#x0060;++{{A}}++&#x0060;` is not processed as markup. Using XML escapes for characters, e.g.
`&amp;#x2b;` for `+`, will also prevent it.

== Passthrough blocks

Passthrough text, such as XML tags, intended to be rendered in a target format
unaltered, can be entered as a passthrough
block [added in https://github.com/metanorma/metanorma-standoc/releases/tag/v1.3.27].

This functionality enables automated processing, custom tagging, hacking into
intermediary formats and experimental development of Metanorma output.

WARNING: A broken Metanorma XML file will cause rendering of target formats to
also break. Use with caution.

Passthrough intended to be rendered in Metanorma XML (such as Metanorma XML tags),
generated from Metanorma AsciiDoc input, can be entered as a
passthrough block [added in https://github.com/metanorma/metanorma-standoc/releases/tag/v1.4.1],
with no format indication.

[example]
.Using passthrough XML tags in the Metanorma XML target
====
[source,asciidoc]
--
++++
<bibitem>
++++
--
====

WARNING: Passthrough text may break the structure of the output
format -- it is the user's responsibility to ensure the integrity
of the resulting structure (e.g. XML) is retained.

Passthrough intended to be rendered in a target format must be specified with
a format indication corresponding to one or more of the existing output formats
of Metanorma in a comma-delimited manner
(not limited to: `html`, `doc`, `pdf`, `rfc`, `sts`).

[example]
.Using passthrough XML tags in the RFC XML target
====
[source,asciidoc]
--
[format=rfc]
++++
<artset>
<artwork>
++++
--
====

== Passthrough inline text

Metanorma AsciiDoc supports the following syntaxes for inline passthrough.

Passthrough of text that does not involve XML structural syntax can be realized
in any of the following syntaxes:

[source,adoc]
----
// syntax 1
+this is passed through+

// syntax 2
+++this is passed through too+++

// syntax 3
pass:[also passed-through]
----

[example]
.Example of specifying passthrough text
====
[source,asciidoc]
--
This is a special pass:[𝒞𝓪𝓼𝓮].
--
====

For passthrough of XML syntax or tags to Metanorma XML, which will require
special character processing, use the following command:

[source,adoc]
----
pass:c[xml-content]
----

Where:

`xml-content`:: content that contains XML or SGML tags

[example]
.Example of specifying passthrough XML content
====
[source,asciidoc]
--
pass:c[<u format="num-lit">ᏚᎢᎵᎬᎢᎬᏒ</u>]
--
====

If the passthrough text is intended for one or more target formats, the formats
needs to be specified with the `pass-format`
command [added in https://github.com/metanorma/metanorma-standoc/releases/tag/v1.10.7].

[source,adoc]
----
pass-format:FORMAT[...]
----

Where:

`FORMAT`:: comma-delimited list of target formats.
+
Possible values are:

`metanorma`::: Metanorma Semantic XML
`html`::: HTML
`doc`::: Word DOC
`pdf`::: PDF
`sts`::: STS XML
`ieee`::: IEEE XML
`rfc`::: RFC XML v3
`txt`::: TXT
`html_alt`::: HTML with alternative styling, for ISO only
`isosts`::: ISO STS XML
`all`::: all possible formats [added in https://github.com/metanorma/metanorma-standoc/releases/tag/v2.6.3].
`straightquotes`::: Text with smart quotes ignored [added in https://github.com/metanorma/metanorma-standoc/releases/tag/v3.0.5].

[example]
.Example of specifying passthrough for selected target formats
====
[source,asciidoc]
--
pass-format:rfc[<u format="num-lit">ᏚᎢᎵᎬᎢᎬᏒ</u>]
--
====

NOTE: Text that is marked up as `pass-format` is not subject to substitutions such as smart quotes.
It can be used to keep straight quotes in a document that otherwise uses smart quotes.

The value `pass-format:straightquotes["..."] is used specifically to prevent dumb quotes from being substituted with
smart quotes, but otherwise is treated as Metanorma XML.
