---
layout: author-docs
---
= Passthrough to Metanorma XML and target formats

Passthrough text, such as XML tags, intended to be rendered in a target format unaltered, can be entered
as a passthrough block [added in https://github.com/metanorma/metanorma-standoc/releases/tag/v1.3.27].

This functionality enables automated processing, custom tagging, hacking into intermediary formats and experimental development of Metanorma output.

CAUTION: A broken Metanorma XML file will cause rendering of target formats to
also break. Use with caution.

Passthrough intended to be rendered in Metanorma XML (such as Metanorma XML tags),
generated from Metanorma AsciiDoc input, can be entered as a
passthrough block [added in https://github.com/metanorma/metanorma-standoc/releases/tag/v1.4.1],
with no format indication:

[source,asciidoc]
--
++++
<bibitem>
++++
--

CAUTION: Passthrough text may break the structure of the output
format -- it is the user's responsibility to ensure the integrity
of the resulting structure (e.g. XML) is retained.

Passthrough intended to be rendered in a target format must be specified with
a format indication corresponding to one or more of the existing output formats
of Metanorma in a comma delimited manner
(not limited to: `html`, `doc`, `pdf`, `rfc`, `sts`).

[source,asciidoc]
--
[format=rfc]
++++
<artset>
<artwork>
++++
--

