---
layout: author-docs
title: Tables
---

tag::tutorial[]
Tables are a useful tool to collect and display measured data. As AsciiDoc is all text input, it uses specific symbols to determine where new table rows and columns begin. A simple table looks like this:

[source, AsciiDoc]
----
[cols="1,1"] <1>
.A table with a title <2>
|=== <3>
|Cell in column 1, header row |Cell in column 2, header row <4>

|Cell in column 1, row 2 
|Cell in column 2, row 2 <5>
|=== <6>
----
<1> Attribute that specifies the table. `cols=”x,x”` tells the compiler that there are two columns. `[cols="1,1"]` The numbers specify the amount of spacing. For example, `[cols="4,2,4"]` would define three columns. The first and last column’s width would be four times the relative width and the middle column would be half as broad. This attribute is optional. 
NOTE: In typical AsciiDoc, `[cols="3"]` is considered a shorthand to
`[cols="1,1,1"]`, but this is not supported in Metanorma AsciiDoc.
<2> You can add a table title by beginning the line with a dot `.`. Make sure that there is no space between the dot and the first word of the heading. 
<3> Starting delimiter `|===`
<4> The first line after the delimiter is the header row. To add a column, add a vertical bar `|` before the text that should be in the column. 
<5> When you use the `[cols]` attribute, columns in the same row can appear on different lines of AsciiDoc text; otherwise, they need to all be on the same line of text, like in <4>.
<6> Closing delimiter `|===`

end::tutorial[]
If you need to format the table differently, for example, to join cells or change text alignment, see the https://docs.asciidoctor.org/asciidoc/latest/tables/align-by-cell/[AsciiDoc table documentation]

== Additional Metanorma AsciiDoc metadata 

To provide advanced features for standardization documents, Metanorma AsciiDoc provides additional metadata for tables: 

* `headerrows` defines how many table rows are headers
* `alt` text that is shown when the table can not be displayed (HTML only)
* `summary` text increases a document's accessibility
* `width` defines the total width of the table. Can take a relative (`width=80%`) or an absolute value (`width=600px`)
NOTE: The `width` attribute value aligns with HTML CSS and HTML 4 behavior.

Typical AsciiDoc renders table cell footnotes inside the cell,
and notes trailing the table outside the table.

In Metanorma AsciiDoc:

* table cell footnotes are rendered inside the table
* notes following the table are rendered inside the table footer

.Example of a more complex table
[source,asciidoc]
----
[headerrows=2,alt=Table of maximum mass fraction of defects in husked rice,summary=Table enumerating the permissible mass fraction of defects in husked and various classes of milled rice,width=70%]
|===
.2+|Defect 4+^| Maximum permissible mass fraction of defects in husked rice +
stem:[w_max]
| in husked rice | in milled rice (non-glutinous) | in husked parboiled rice | in milled parboiled rice

| Extraneous matter: organic footnote:[Organic extraneous matter includes foreign seeds, husks, bran, parts of straw, etc.] | 1,0 | 0,5 | 1,0 | 0,5

|===
----

which renders:

.Illustration of a table in Metanorma (DOC output). Configuration: 70% of width, two header rows, one normal row, one footnote.

[TIP]
====
https://raw.githubusercontent.com/metanorma/mn-samples-iso/main/sources/international-standard/body/body-en.adoc[Table 1 in the Metanorma ISO Rice example document] illustrates
a large range of table formatting options. Search for `#table1`.
====


