---
layout: itu-flavor
---

= Authoring ITU documents using Metanorma

== Document attributes

[[note_general_doc_ref_doc_attrib_itu]]
[NOTE]
====
Below are listed only document attributes that are unique to Metanorma’s processing of ITU documents.

For _common document attributes_, see link:/author/ref/document-attributes/[Document attributes reference] in general Metanorma author’s documentation. That page describes attributes that apply to all Metanorma flavors, not just ITU.

For an _introduction to AsciiDoc document attributes_ and how Metanorma uses them, see link:/author/topics/document-format/meta-attributes/[the corresponding topic].
====

=== Document Info

`doctype`::
Document type. Choices:
+
--
* `recommendation` (default)
* `recommendation-supplement`
* `recommendation-amendment`
* `recommendation-corrigendum`
* `recommendation-errata`
* `recommendation-annex`
* `focus-group`
* `implementers-guide`
* `technical-paper`
* `technical-report`
* `joint-itu-iso-iec`
--

`:status:`::
Document status. Synonym: `:docstage:`.  Choices:
+
--
* `in-force`
* `superseded`
* `in-force-prepublished`
* `withdrawn`
--

`:series:`::
Series that the recommendation belongs to. Use full title, for example:
_H: Audiovisual and Multimedia Systems_

`:series1:`::
First level subseries, for example: _IPTV multimedia services and applications for IPTV_
(= H.700–H.789)

`:series2:`::
Second level subseries, for example: _Digital Signage_
(= H.780–H.789)

`:language:` :: The language of the document (only `en` for now; will eventually support
`ar`, `zh`, `en`, `fr`, `ru`, `es`)  (default: `en`)

`:provisional-name:`:: A provisional identifier allocated to the document if the proper
document identifier (`:docnumber:`) is not yet known.

`:ip-notice-received:`:: ITU has received a notice of intellectual property,
protected by patents, which may be required to implement this Recommendation.
(default: `false`)

`:title-(en, fr, es, ar, ru, zh):`:: The title to use, in each of the official languages of the ITU.

`:annexid:`:: The ID to use for the annex, if this document is an annex.

`:annextitle:`:: The title to use for the annex, if this document is an annex.

`:annextitle-(en, fr, es, ar, ru, zh):`:: The title to use for the annex, if this document is an annex,

in each of the official languages of the ITU.


=== Author Info

`:bureau_{i}:`::
Mandatory. Bureau that the document belongs to. Choices: `R` (Radiocommunication),
`T` (Telecommunication Standardization), `D` (Development).
_Defaults to `T`_. `bureau`, `group`, `subgroup`, and `workgroup` together form
a project group, and there may be multiple project groups associated with a document;
each group after the first is indicated by a trailing number, e.g. `bureau_2`, `group_2`.

`:group_{i}:`::
Mandatory. Project group that the document belongs to.

`:grouptype_{i}:`::
Type of Project group that the document belongs to. Permitted values:
`tsag`, `study-group`, `work-group`

`:groupacronym_{i}:`::
Acronym of Project group that the document belongs to.

`:groupyearstart_{i}:`::
Year that Project group study period started.

`:groupyearend_{i}:`::
Year that Project group study period ended.

`:subgroup_{i}:`::
Project subgroup that the document belongs to.

`:subgrouptype_{i}:`::
Type of Project subgroup that the document belongs to. Permitted values:
`tsag`, `study-group`, `work-group`

`:subgroupacronym_{i}:`::
Acronym of Project subgroup that the document belongs to.

`:subgroupyearstart_{i}:`::
Year that Project subgroup study period started.

`:subgroupyearend_{i}:`::
Year that Project subgroup study period ended.

`:workgroup_{i}:`::
Project workgroup that the document belongs to.

`:workgrouptype_{i}:`::
Type of Project workgroup that the document belongs to. Permitted values:
`tsag`, `study-group`, `work-group`

`:workgroupacronym_{i}:`::
Acronym of Project workgroup that the document belongs to.

`:workgroupyearstart_{i}:`::
Year that Project workgroup study period started.

`:workgroupyearend_{i}:`::
Year that Project workgroup study period ended.

=== Recommendation Status

`:recommendation-from:`::
Date from which recommendation status applies

`:recommendation-to:`::
Date to which recommendation status applies

`:approval-process:`::
Approval Process for recommendation status. Legal values: `tap`, `aap`

`:approval-status:`::
Approval status code for recommendation status. Legal values are:
+
--
* For Approval Process `tap`: `determined`, `in-force`
* For Approval Process `aap`: `a`, `lc`, `ac`, `lj`, `aj`, `na`, `ar`, `ri`, `at`, `sg`, `c`, `tap`
--

== Markup

=== Summaries

The summary sections of recommendations are marked up with the
style attribute `[abstract]`.


=== Formulae

By default, formulae are labelled "`Equation`" with a formula sequence number, such as "`Equation 18`".

[source,asciidoc]
--
[stem]
++++
A = B + 100
++++
--

Inequalities are indicated through the option attribute `%inequality`.
They will be shown with a label such as "`Inequality 19`".

[source,asciidoc]
--
[stem%inequality]
++++
A < B
++++
--



=== Annexes

Appendixes are annexes marked as informative instead of normative, which is the default.

Appendixes are numbered
with roman numerals rather than letters, as a separate sequence from normative Annexes.

[source,asciidoc]
--
[appendix,obligation=normative]
== First Annex

[appendix,obligation=informative]
== First Appendix
--

renders as

____
*Annex A*

*First Annex*

(This annex forms an integral part of this Recommendation)

*Appendix I*

*First Appendix*

(This appendix does not form an integral part of this Recommendation)
____

=== References & Bibliography

There is one references section in ITU documents, which is titled `References`. All documents
have the same references boilerplate inserted at the start of the section, which overwrites
any text already supplied before the individual references.

=== Definitions

==== Boilerplate

If no text appears at the start of the clauses and subclauses in the Definitions section,
standard boilerplate is provided automatically:

* If there is a terms subclause "Terms defined elsewhere", we must inject the text "This Recommendation uses the following terms defined elsewhere:" 
or "None", depending on whether any terms are present.
* If there is a terms subclause "Terms defined in this Recommendation", we must inject the text "This Recommendation defines the following terms:" 
or "None", depending on whether any terms are present.
* If neither subclause appears (as is the case in G 650 but not in the documents first sighted), we must inject at the top clause the text 
"This Recommendation defines the following terms:".


