---
layout: ogc-flavor
title: Terms and definitions
---
////
This text is copied and pasted from metanorma.org:staging /learn/tutorial_complete.adoc
Once staging is merged into main --> Reuse
////

== General

//General Metanorma AsciiDoc

Every OGC standard requires a "`Terms and definitions`" clause to hold
terminology entries important to the standard.

The "`Terms and definitions`" section provides a single point of truth for terms
and concepts used within this standard. Content in the "`Terms and definitions`"
section is considered normative.

Optionally, if there are informative terminology entries, OGC allows
a "`Glossary`" section to be set in an Annex, which only consists of
informative terms.

NOTE: OGC has recently adopted similar practice to that of ISO with regards to
the "`Terms and definitions`" clause.

== Terminology models

Terminology entries in OGC and ISO adhere to the terminology model from the
international standard for terminology representation, ISO 10241-1.

The organization of terminology entries within the section should follow
the defined conceptual hierarchies specified in ISO 704.


== Terminology clauses

Normative terms are to be kept in the "`Terms and definitions`" clause, which
is always to be located at Clause 3.

NOTE: Legacy practice may have this clause at Clause 4, but in new publications
this is not allowed.

.Defining the Terms and definitions section
[source,adoc]
----
== Terms and definitions

...
----

.Defining the Glossary section
[source,adoc]
----
[appendix,obligation="informative"]
[heading='terms and definitions']
== Glossary

...
----

NOTE: The initial notice in Terms and Definitions clauses ("This document uses the terms defined in OGC Policy Directive 49...")
is inserted automatically by Metanorma, and you should not type it in to your document.


== Entering terminology entries

There are in general three kinds of terms:

* Terms that are newly defined in this standard;

* Terms that are entirely sourced from another document;

* Terms that are sourced from another document but modified within this
  standard.

A newly defined term:

[source,adoc]
----
=== milled rice
alt:[white rice] <1>

{{husked rice}} from which almost all of the bran and embryo have been removed by milling. <2>
----
<1> `alt:[white rice]` indicates the alternative term for milled rice. Metanorma uses both the notations `alt:[]` and `admitted:[]`,
and normally refers to this as an admitted term (the terminology of ISO); they mean the same thing.
<2> `{{husked rice}}` cites a previously introduced term.


A sourced term:

[source,adoc]
----
=== extraneous matter
alt:[EM]
domain:[rice] <1>

organic and inorganic components other than whole or broken kernels

[example] <2>
Foreign seeds, husks, bran, sand, dust.

[.source]
<<ISO7301,clause 3.3>> <3>
----
<1> Terms can be specified to a certain domain.
<2> If you provide an example, use the `[example]` attribute.
<3> Term is sourced but no modification is done.


A sourced but modified term looks like this:

[source,adoc]
----
=== husked rice <1>
deprecated:[cargo rice] <2>

Paddy from which the husk only has been removed. <3>

[.source] <4>
<<ISO7301,clause 3.2>>, The term "cargo rice" is shown as deprecated, and Note 1
to entry is not included here
----
<1> The term that should be defined is marked as a subheading under the terms and definitions section.
<2> The term `husked rice` supersedes `cargo rice`. To document the old term, use the annotation `deprecated:[term]`.
<3> Definition for the term: the first paragraph of text after commands like `deprecated:[]` and `alt:[]`.
<4> The `[.source]` attribute indicates that a citation follows, indicating where the term definition has been taken from. Make sure to include the dot `.` before source, so that the citation will be rendered correctly.


//OGC specific markup
== More OGC terms and definitions

include::author/ogc/topics/markup.adoc[tag=term-def-ogc,leveloffset=-1]
