---
layout: author-docs
title: Annexes
---
== Annexes

=== General

All annexes must be preceded by the style attribute `[appendix]`, or
([added in https://github.com/metanorma/metanorma-standoc/releases/tag/v1.3.27])
the role attribute `[.appendix]`. The latter can be used to combine the appendix.
with another style attribute, such as `[bibliography]`, though this is not recommended
practice.

Like all clauses, annexes are **normative by default**,
an informative annex is indicated with `[appendix,obligation=informative]`.

The **numbering** of annexes and appendices is automatic:
do not insert "Annex A" or "Appendix 1" as part of the title.

Annex and Appendix **titles** can be left blank, as with Clauses.

=== Term Annexes, Symbols Annexes, Bibliography Annexes

Normally in Metanorma, the sections describing terms and definitions, symbols
and abbreviated terms, and bibliographic references are contained in a main
clause.

However, it is possible for such clauses to be contained in annexes instead. In
fact, this is done by default for the "Terms and References" section in the NIST
flavour of Metanorma.

In rendering, these annexes are treated identically as when those sections were
in the main body.

However, the Metanorma information model does not permit a clause to be an annex
and a terms or a bibliographic clause at the same time.

Such clauses are modelled as an annex *containing* a terms clause or bibliographic clause:

[source,asciidoc]
----
[annex]
== Bibliography

[bibliography]
=== Bibliography
----

In order to render such annexes as expected, the following rules are
applied [added in https://github.com/metanorma/isodoc/releases/tag/v2.0.9]:

* If an annex contains multiple subclauses, it is rendered as usual.
* If an annex contains a single subclause, and that subclause is a Terms & Definitions,
Symbols & Abbreviated Terms, or Bibliographic section,
** The title for that subclause is skipped in rendering
** The subclause itself is skipped for the purposes of numbering; if it has any sub-subclauses
of its own, they are numbered as immediate child clauses of the annex.

So:

[source,asciidoc]
----
[annex]
== Terminology

=== Terms and definitions

==== First Term

==== Second Term
----

is rendered like

____
*Annex A. Terminology*

*A.1 First Term*

*A.2 Second Term*
____
