---
layout: author-docs
title: Attachments
---
== Attachments

There are often occasions where a Metanorma document needs to hyperlink to separate files, that are not
themselves Metanorma documents, but which need to be distributed with the document as local file references.
This could include source code, configuration files, executable binaries, or any other file -- so long
as it is expected to be hyperlinked by Metanorma instead of being processed as a Metanorma file.

In order to signal to Metanorma that there are file attachments, the attachments need to be listed in the
bibliography of the Metanorma document, with the syntax [added in https://github.com/metanorma/metanorma-standoc/releases/tag/v2.8.10]:

[source,asciidoc]
--
* [[[anchor,attachment:(file path of attachment relative to current fileidentifier)]]]
--

For example, the entry `* [[[file1,attachment:(schemas/schema.txt)]]]` indicates that schemas/schema.txt
is an attachment to the current document. It also indicates that any cross-references to `<<file1>>` are
to be interpreted as hyperlinks to that file, and will be so rendered in output.

By default, attachments are binary-encoded within the Metanorma XML file, just as with images. If the
references to attachments are to be kept as file references in the XML file, set the document attribute
`data-uri-attachment: false`.

When the Presentation XML output for a Metanorma document is generated (as a precursor to DOC, HTML and PDF output), 
the documents are output to the folder `{document-filename}_attachments` relative to the output HTML file.

