---
layout: author-docs
title: Extension container
---

== Extension container

=== General

By default the single prefatory clause is identified with the pre-defined
section titles:

* `metanorma-extension`

=== `metanorma-extension` section

The `metanorma-extension` element in Metanorma XML contains miscellaneous data
necessary for the processing of the document, that are not themselves part of
the document.

If a preface clause is named `metanorma-extension` (case-insensitive), its contents
are appended to the `metanorma-extension` element for the
document [added in https://github.com/metanorma/metanorma-standoc/releases/tag/v2.2.7].

This can be used to add data into a document that is not to be rendered, but
which is still needed for processing.

The following features utilize the `metanorma-extension` section:

* link:/author/topics/metadata/history.adoc[detailed revision history encoding]
* https://www.unitsml.org/[UnitsML] definitions of units referenced in the
document, or identifiers used as aliases of anchors in the document.

