---
layout: author-docs
---
= Section Attributes

== Language & script

The language and script of a section is indicated via the optional attributes
`language` and `script`:

[source,asciidoc]
--
[language=fr]
== Section 3

[appendix,script=Zmth]
== Math Appendix
--

== Obligations

The obligation of a section—whether it is normative or informative—is indicated
via the attribute “obligation” (see example below).

For most sections, this is fixed; for annexes and clauses,
the default value of the obligation is "normative" and users need to set the obligation
to "informative" as a section attribute if needed. For example:

[source,asciidoc]
--
[[AnnexA]]
[appendix,obligation=informative]
== Determination of defects
--

== Numbering

As with link:/author/topics/document-format/text#numbering-override[block element numbering],
a clause number may be provided to override auto-numbering.

For instance, in order to number out-of-sequence clauses in updated
documents or amendments [added in https://github.com/metanorma/metanorma-standoc/releases/tag/v1.7.3].

A manual clause number is specified with the attribute `number`:

[source,asciidoc]
----
== Clause 7

[number=0]
=== Zeroth Subclause
----

Elements subsequent to the manually numbered element will be auto-numbered
so as to follow the previous element. This may include incrementing the final
letter in an alphanumeric clause number (e.g. _7a_ followed by _7b_.)

If resumption of auto-numbering is not intended for subsequent clauses
(e.g. _7bis_ should not be followed by _7bit_),
an explicit number also needs to be given to those clauses separately.

== Inline headings

Inline subclause headings (e.g. for test methods) are indicated by preceding the heading
with the `[%inline-header]` option attribute. So in the Rice Model document,

[source,asciidoc]
--
[%inline-header]
==== Sieve,

with round perforations of diameter 1,4 mm.
--

renders as

____
*A.2.1.1. Sieve,* with round perforations of diameter 1,4 mm.
____

