---
layout: author-docs
---

= References & Bibliography

The Normative References and the Bibliography must be preceded by the style attribute
`[bibliography]`, so that the references they contain may be recognized as such. 

All bibliographic entries must be given as unordered lists. The entry must be preceded by a 
bibliographic anchor, in triple brackets: this consists of an internal identifier (used within
Asciidoc for crossreferences), followed by a document identifier

Bibliographic entries for standards are expected to have the standard document
identifier as the item label. References to well-defined standards codes use the document identifiers for citations
(e.g. `ISO 20483:2013`)

[source,asciidoctor]
--
* [[[ref1,ISO 20483:2013]]], _Cereals and cereal products -- Determination of moisture content -- Reference method_
--

Generic references in bibliographies use numbers, which are rendered bracketed, like `[1]`.

[source,asciidoctor]
--
* [[[ref1,1]]], _Cereals and cereal products -- Determination of moisture content -- Reference method_
--

[TIP]
====
Currently the gem only supports formatted citations, which are given as such in the AsciiDoc source.
In the future, we expect to integrate the documents with rendering of Relaton-model bibliographies,
so that the text of the citation itself doesn’t have to be entered by hand.

See link:/author/topics/building/reference-lookup[Automatic reference lookup] topic.
====

== Citations

Citations of references in Metanora are formulated as cross-references; the id crossreferenced is the
internal identifier given for the bibliographic entry (`ref1` in the examples above).

Normally in Asciidoctor, any text in a cross-reference that follows a comma constitutes custom text for the cross-reference. 
So a cross-reference `<<ISO7301,the foregoing reference>>` will be rendered as "the foregoing reference", and hyperlinked to the ISO7301 reference.


== Localities

Citations can include details of where in the document the citation is located (or the word “whole”);
these are entered by suffixing the lowercase type of locality, then an equals sign,
then the locality value or range of values.

Multiple instances of locality and reference can be provided, delimited by comma or colon.
Any trailing text after the sequence of _locality=reference_ (or _locality{space}reference_)
is treated as custom text for the cross-reference, as would occur normally in an Asciidoctor cross-reference.

The locality can appear in quotations if it contains special characters (like dashes or commas).
For example:

[source,asciidoctor]
--
<<ISO7301,clause=3.1-3.4>>

NOTE: This table is based on <<ISO7301,table=1>>.

Sampling shall be carried out in accordance with <<xxx,section="5-3-1,bis">>
--

More examples:

[source,asciidoctor]
--
<<ISO712,the foregoing reference>>     # renders as: the foregoing reference
<<ISO712,section=5, page 8-10>>         # renders as: ISO 712, Section 5, Page 8-10
<<ISO712,section=5, page=8-10: 5:8-10>> # renders as ISO 712, 5:8-10 ("5:8-10" treated as replacement text for all the foregoing)
<<ISO712,whole>>                        # renders as: ISO 712, Whole of text
--

The references cannot contain spaces. Any text following the sequence of localities
will be displayed instead of the localities.

A custom locality can be entered by prefixing it with `locality:`:

[source,asciidoctor]
--
<<ISO712,locality:frontispiece=5, page=8-10>>         # renders as: ISO 712, Frontispiece 5, Page 8-10
--

Custom localities may not contain commas, colons, or space. Localities with the `locality:`
prefix are recognized in internationalization configuration files.

Any text after the bibliographic localities is still treated as custom cross-reference text;
for example:

[source,asciidoctor]
--
<<ISO7301,clause=5,table=1,the foregoing reference>>
--

=== Automatic reference fetching

https://www.relaton.com/[Relaton] can fetch bibliographic entries
for any standards known to have online bibliographic databases (ISO, IEC, IETF, GB, NIST).

Any bibliographic entry recognized through its document identifier prefix
will by default have its bibliographic entry fetched by that gem.
The fetched data overrides any content about the item provided in the document,
since the online bibliography is treated as the source of truth for that standards document.


