---
layout: author-docs
---

= References & Bibliography

== General

The "`Normative References`" and the "`Bibliography`" sections must be
preceded by the style attribute `[bibliography]`, so that the references
they contain may be recognized as such:

[source,asciidoc]
--
[bibliography]
=== Bibliography 1

* [[[id1,1]]] _First reference_
* [[[id1,2]]] _Second reference_
* [[[id3,3]]] _Third reference_
--

Both of these bibliography sections can be split into subsections.

Metanorma AsciiDoc requires each subsection containing references
to be styled with `[bibliography]`, and raises an (ignorable)
warning if the subsections are contained in a section itself
styled with `[bibliography]`.

[source,asciidoc]
--
== Bibliography

[bibliography]
=== Part 1

* [[[id1,1]]] _First reference_
* [[[id1,2]]] _Second reference_
* [[[id3,3]]] _Third reference_

[bibliography]
=== Part 2

* [[[id4,4]]] _Fourth reference_
* [[[id5,5]]] _Fifth reference_
* [[[id6,6]]] _Sixth reference_
--

NOTE: A warning will be raised if `== Bibliography` in the above EXAMPLE was
preceded by `[bibliography]`.

=== Numbering and ordering

All entries in a bibliography section, whether standards or generic,
are renumbered incrementally in the Metanorma XML. If the number for
generic references is updated, all citations of that reference will
be updated as well.

By default, Metanorma does not change the ordering of references in the
bibliography sections from what has been entered by the authors.
Some Metanorma flavours *will* reorder references to suit document
requirements.

That said, all references in a references section are grouped together,
even if there is intervening text in the source document. Only notes
are left attached to their reference, in order to enable annotated
bibliographies.

=== Boilerplate

Any initial text in a Normative Reference section (before the first
reference) is replaced by boilerplate specific to the Metanorma flavour.

== Entering typical references

=== General

Typical bibliographic entries are given as unordered lists.

A single bibliographic entry must be preceded by a
bibliographic anchor, in triple brackets, consisting of:

* an internal identifier (used within Metanorma AsciiDoc for cross-references); and
* a document identifier.

This is illustrated as:

[source,asciidoc]
--
* [[[{anchor},{document identifier or reference tag}]]], _{reference list text}_
--

=== Implied reference tags

Bibliographic entries for standards are expected to have the standard
document identifier as the item label. References to well-defined
standards codes use the document identifiers for citations
(e.g. `ISO 20483:2013`).

This is entered as:

[source,asciidoc]
--
* [[[{anchor},{document identifier as reference tag}]]], _{reference list text}_
--

EXAMPLE:

[source,asciidoc]
--
* [[[ISO20483,ISO 20483:2013]]], _Cereals and cereal products -- Determination of moisture content -- Reference method_
* [[[ISO6540,ISO 6540:1980]]]. _Maize -- Determination of moisture content (on milled grains and on whole grains)_
--

gets rendered as:

____
* ISO 20483:2013. _Cereals and cereal products -- Determination of moisture content -- Reference method_
* ISO 6540:1980. _Maize -- Determination of moisture content (on milled grains and on whole grains)_
____

A well-defined standards code as the item label will by default result in the reference details for the
bibliographic entry being auto-fetched, provided that auto-fetching has been defined for that class of
standard (<<autofetch>>).


=== Numeric reference tags

Generic references in bibliographies, as opposed to standards
references, use numbers, which are rendered bracketed, like `[1]`.

This is entered as:

[source,asciidoc]
--
* [[[{anchor},{number}]]], _{reference list text}_
--

EXAMPLE:

[source,asciidoc]
--
* [[[ISO20483,1]]], _ISO 20483:2013 Cereals and cereal products -- Determination of moisture content -- Reference method_
* [[[ISO6540,1]]]. _ISO 6540:1980 Maize -- Determination of moisture content (on milled grains and on whole grains)_
--

gets rendered as:

____
* [1] _ISO 20483:2013 Cereals and cereal products -- Determination of moisture content -- Reference method_
* [2] _ISO 6540:1980 Maize -- Determination of moisture content (on milled grains and on whole grains)_
____

NOTE: To indicate usage of the numeric reference system, any number
can be entered into the reference tag field. All references are
automatically re-sorted and auto-incremented during compilation.


=== Named reference tags

==== General

References can be tagged with user-supplied alphanumeric labels,
in addition to numbers or standard document identifiers.

These are indicated by wrapping the label within the bibliographic
anchor in brackets.

==== Named reference tag with fully specified bibliographic entry

If the reference text is fully specified, and where no auto-fetching of
the bibliographic entry is necessary, a user-supplied label is entered
using the following syntax:

[source,asciidoc]
--
* [[[{anchor},({reference tag})]]], _{reference list text}_
--

NOTE: These alphanumeric labels will not result in the bibliographic
entry being auto-fetched.

EXAMPLE:

[source,asciidoc]
--
* [[[ISO20483,(CerMoist)]]], _ISO 20483:2013 Cereals and cereal products -- Determination of moisture content -- Reference method_
* [[[ISO6540,(MaiMoist)]]]. _ISO 6540:1980 Maize -- Determination of moisture content (on milled grains and on whole grains)_
--

gets rendered as:

____
* [CerMoist] _ISO 20483:2013 Cereals and cereal products -- Determination of moisture content -- Reference method_
* [MaiMoist] _ISO 6540:1980 Maize -- Determination of moisture content (on milled grains and on whole grains)_
____



==== Named reference tag with automatic reference fetching

Users can provide both their own alphanumeric label, and the
well-defined reference identification code for the standards document.

This will result in the bibliographic entry being auto-fetched, so long
as that auto-fetch is supported for that class of references
[added in https://github.com/metanorma/metanorma-standoc/releases/tag/v1.3.15]:

If a named reference is to be auto-fetched, it is entered by prefixing
the named reference tag (in parentheses) to the document identifier:

[source,asciidoc]
--
* [[[{anchor},({reference tag}){reference identification code}]]], _{reference list text}_
--

EXAMPLE:

[source,asciidoc]
--
* [[[ISO20483,(CerMoist)ISO 20483]]], _ISO 20483:2013 Cereals and cereal products -- Determination of moisture content -- Reference method_
* [[[ISO6540,(MaiMoist)ISO 6540]]]. _ISO 6540:1980 Maize -- Determination of moisture content (on milled grains and on whole grains)_
--

== Alternate bibliography formats

=== Entering formatted citations

For generic references, by default, Metanorma only supports formatted citations,
which are given as such in the AsciiDoc source.

The NIST flavour of Metanorma currently supports rendering of generic references, on an experimental basis.

See link:/author/topics/building/reference-lookup[Automatic reference lookup] topic.


=== Entering Relaton XML

Bibliographic entries can also be given as raw https://www.relaton.com[Relaton XML],
in an AsciiDoc passthrough block. Of course, any Relaton XML BibItem entries
need to be valid, and using correct `id` attributes:

[source,asciidoc]
--
[bibliography]
== Normative References

++++
<bibitem id="doc1">
<docidentifier>ISO 1</docidentifier>
<title>Geometrical product specifications (GPS) -- Standard reference temperature for the specification of geometrical and dimensional properties</title>
</bibitem>
++++
--

=== AsciiBib

Finally, bibliographic entries can be entered as AsciiDoc definition lists, capturing the structure
of Relaton XML. This approach is documented in https://www.relaton.com/specs/asciibib/[relaton.com].

[source,asciidoc]
--
[bibliography]
== Normative References

[%bibitem]
=== Rubber latex -- Sampling
id:: iso123
docid:: 
  type::: ISO
  id::: ISO 123
docid::
  type::: ABC
  id::: 32784
type:: standard
--

== Citations

Citations of references in Metanorma are formulated as cross-references; the ID cross-referenced is the
internal identifier given for the bibliographic entry (`ref1` in the examples above).

In typical AsciiDoc, any text in a cross-reference that follows a comma constitutes custom text for the cross-reference.
So a cross-reference `<<ISO7301,the foregoing reference>>` will be rendered as
"`the foregoing reference`", and hyperlinked to the `ISO7301` reference.

[[localities]]
== Localities

Citations can include details of where in the document the citation is located (or the word "`whole`");
these are entered by suffixing the lowercase type of locality, then an equals sign,
then the locality value or range of values.

Multiple instances of locality and reference can be provided, delimited by comma or colon.
Any trailing text after the sequence of `locality=reference` (or `locality{space}reference`)
is treated as custom text for the cross-reference, as would occur normally in a
typical AsciiDoc cross-reference.

The locality can appear in quotations if it contains special characters (like dashes or commas).
For example:

[source,asciidoc]
--
<<ISO7301,clause=3.1-3.4>>

NOTE: This table is based on <<ISO7301,table=1>>.

Sampling shall be carried out in accordance with <<xxx,section="5-3-1,bis">>
--

More examples:

[source,asciidoc]
--
# renders as: the foregoing reference
<<ISO712,the foregoing reference>>

# renders as: ISO 712, Section 5, Page 8-10
<<ISO712,section=5, page 8-10>>

# renders as ISO 712, 5:8-10
# ("5:8-10" treated as replacement text for all the foregoing)
<<ISO712,section=5, page=8-10: 5:8-10>>

# renders as: ISO 712, Whole of text
<<ISO712,whole>>
--

The references cannot contain spaces. Any text following the sequence of localities
will be displayed instead of the localities.

A custom locality can be entered by prefixing it with `locality:`:

[source,asciidoc]
--
# renders as: ISO 712, Frontispiece 5, Page 8-10
<<ISO712,locality:frontispiece=5, page=8-10>>
--

Custom localities may not contain commas, colons, or space. Localities with the `locality:`
prefix are recognized in internationalization configuration files.

Any text after the bibliographic localities is still treated as custom cross-reference text;
for example:

[source,asciidoc]
--
<<ISO7301,clause=5,table=1,the foregoing reference>>
--

[[autofetch]]
== Automatic reference fetching ("auto-fetch")

https://www.relaton.com/[Relaton] can fetch bibliographic entries
for any standards known to have online bibliographic databases.

Any bibliographic entry recognized through its document identifier prefix
will by default have its bibliographic entry fetched by that gem.
The fetched data overrides any content about the item provided in the document,
since the online bibliography is treated as the source of truth for that standards document.

The format of the standard identifier required for automatic lookup is documented at
link:/author/topics/building/reference-lookup/[Automatic reference lookup].

NOTE: Currently Metanorma supports auto-fetching document identifiers
from: ISO, IEC, IETF, GB, NIST, OGC, CalConnect.


For example, the following will trigger auto-fetching:

[source,asciidoc]
--
* [[[ref1,ISO 20483]]]
--

and gets rendered as:

____
* ISO 20483:2013. _Cereals and cereal products -- Determination of moisture content -- Reference method_
____
