---
layout: author-docs
---

= Requirements, Recommendations, and Permissions

Requirements, Recommendations, and Permissions are encoded as Asciidoctor examples,
with the style attribute value indicating that it is a Requirement, Recommendation, or Permission:

[source,asciidoctor]
--
[permission]
====
I recommend this
====
--

(In the following, "requirement" shall be used as the cover-all term.)

The named attributes `subject` and `label` may be used to indicate the subject of the
requirement, and the conventional label assigned to the requirement. The named attribute
`classification` may be used to give an arbitrary number of key-value pairs of tags describing
the requirement; key-value pairs are delimited by semicolon, key and value are delimited by
colon, multiple values are delimited by comma, 
and key and value are both intended to be tokens (containing no punctuation). The `obligation`
attribute can contain one or more of "requirement", "permission", "recommendation", comma-delimited:
it can be used to override the obligation in the tag name. The `inherit`
attribute may be used to reference the label of a requirement that is imported or
presupposed by this requirement:

[source,asciidoctor]
--
[recommendation,label="/ogc/recommendation/wfs/2",subject="user",inherit="/ss/584/2015/level/1",classification="control-class:Technical;priority:P0;family:System and Communications Protection,System and Communications Protocols",obligation="permission,recommendation"]
====
I recommend this
====
--

Requirements can be nested, as is the case with any delimited block in Asciidoctor,
by adding one more delimiter symbol than its containing block:

[source,asciidoctor]
--
[permission]
====
I permit this
=====
Example 2
=====
[permission]
=====
I also permit this
=====
====
--

The internal structure of a requirement can also be marked up to make it machine-readable,
although this is not expected to be reflected in rendering.

Any text not wrapped in a named open block is considered to be part of a description.
Any text in a named open block allowed under Metanorma is considered to be a separate
subpart of the requirement: that includes the measurement target  (for quantitative requirements),
the verification steps, imports (code stubs), and specifications (which may be considered
the object of the requirement). These blocks can have types, referring to the conventions
or computer frameworks that they follow.

Text in a named open block may be include or consist of machine readable code; any such
code needs to be wrapped in turn in a source code element, which is expected to
contain an attribute giving the computer language the block is expressed in.
(The notion of "language" may be expanded to include a particular computer framework
that the code is to be run under.)
`[sourcecode,text]` is taken as meaning that the block is still human readable.
The language of a source code block is likely to be distinct from the type of named block
it is contained in.

By default, both named blocks and descriptions will be included in the document output.
Often, though not always, the named blocks contain machine-readable code which is not
intended to be included in the document output, but is supplemental to the human-readable
description. That is signalled through the options attribute `exclude` on the named block.

The label attribute is always rendered if present. The subject attribute is never rendered.

[source,asciidoctor]
--
[recommendation,label="/ogc/recommendation/wfs/2",subject="user"]
====
I recommend _this_.
[specification,type="tabular"]
---
This is the object of the recommendation:
|===
|Object |Value
|Mission | Accomplished
|===
---
As for the measurement targets,
[measurement-target]
---
The measurement target shall be measured as:
[stem]
++++
r/1 = 0
++++
---
[verification,type="comprehensive"]
---
The following code will be run for verification:
[source,CoreRoot]
----
CoreRoot(success): HttpResponse
if (success)
  recommendation(label: success-response)
end
----
---

[import%exclude]
---
[source,CoreRoot]
----
success-response()
----
---
====
--

