---
layout: author-docs
---

= Text formatting

=== Format-independent links

Typical links created by the `link` command require the correct file path that
includes the file suffix (e.g. `.html` for HTML documents).

When linking a Metanorma document to another Metanorma document, which can be
rendered into multiple output formats with different suffixes
(such as in HTML, PDF or DOC), the option `update-type=true` can be specified
to achieve format-independent
links [added in https://github.com/metanorma/metanorma-standoc/releases/tag/v1.9.4].

When the option `update-type=true` is given, the rendered link will provide the
correct file paths dependent on the output format.

The following conditions must be satisfied to use format-independent links:

* The link shall be relative and not absolute
* The link shall not have a file suffix

[example]
.Example of links to other Metanorma documents
====
[source,asciidoc]
----
link:../parent[update-type=true]
link:../child[This is the child document,update-type=true]
----

This will render the following links depending on the output format:

* in HTML, `../parent.html` and `../child.html`
* in PDF, `../parent.pdf` and `../child.pdf`
====



== Examples

=== Explicitly-defined terminology examples

Normally, examples are only tagged as term examples when they appear in the
context of a terms section.

Rarely, term notes need to be presented in isolation, including in ISO Amendments or
Technical Corrigenda.

To achieve that, mark the example up with `%termexample` [added in https://github.com/metanorma/metanorma-standoc/releases/tag/v2.1.2].

[source,asciidoc]
--
[%termexample]
====
Bibliographic note
====
--

== Admonitions

=== General


