---
layout: author-docs
---

= Reading structured data (YAML) into Metanorma content

yaml2text block allows to include content of yaml files into the document.

== Examples
=== An array of strings

Given:
strings.yaml

[source,yaml]
--
---
- lorem
- ipsum
- dolor
--

[source,asciidoc]
--
[yaml2text,strings.yaml,ar]
----
{ar.*,s,EOS}
=== {s.#} {s}

This section is about {s}.

{EOS}
----
--

Syntax is: [yaml2text, YAML file path , self-defined context name ]

Here, the file path is strings.yaml, and context name is s.

`{s.#}` gives the zero-based position of item s in the parent array yaml.items.

Expect:

[source,text]
--
=== 0 lorem

This section is about lorem.

=== 1 ipsum

This section is about ipsum.

=== 2 dolor

This section is about dolor.
--

=== A hash
Given:

hash.yaml
[source,yaml]
--
---
name: Lorem ipsum
desc: dolor sit amet
--

Usage:

[source,asciidoc]
--
[yaml2text,hash.yaml,my_item]
----
=== {my_item.name}

{my_item.desc}
----
--

Expect:
[source,text]
--
=== Lorem ipsum

dolor sit amet
--

Named hash key:
[source,asciidoc]
--
[yaml2text,hash.yaml,my_item]
----
{my_item.*,key,EOI}
=== {key}

{my_item[key]}

{EOI}
----
--

Array / hash items can be de-referenced with square brackets, e.g. {yaml.items[s.#]}, {my_hash[key_name]}.
Hash items should only be de-referenced with item key and not with integer index.

Expect:
[source,text]
--
=== name

Lorem ipsum

=== desc

dolor sit amet
--

Also hash items can use `keys` and `values` attributes:

[source,asciidoc]
--
[yaml2text,hash.yaml,item]
----
.{item.values[1]}
[%noheader,cols="h,1"]
|===
{item.*,key,EOK}
| {key} | {item[key]}

{EOK}
|===
----
--

Expect:
[source,text]
--
.dolor sit amet

[%noheader,cols="h,1"]
|===
| name | Lorem ipsum
| desc | dolor sit amet
|===
--

=== An array of hashes
Given:
array_of_hashes.yaml
[source,yaml]
--
---
- name: Lorem
  desc: ipsum
  nums: [2]
- name: dolor
  desc: sit
  nums: []
- name: amet
  desc: lorem
  nums: [2, 4, 6]
--

Usage:
[source,asciidoc]
--
[yaml2text,array_of_hashes.yaml,ar]
----
{ar.*,item,EOF}

{item.name}:: {item.desc}

{item.nums.*,num,EON}
- {item.name}: {num}
{EON}

{EOF}
----
--
Different contexts are referred to by the name defined, e.g. ar, item, num.
Scopes are delimited by self-defined heredoc-esque markers, e.g. EOF, EON.

[source,text]
--
Expect:
Lorem:: ipsum

- Lorem: 2

dolor:: sit


amet:: lorem

- amet: 2
- amet: 4
- amet: 6
--

=== An array with interpolated file names, etc. for Asciidoc's consumption

Given:
strings.yaml
[source,yaml]
--
---
prefix: doc-
items:
- lorem
- ipsum
- dolor
--

Usage:
[source,asciidoc]
--
[yaml2text,strings.yaml,yaml]
------
First item is {yaml.items[0]}.
Last item is {yaml.items[-1]}.

{yaml.items.*,s,EOS}
=== {s.#} -> {s.# + 1} {s} == {yaml.items[s.#]}

[source,ruby]
----
include::{yaml.prefix}{s.#}.rb[]
----

{EOS}
------
--

Negative array indices wraps around from the end like Ruby Arrays do.

Expect:
[source,text]
--
First item is lorem.
Last item is dolor.

=== 0 -> 1 lorem == lorem

[source,ruby]
----
include::doc-0.rb[]
----

=== 1 -> 2 ipsum == ipsum

[source,ruby]
----
include::doc-1.rb[]
----

=== 2 -> 3 dolor == dolor

[source,ruby]
----
include::doc-2.rb[]
----
--