---
layout: flavor

docs_title: Metanorma for ISO
title: Quickstart with ISO standards using Metanorma

iso_flavor:
  implemented_by: metanorma-iso
  title: ISO
  markup_name: Metanorma for ISO
  build:
    cli_flags: "--type iso -x html,doc,xml"
  sample:
    title: Rice
    repo_url: https://github.com/metanorma/mn-samples-iso
    rendered_url: https://metanorma.github.io/mn-samples-iso/
  docs_entry_points:
    - path: ./topics/
      title: topics

navigation:
  items:
  - title: Get started
    path: /
  - title: Sample
    path: /sample/
  - title: Usage
    path: /topics/
    items:
    - title: Markup
      path: /topics/markup/
    - title: Output formats
      path: /topics/formats/
    - title: Style validation
      path: /topics/content-validation/
  - title: Reference guides
    path: /ref/
    items:
      - title: Document attributes
        path: /ref/document-attributes/

base_url: /author/iso
---

== Inline Markup

=== Links and Cross-References
In Metanorma, you can link to other Metanorma documents by providing an attribute update-type=true after specifying the link. This attribute changes the link type depending on the output format (HTML, PDF, DOC) you are looking for. 
For instance,

[source,console]
----
link:../parent[update-type=true]
link:../child[This Is The Child Document,update-type=true]
----

This will link to ../parent.html in HTML or ../parent.pdf in PDF format. 
[NOTE]
The link provided should be a relative link and not absolute one. Also, it should not contain any file type suffix. 
<cross-references is already added by Tina>

=== Index Terms
<Tina has already defined all the content, just adding a small section>
Index Terms as per output formats:
The hierarchy of terms differs for different output formats:
.PDF– 
In PDF output format, the index renders as page numbers.
.HTML/DOC– 
In HTML or DOC output format, indexes follow the just defined element like note, example, figure, formula etc.

[NOTE]
Currently, the only flavors that support indexing terms are ISO, IETF, and BIPM. Although, formatting index terms is not supported in IETF. 
