---
layout: iso-flavor
---

= AsciiISO markup

== Cross-references

Custom cross-references should not be used in ISO standards,
either for an external reference, or for a section of the current document:
ISO/IEC DIR 2 requires any cross-references to be transparent in text.

For example, a cross-reference to the anchor such as:

[source,asciidoctor]
--
[[tabular]]
--

on clause 5 should be given as just:

[source,asciidoctor]
--
<<tabular>>
--

…and custom text will be automatically rendered as `Clause 5` by Metanorma-ISO.

ISO clause references will suppress the word "Clause" before a subclause reference,
following ISO/IEC DIR 2: `<``<ISO24333,clause=5>``>` will be rendered as _ISO 24333, Clause 5_,
but `<``<ISO7301,clause=3.1>``>` will be rendered as _ISO 7301, 3.1_.

== Bibliographies

All references under Normative References are expected to have such a standard document identifier. For example:

[source,asciidoc]
--
* [[[ricepotentialmilling,ISO 6646]]], _Rice -- Determination of the potential milling yield from paddy and from husked rice_
* [[[ISOGuide73, ISO Guide 73:2009]]], _Risk management -- Vocabulary_
--

[subs="quotes"]
ISO 6646 in this example would be cited from elsewhere in the document through crossreferences to the `ricepotentialmilling` identifier; e.g. `<< ricepotentialmilling>>` (which will be rendered as `ISO 6646`), `<<``ricepotentialmilling, section 5``>>` (which will be rendered as `ISO 6646, Section 5`), `<<``ricepotentialmilling,section 5: the foregoing discussion``>>` (which will be tagged in the XML representation as Section 5 of ISO 6646, but will be displayed as `the foregoing discussion`.)

ISO treats dated and undated references as separate (an undated reference is taken to
refer to the latest published edition of that reference.) if reference is to be made to
both an undated and a dated version of an ISO reference, these need to be explicitly listed as
separate references.


[TIP]
====
If an ISO reference is in preparation, ISO/IEC DIR 2 dictates that details of the reference status be given as a footnote. In Asciidoc, this is done by giving the date as a double dash, and following the bibliographic anchor with a footnote macro:

[source,asciidoc]
--
* [[[ISO16634,ISO 16634:--]]] footnote:[Under preparation. (Stage at the time of publication ISO/DIS 16634)], _Cereals, pulses, milled cereal products, oilseeds and animal feeding stuffs -- Determination of the total nitrogen content by combustion according to the Dumas principle and calculation of the crude protein content_
--

If an ISO reference includes all parts of the standard, that is indicated by appending `(all parts)` after the reference anchor:

[source,asciidoc]
--
* [[[ISO16634,ISO 16634 (all parts)]]] _Cereals, pulses, milled cereal products, oilseeds and animal feeding stuffs -- Determination of the total nitrogen content by combustion according to the Dumas principle and calculation of the crude protein content_
--
====

In informative references, references to standards documents are still given with the same format of bibliographic anchor, and they are cited by their document identifier -- although they are displayed with an incrementing reference number in brackets, for consistency with any bibliographic entries that are not standards documents. ISO references appear before non-ISO references. So

[source,asciidoc]
--
[bibliography]
== Bibliography

* [[[ISO3696,ISO 3696]]], _Water for analytical laboratory use -- Specification and test methods_
...
* [[[ref11,11]]] Nitrogen-ammonia-protein modified Kjeldahl method -- Titanium oxide and copper sulfate catalyst. _Official Methods and Recommended Practices of the AOCS_ (ed. Firestone, D.E.), AOCS Official Method Ba Ai 4-91, 1997, AOCS Press, Champaign, IL
--

is displayed as:

[quote]
____
*Bibliography*

[1] ISO 3696, _Water for analytical laboratory use -- Specification and test methods_
...
[11] Nitrogen-ammonia-protein modified Kjeldahl method -- Titanium oxide and copper sulfate catalyst. _Official Methods and Recommended Practices of the AOCS_ (ed. Firestone, D.E.), AOCS Official Method Ba Ai 4-91, 1997, AOCS Press, Champaign, IL
____

The entries in the Bibliography are reordered (and, for numerical references, renumbered) according to the following criteria:

* Document class (as defined in the ISO sample Rice document): standard which ISO has published or co-published; standard which IEC has published or co-published; other standards; other documents.
** Standards are identified by the use of a code for the document identifier, as opposed to a number.
* Document identifier type (as a proxy for the standards setting body)
* Document number (the numeric portion of the standards identifier, sorted numerically)
* Full document identifier
* Document title

The bracketed reference numbers are expected to be correct and in order (accounting for the fact that references to standards will end up numbered): they are not overriden in rendering.

== Annexes & appendices

In ISO, Appendixes to annexes can occur, although they are not mentioned in ISO/IEC DIR 2; ISO/IEC DIR 1 features them. They are marked up as immediate subsections of annexes, and must be tagged with an option attribute of "appendix":

[source,asciidoc]
--
[appendix]
== Annex A
Text

[%appendix]
=== Appendix 1
Text
--

== Additional warning types

Metanorma AsciiDoc natively supports the ISO admonitions
"`Caution`", "`Warning`", and "`Important`" through its
admonition syntax:

[source,asciidoctor]
--
CAUTION: This is a single-block caution

[WARNING]
====
This is a

multiple-block warning
====
--

If the admonitions "Danger" and "Safety Precaution" are needed, they should be indicated
through a `type` attribute, which will override the admonition type appearing in the AsciiDoc:

[source,asciidoctor]
--
[type=Danger]
CAUTION: This is a single-block caution

[WARNING,type=Safety Precaution]
====
This is a

multiple-block warning
====
--

== Terms and Definitions

=== Title

The title of a top-level Terms and Definitions clause is populated automatically,
overriding the title provided by the user: if it contains a Symbols and Abbreviated Terms subclause,
it is titled _Terms, definitions, symbols and abbreviated terms_,
otherwise it is titled _Terms and definitions_.

Symbols and Abbreviated Terms subclauses are also automatically titled;
other subclauses of Terms and Definitions clauses are not.


== Lists

Unordered lists in Word are rendered with em-dashes instead of bullets, as preferred by ISO.

