////
Checkboxes: 
[%interactive]
* [*] checked
* [x] also checked
* [ ] not checked
* normal list item 
////

tag::exercise-2-1[]

Now it’s your turn. Fill the document with the following attributes: 

[%interactive]
* [ ] Document title
* [ ] Your name
* [ ] Your organization using the `:publisher:` attribute
* [ ] Your organization's address
* [ ] The document class: `standoc`
* [ ] The document type: `document`
* [ ] The language
* [ ] The copyright year

.Hint
[%collapsible]
====
To declare an attribute, follow the syntax `:attribute: value`. 

For example: `:publisher: Ribose Inc.`
====
end::exercise-2-1[]

tag::exercise-2-2[]
Look at the prepopulated Metanorma document. There are many clauses describing the content but there are sections missing to form a correct standard document. 
Add the following sections:

[%interactive]
* [ ] Foreword on line 13
* [ ] Introduction on line 21
* [ ] Terms and definitions on line 27
* [ ] Bibliography on line 60

end::exercise-2-2[]
Add lists to the prepopulated document.

[%interactive]
* [ ] Add an unordered list in line xx
* [ ] Add an ordered list in line xx
* [ ] Add a definition list in line xx


tag::exercise-2-3[]
Add a definition, alternative terms, deprecated terms, definitions

end::exercise-2-3[]

tag::exercise-2-4[]
Create a new table
end::exercise-2-4[]

tag::exercise-2-5[]
Insert a graphic from a url
URL raussuchen
end::exercise-2-5[]

tag::exercise-2-6[]
Write 3 admonitions
end::exercise-2-6[]

tag::exercise-2-7[]
Enter the following ruby/java/python code as a sample into the document and check the output. 
end::exercise-2-7[]

tag::exercise-2-8[]
Mark up the following text using the text formatting options above.
end::exercise-2-8[]

tag::exercise-2-9[]
Create a new index section at the bottom of the document
Define index entries for the following words in the document:
Word 1
Word 2
Word 3
Word 4
Word 5
Add a second level and third level to the words:
Word 2, Second word, ..
Word 3, second word, ..
Word 5, second word, ..

end::exercise-2-9[]

tag::exercise-2-10[]
Look at the following document and implement an internal reference for the figure and for a table. --> maybe split into several exercises
end::exercise-2-10[]

tag::exercise-2-11[]
end::exercise-2-11[]

tag::exercise-3-1[]
end::exercise-3-1[]

tag::exercise-3-2[]
Enter the command `metanorma document.adoc` into the terminal and see what happens.
end::exercise-3-2[]

tag::exercise-4[]
end::exercise-4[]