//This file contains all the lessons for the tutorials. Since there was no template while Tina contributed to Metanorma, you'll find all lessons here, and you can copy the inlcudes into the tutorial templates later. 
//All content that isn't fit for reuse elsewhere, for example the "Summary" sections, can be written into the file directly. 
//Should you have any questions, you can contact me via e-mail (tina@kickoke.com). 

//Lesson 1
== Introduction to Metanorma

include::../tutorials/learning_objectives.adoc[tag=learningobjectives-1]
>> Start next lesson 

//Lesson 1-1
== What is Metanorma?
=== What you get is what you see vs. What you get is what you mean
include::../author/concepts/wysiwyg_vs_wysiwym.adoc[tag=tutorial]
=== What is Metanorma?
include::../author/concepts/what_is_Metanorma.adoc[tag=tutorial]

Let’s explore the workflow of Metanorma in the next lesson.
>> Start next lesson 

//Lesson 1-2
== The Metanorma Workflow

include::../author/concepts/Metanorma_workflow.adoc[tag=tutorial, leveloffset=+1]

Before we dive into AsciiDoc, let's summarize what we've covered so far.
>> Start next lesson 

//Lesson 1-3
=== Summary

Let’s recap what we’ve learned so far:

* Metanorma uses a what you see is what you mean (WYSIWYM) approach, meaning that the text you write is what you *want* to see.
* You need to render documents to have a correct visible output. The appearance is controlled in a stylesheet.
* Metanorma is an umbrella term for several things and consists of: +
The Metanorma toolchain, document models and a XML schema of these document models.
* Metanorma documents use Metanorma AsciiDoc markup 
* When you want to generate an output, the AsciiDoc document is converted into XML in order to be checked against the XML schema.
* If the document is valid, Metanorma generates an HTML, PDF and Microsoft Word (`.doc`) output. 

Now that we have covered the fundamentals, let’s have a look at AsciiDoc.
>> Start next lesson

//Lesson 2 
== Introduction to AsciiDoc

include::../tutorials/learning_objectives.adoc[tag=learningobjectives-2]

include::../author/concepts/intro_to_asciidoc.adoc[tag=tutorial, leveloffset=+2]

We will have a look at these different levels of markup in the following lessons. 
You can do the exercises either in the browser, or on your local machine. If you choose to use your local machine, you will need to https://www.metanorma.org/install/[install Metanorma] and set up a new Metanorma project. 

>> Start next lesson

//Lesson 2-1
== The Header
include::../author/topics/metadata.adoc[tag=tutorial]

[[exercise-2-1]]
include::exercises.adoc[tag=exercise-2-1]

Let’s add some sections to our document in the next lesson.
>> Start next lesson 

//Lesson 2-2
== Sections

include::../author/topics/sections.adoc[tag=tutorial]

[[exercise-2-2]]
include::exercises.adoc[tag=exercise-2-2]

We’ve built the basic structure of a Metanorma document. Let’s add some content to our document in the next lesson.
>> Start next lesson 

//Lesson 2-3
== Blocks
include::../author/topics/blocks.adoc[tag=tutorial]

Let’s look at lists in the next lesson. 
>> Start next lesson

//Lesson 2-3-1
=== Lists

include::../author/topics/blocks/lists.adoc[tags=tutorial,leveloffset=+2]

[[exercise-2-3-1]]
include::exercises.adoc[tag=exercise-2-3-1]

Great work! Let’s have a look at term definitions in the next lesson.
>> Start next lesson

//Lesson 2-3-2; Incorporate Tutorial content into author/topics/terms/ when reworking terms_definitions.adoc

=== Term definitions
If you want to cite a term throughout the standard, include it in the terms and definitions section. Term definitions vary from definition lists, as they are more granular and provide metadata to mark features such as alternative terms or deprecated terms. 
Let’s have a look at a term entry:

[source, AsciiDoc]
----
== Terms and definitions <1>

=== husked rice <2>
deprecated:[cargo rice] <3>

Paddy from which the husk only has been removed. <4>

[.source] <5>
<<ISO7301,clause 3.2>>, The term "cargo rice" is shown as deprecated, and Note 1 to entry is not included here

=== milled rice
alt:[white rice] <6>

term:[husked rice] from which almost all of the bran and embryo have been removed by milling. <7>

=== extraneous matter
alt:[EM]
domain:[rice] <8>

organic and inorganic components other than whole or broken kernels

[example] <9>
Foreign seeds, husks, bran, sand, dust.
----
<1> The start of the terms and definitions section
<2> The term that should be defined is marked as a subheading using three equal signs. `===`.
<3> The term `husked rice` supersedes `cargo rice`. To document the old term, use the annotation `deprecated:[term]`.
<4> Definition for the term: the first paragraph of text after macros like `deprecated:[]` and `alt:[]`.
<5> The `[.source]` attribute indicates that a citation follows, indicating where the term definition has been taken from. Make sure to include the dot `.` before source, so that the citation will be rendered correctly. 
<6> `alt:[white rice]` indicates the alternative term for milled rice. 
<7> `term:[husked rice]` cites the previously introduced term.
<8> Terms that do not obviously belong to a certain domain can be annotated with `domain:[]` at the start of their definition.
<9> If you provide an example, use the `[example]` attribute so that it renders according to the styling rules of your SDO. 


[[exercise-2-3-2]]
include::exercises.adoc[tag=exercise-2-3-2]

The next type of block we will cover are tables.
>> Start next lesson

//Lesson 2-3-3
=== Tables
include::../author/topics/blocks/tables.adoc[tag=tutorial]

[[exercise-2-3-3]]
include::exercises.adoc[tag=exercise-2-3-3]

Let’s look at inserting images next.
>> Start next lesson

//Lesson 2-3-4
=== Images
include::../author/topics/blocks/images.adoc[tag=tutorial]

[[exercise-2-3-4]]
include::exercises.adoc[tag=exercise-2-3-4]

Let’s look at admonitions next.
>> Start next lesson

//Lesson 2-3-5
=== Admonitions
include::../author/topics/blocks/admonitions.adoc[tag=tutorial,leveloffset=+2]
[[exercise-2-3-5]]
include::exercises.adoc[tag=exercise-2-3-5]

Great progress so far! Let's look at code samples in the next lesson.
>> Start next lesson

//Lesson 2-3-6
=== Code Samples
include::../author/topics/blocks/code_samples.adoc[tag=tutorial]
[[exercise-2-3-6]]
include::exercises.adoc[tag=exercise-2-3-6]

We’re done with blocks - good job! The next lesson covers inline markup. 
>> Start next lesson

//Lesson 2-4
== Inline Markup
include::../author/topics/inline_markup.adoc[tag=tutorial]

Let’s look at these features in the following lessons.
>> Start next lesson

//Lesson 2-4-1
=== Text markup
include::../author/topics/inline_markup/text_formatting.adoc[tag=tutorial,leveloffset=+2]
==== Footnotes
include::..//author/topics/inline_markup/footnotes.adoc[tag=tutorial]
[[exercise-2-4-1]]
include::exercises.adoc[tag=exercise-2-4-1]

Let’s look at a more advanced form of inline formatting: index entries
>> Start next lesson

//Lesson 2-4-2
=== Index Terms
include::../author/topics/inline_markup/index.adoc[tag=tutorial]
[[exercise-2-4-2]]
include::exercises.adoc[tag=exercise-2-4-2]

In the next lesson, we will cover references and links. 
>> Start next lesson

//Lesson 2-4-3
=== References
include::../author/topics/inline_markup/links.adoc[tag=tutorial]
=== Bibliographic entries
include::../author/topics/sections/entering_bib.adoc[tag=tutorial]
[[exercise-2-4-3]]
include::exercises.adoc[tag=exercise-2-4-3]


Let’s summarize what we’ve learnt so far.
>> Start next lesson

//Lesson 2-4-4
=== Summary

We’ve covered a lot of ground, so here is a quick summary for you:

* Each Metanorma document contains metadata in the header using the colon notation `:attribute:`.
* A Metanorma document consists of several predefined sections. The document model of your organization dictates which are optional and which are mandatory. Sections are invoked using equal signs `=`.
* Blocks are entities that belong together, such as paragraphs, lists, tables, etc. Paragraphs and lists do not need to be marked by delimiters. The remaining block types begin and end with a delimiter, for example four dashes `----`.
* Inline markup is used for text formatting and references. You can reference:
** an external source (`URL[Link text]`) 
** Metadata (`{attribute}`)
** Places in the document by setting an anchor (`[[anchor-id]]`) and referencing the anchor (`<<anchor-id>>`)
** Bibliographic entries + 
[source, AsciiDoc]
----
* [[[anchor,document identifier or reference tag]]], _reference list text_
<<anchor>>
----

You did a great job so far! Let’s talk about reviewing documents in the next lesson. 
>> Start next lesson

//Lesson 3
== Reviewing Metanorma Documents

include::../tutorials/learning_objectives.adoc[tag=learningobjectives-3]

>> Start next lesson

//Lesson 3-1
=== Adding Comments

include::../author/topics/reviewing.adoc[leveloffset=1]

[[exercise-3-1]]
include::exercises.adoc[tag=exercise-3-1]

Now that we've commented on the content, let's create a draft of the document. 
>> Start next lesson

//Lesson 3-2 Add to docs
=== Rendering a Draft Document

To render a draft that your peers should review, you need to add these metadata to the document header:

* `:draft:`: Tells the compiler to display comments in the final output
* `:status: draft` Defines the current document stage. +
NOTE: Some flavors, for example ISO, use `:docstage:` and a status code to indicate in what stage the document is.

To compile a Metanorma document you must enter the name of the application `Metanorma` and the document you want to compile `document.adoc`. 

[source, shell]
----
Metanorma document.adoc
----
With this command you trigger the Metanorma toolchain to:

* Read the AsciiDoc input
* Convert it into XML
* Check the XML against the document model (XML schema)
* Create HTML, PDF, and DOC output

[[exercise-3-2]]
include::exercises.adoc[tag=exercise-3-2]


Now that you are familiar with the simplest way of creating a Metanorma document, let's look at different ways to compile documents in the next lesson.
>> Start next lesson

//Lesson 4
== Publishing a Metanorma Document

include::../tutorials/learning_objectives.adoc[tag=learningobjectives-4]

>> Start next lesson

//Lesson 4-1
=== Compiling a Metanorma Document

To successfully compile a Metanorma document, the toolchain looks at:

* Metadata: The title, document flavor, and document type.
* Syntax: Is the entered AsciiDoc code correct?
* Dependencies: Are all tools needed to compile the document installed?
* File references: Are any files referred to by the file being compiled, and is their path entered correctly, for example when you include images (`image::PATH[]`). Advanced AsciiDoc usage also allows a document to embed other AsciiDoc documents (`include::PATH[]`), and Metanorma extends this in advanced usage to external data sources. 

To compile a Metanorma document:

. On the command line, go to the folder where the document you want to compile is located. 
. Enter the following command: +
[source, shell]
----
Metanorma document.adoc
----
With this command you trigger the Metanorma toolchain to:

* Read the AsciiDoc input
* Convert it into XML
* Check the XML against the document model (XML schema)
* Create HTML, PDF, and DOC output

You can also manipulate the way Metanorma compiles a document by setting flags. Flags are appended to the build command, like this:  

.Example of a build command with a flag
[source, shell]
----
Metanorma document.adoc -x html
----

You can use the following flags to manipulate the building process:

* `-t`: Sets the flavor of the document +
NOTE: Either define the flavor in the metadata using `mn-document-class` or use `-t flavor`
* `-x`: Sets the output format(s) of the document 
* `-o`: Enter a path that the output should be saved to. 

To see the full list of possible build commands, open the Metanorma help on the command line.

[source, shell]
----
Metanorma help compile
----

>> Start next lesson

// Lesson 4-2
=== Troubleshooting
include::../author/topics/troubleshooting.adoc[tag=tutorial,leveloffset=+2]
include::../author/topics/troubleshooting.adoc[tag=no-compile-markup,leveloffset=+1]
include::../author/topics/troubleshooting.adoc[tag=rendering-errors,leveloffset=+1]


//Exercise will promt the user to fix some bugs in a document: For example syntax errors. 
include::exercises.adoc[tag=exercise-4]
>> Start next lesson

// Lesson 4-2
=== Summary
Let's summarize what we've learnt in this lesson:

* To generate a Metanorma document, enter the following command: +
[source, shell]
----
Metanorma document.adoc
----

* More often than not, we encounter errors that we need to fix:

** Metadata errors: Provide all metadata that your organization mandates; include the flavor type and document type either in the header or in the build command.
** Markup errors: Make sure you've entered the correct syntax for blocks or inline macros and provided the correct filenames and paths. 
** Reference errors: If a reference can't be resolved, make sure that the anchor name follows the naming rules; The anchor and the reference need to be identical. 
** Bugs: Sometimes, when you can't solve an error, you might have discovered a bug. Feel free to raise an issue in your organization's repository on the https://github.com/Metanorma[Metanorma Github page].


Great work! 
>> Finish the tutorial
// Maybe include a page after the tutorial where a user can type in their name and a certificate (PDF) will be generated + downloaded? :)
