---
layout: ieee-flavor
---

= Metanorma IEEE SA document attributes

[[note_general_doc_ref_doc_attrib_ieee]]
[NOTE]
====
Document attributes listed below are unique to the processing of IEEE SA documents
in Metanorma.

For _common document attributes_, see link:/author/ref/document-attributes/[Document attributes reference] in general Metanorma author's documentation. That page describes attributes that apply to all Metanorma flavors, not just IEEE SA.

For an _introduction to Metanorma AsciiDoc document attributes_ and how Metanorma uses them, see link:/author/ref/document-attributes/[the corresponding topic].
====

== Document information

`docnumber`:: In IEEE SA terms: the designation number for the document. Do not include the initial "P".
+
.Example for IEEE SA `docnumber`
[example]
====
[source,adoc]
----
:docnumber: 2830
----
====

`partnumber`:: The document part number, where applicable [added in https://github.com/metanorma/isodoc/releases/tag/v1.0.12].
`subpartnumber`:: The document subpart number, where applicable [added in https://github.com/metanorma/isodoc/releases/tag/v1.0.12].

`conformance`:: Specification of the conformance of the document, where applicable (e.g. _Conformance_ `02-2021`)  [added in https://github.com/metanorma/isodoc/releases/tag/v1.0.12].

`draft`:: The draft number. Use together with `:docstage: draft`. Do not include the initial "D".
+
.Example for IEEE SA `docstage`
[example]
====
[source,adoc]
----
:docstage: draft
:version: 2
----
====

`edition`:: The edition number of the document. In case that a document is a
draft, the edition number indicates the intended edition number.
+
.Example for IEEE SA `edition`
[example]
====
[source,adoc]
----
:edition: 1
----
====

`amendment-number`:: (only when `docsubtype` is set to `amendment`) The number of the amendment.

`corrigendum-number`:: (only when `docsubtype` is set to `corrigendum`) The number of the corrigendum.

`isbn-pdf`:: The ISBN of the PDF document in ISBN-13 format.
+
.Example for IEEE SA `isbn-pdf`
[example]
====
[source,adoc]
----
:isbn-pdf: 978-1-5044-7724-6
----
====

`isbn-print`:: The ISBN of the print document in ISBN-13 format.
+
.Example for IEEE SA `isbn-print`
[example]
====
[source,adoc]
----
:isbn-print: 978-1-5044-7725-3
----
====

`stdid-pdf`:: The final standard identifier of the PDF document.
+
.Example for IEEE SA `stdid-pdf`
[example]
====
[source,adoc]
----
:stdid-pdf: STD24807
----
====

`stdid-print`:: The final standard identifier of the print document.
+
.Example for IEEE SA `stdid-print`
[example]
====
[source,adoc]
----
:stdid-print: STDPD24807
----
====

`docstage`:: Document stages. Allowed values are:

`draft`::: This document is in draft stage, being developed.

`approved`::: (default) This document has been approved by the IEEE SASB.
+
NOTE: Approved does not necessarily mean published, it is a necessary stage
prior to publication. However approved documents are rendered as published documents,
with no draft indications.

`superseded`::: This document has been superseded.

`withdrawn`::: This document has been withdrawn.


`doctype`::
Document type. Definitions of the document type are found on
the https://standards.ieee.org/develop/drafting-standard/resources/[IEEE SA Style Manual].
+
Choices:
+
--
`standard`:: This document is a Standard (default)
`recommended-practice`:: This document is a Recommended Practice
`guide`:: This document is a Guide
`whitepaper`:: This document is a White Paper
`redline`:: This document is a Redline product document
`other`:: This document is of a type not otherwise described
--

`docsubtype`::
Document subtype. Choices:
+
--
`document`:: Document is new or a revision (default)
`amendment`:: Document is an amendment
`corrigendum`:: Document is an corrigendum
`erratum`:: Document is an erratum
`icap`:: Document is an ICAP (IEEE Conformity Assessment Program) document (applies only to `whitepaper`)
`industry-connections-report`:: Document is an Industry Connections Report document (applies only to `whitepaper`)
`industry-affiliate-network`:: Document is an Industry Affiliate Network document  [added in https://github.com/metanorma/metanorma-ieee/releases/tag/v1.5.3]
--

`trial-use`:: Document published for a limited period of time.
Can apply to any of the document types. (Default value: `false`.)
+
NOTE: A Trial-Use standard is only described in the text of the introduction,
it is not prominently displayed nor is it fielded data.
+
NOTE: Please see
https://standards.ieee.org/about/policies/opman/sect5/[Operations Manual, 5.7 Trial-Use standards]
for more details.

`issued-date`:: The date on which the document was approved. (Applicable to drafts.)
Like all dates in Metanorma, this must be supplied in `YYYY-MM-DD` format.
+
.Example for IEEE SA `issued-date`
[example]
====
[source,adoc]
----
:issued-date: 2021-06-16
----
====

`feedback-ended-date`:: (conditional: used only when `trial-use` is set to `true`.)
Specific to trial-use documents: the final date at which comments about the
document will be accepted.

`ieee-sasb-approved-date`:: Date that the document was approved specifically by the
IEEE SA Standards Board [added in https://github.com/metanorma/metanorma-ieee/releases/tag/v1.5.3].

`obsoleted-date`::

** When `trial-use` is set to `false`: the date on which the document will become `inactive`.
+
NOTE: See https://standards.ieee.org/about/policies/opman/sect6/[Operations Manual, 6.3.3 Inactive standards] for details.

** When `trial-use` is set to `true`: the date on which the document will expire.
+
NOTE: A trial-use document is effective for not more than three years
(https://standards.ieee.org/about/policies/opman/sect5/[Operations Manual, 5.7 Trial-Use standards]).


`:keywords`:: Comma-delimited list of keywords associated with the document.
+
.Example for IEEE SA `keywords` (IEEE Std 2830(TM)-2021)
[example]
====
[source,adoc]
----
:keywords: data fusion, IEEE 2830™, shared machine learning, SML, trusted execution environment, TEE
----
====

`:doctitle:`:: Document title.
+
NOTE: Do not include the words "{Draft/IEEE} (Trial-Use) {Guide/Standard/Recommended Practice} for",
these words are supplied automatically by Metanorma.
+
NOTE: The `:doctitle:` value can also be set using the first line of the
Metanorma AsciiDoc markup, prefaced by `= ` instead of setting the document
attribute.
+
.Example of default document titling
====
[source,adoc]
----
:doctitle: Spatial Web Protocol, Architecture and Governance
:docstage: approved
:doctype: recommended-practice
----

Document title: _Spatial Web Protocol, Architecture and Governance_
Full document title: _IEEE Recommended Practice for Spatial Web Protocol, Architecture and Governance_
Abbreviated document title: _IEEE Rec. Prac. for Spatial Web Protocol, Architecture and Governance_

====

`:title-full:`:: Full document title
By default, the words "(Draft/IEEE) (Trial-Use) {Guide/Standard/Recommended Practice} for" are prefixed
to the supplied title automatically by Metanorma, depending on document metadata, in the form of the title
used to render the document.
In order to override this, users can supply the complete title of the document with this document
attribute [added in https://github.com/metanorma/metanorma-ieee/releases/tag/v1.5.4].

`:title-abbrev:`:: Abbreviated document title
The full title of the document is abbreviated by Metanorma, for use in Word output headers,
by constructing the full title depending on document metadata, but using a standard abbreviation
for the document type.  In order to override this, users can supply the abbreviated title of the document with this document
attribute [added in https://github.com/metanorma/metanorma-ieee/releases/tag/v1.5.4].
+
.Example of user-supplied document titling
====
[source,adoc]
----
:doctitle: Spatial Web Protocol, Architecture and Governance
:docstage: approved
:doctype: recommended-practice
:title-full: IEEE Recommended Practice for Spatial Web Protocol
:title-abbrev: IEEE Rec. Prac. for SWF
----

Document title: _Spatial Web Protocol, Architecture and Governance_
Full document title: _IEEE Recommended Practice for Spatial Web Protocol_
Abbreviated document title: _IEEE Rec. Prac. for SWF_

====


`:document-scheme`:: The document scheme that this document aligns to.
Metanorma will enforce alignment as appropriate, including by supplying
predefined sections.
+
Accepted values:
+
`ieee-sa-2021`::: (default)

**** A "Word usage" subclause will be supplied at the end of the "Overview"
clause with contents defined in the IEEE SA Style Manual 2021.

**** The "Participants" clause will be automatically generated according to IEEE
SA requirements using the information supplied by the user-defined "Participant"
clauses.

`legacy`::: (all unsupported values fall back to `legacy`)
Metanorma will not supply the "Word usage" subclause and will not
generate or modify the "Participants" clause.

`:program:`:: Program under which a white paper was authored [added in https://github.com/metanorma/metanorma-ieee/releases/tag/v1.1.6].

== Document relationships

`:merges:`:: This document incorporates the document(s) with the nominated
identifiers (semicolon-delimited). In IEEE identifiers, indicated as _incorporated_.

`:updates:`:: This document is an update of the document(s) with the nominated
identifiers (semicolon-delimited). Applies to revisions, as well as to appendices
and corrigenda.

`:supplements:`:: This document is a supplement of the document with the nominated
identifier [added in https://github.com/metanorma/isodoc/releases/tag/v1.0.12].


[[document-contributors]]
== Document contributors

=== General

There are multiple types of contributors to an IEEE SA document, and the
document displays full provenance of where the document was developed, balloted
and eventually approved.

The basic information of these groups are entered as document attributes,
including:

* the working group
* the balloting group
* the standards board, at the time of publishing the document.

Members of these groups are entered in the
link:/author/ieee/topics/markup#participants[Participants clause].


=== Society

An IEEE SA document is sponsored by or developed by an IEEE society.
This IEEE society is prominently displayed on the cover page.

NOTE: This is mandatory information.

`society`:: The IEEE society responsible for the document. Do not include the
"IEEE" prefix.
+
.Example for IEEE SA `society`
[example]
====
[source,adoc]
----
:society: Computer Society
----
====

=== Committee

An IEEE SA document is developed within a working group under an IEEE SA
committee.
This IEEE SA committee is prominently displayed on the cover page.

NOTE: This is mandatory information.

`committee`:: The committee responsible for the document.
+
.Example for IEEE SA `committee`
[example]
====
[source,adoc]
----
:committee: C/AISC - Artificial Intelligence Standards Committee
----
====
+
[example]
====
[source,adoc]
----
:committee: Standards Activities Board
----
====


=== Working group

An IEEE SA document is developed by a working group.

NOTE: This is mandatory information.

An IEEE SA working group can be one of two modes
(more details at link:/author/ieee/authoring-guide/process[process]):

* Entity-based: members are IEEE SA member organizations
* Individual-based: members are individual contributors

`working-group`:: The working group responsible for the document.
Include any final "Working Group" text in the group name.
+
.Example for IEEE SA `working-group`
[example]
====
[source,adoc]
----
:working-group: Spatial Web Working Group
----
====

(Rendered as: _the Spatial Web Working Group had the following membership:..._)

Members of the working group are to be listed in the
link:/author/ieee/topics/markup#participants[Participants clause].


=== Balloting group

The balloting group, or balloting committee, is the group that recommends
the document for approval as a standard by the IEEE SA Standardization board.

The balloting group is composed of voting members of the working group, or the
committee that the working group belongs to.

`balloting-group`:: The Standards Association balloting group responsible for the document.
Do not supply the final "Standards Association balloting group" text in the group name;
that is supplied by Metanorma.

`balloting-group-type`:: The type of the Standards Association balloting group responsible for the document,
_individual_ or _entity_ (default: _individual_).

Members of the balloting group are to be listed in the
link:/author/ieee/topics/markup#participants[Participants clause].


=== Standardization board

The IEEE Standardization Board at the time of document publication is rendered
in the document preface.

Members of the IEEE SA Standardization Board (SASB) are to be listed in the
link:/author/ieee/topics/markup#participants[Participants clause].

=== Personal authors

White papers require personal authors to be specified, as follows:

`:surname:`, `:surname_2:`, `:surname_{i}:`::
Surname of personal authors

`:givenname:`, `:givenname_2:`, `:givenname_{i}:`::
Given name of personal authors

`:contributor-position:`, `:contributor-position_2:`, `:contributor-position_{i}:`::
Job title of personal authors



=== Sponsors

The sponsoring bodies, if any, are indicated through the `:sponsor:` and
`:sponsor-subdivision:` attributes.

As with other author values, multiple instances of sponsoring organisations and
their subdivisions are indicated as `:sponsor_2:` and `:sponsor-subdivision_2:`,
`:sponsor_3:` and `:sponsor-subdivision_3:`, etc.

The values of `:sponsor-subdivision_{i}:` can be:

* multiple (semicolon-delimited: processed via CSV, recognising quote marks)
* hierarchical, with multiple levels of subdivision (comma-delimited, from larger to
  smaller) [added in https://github.com/metanorma/metanorma-standoc/releases/tag/v2.8.3];

The different hierarchical levels can optionally be prefixed with type and a colon.

On the front cover, if it is a sponsor, "IEEE" is prefixed to the first
subdivision, rather than being rendered on a separate line.

The following is an example of how two divisions of the IEEE are indicated as sponsoring the document:

.IEEE subdivsion sponsors to a document
====
[source,adoc]
----
:sponsor: IEEE
:sponsor-subdivision: "Power & Energy Society", Power System Communications Committee; Communications Society, Standards Committee
----

rendered as:

____
Sponsored by the +
*Power System Communications Committee* +
of the +
*IEEE Power & Energy Society* +
and the +
*Standards Committee* +
of the +
*IEEE Communications Society*
____
====

NOTE: The quotation marks are needed to process the CSV correctly.

=== Corporate authors

In Industry Affiliate Network documents, an affiliate needs to be nominated, along with its logo.
These are indicated through the `:corporate-author:` attribute, which overrides the default of IEEE
to indicate which organisations have been involved 
in authoring the document [added in https://github.com/metanorma/metanorma-ieee/releases/tag/v1.5.3].
The affiliate should be given as the second `:corporate-author:` instance, after IEEE. 
The `:corporate-author_logo:` attribute should match the `:corporate-author:` attribute:

[source,adoc]
----
:corporate-author: IEEE
:corporate-author_2: Spatial Web Foundation
:corporate-author_logo_2: swf.png
----


== Visual appearance

`:hierarchical-object-numbering:`::
If set, do not number tables and figures consecutively throughout the body of the
document, but restart numbering with each clause (hierarchically).
+
Use in complex documents, with multiple tables or figures, that need to be tracked against
clauses for ease of lookup (so _Figure 6-3, Figure 6-4_, instead of _Figure 21, Figure 22_.)

`:presentation-metadata-coverpage-statement:`:: In Industry Affiliate Network documents,
used to give the coverpage statement of the affiliate organisation's 
contribution [added in https://github.com/metanorma/metanorma-ieee/releases/tag/v1.5.3].

`:presentation-metadata-page-break-between-sections:`::
If set to `true`, page breaks will be added between the document sections in the PDF.


== Document processing

`:ieee-dtd:`::
The location of the IEEE XML DTD [added in https://github.com/metanorma/isodoc/releases/tag/v0.1.0].
Used to validate any IEEE XML generated for the document.

