---
layout: ieee-flavor
---

= Metanorma IEEE SA document attributes

[[note_general_doc_ref_doc_attrib_ieee]]
[NOTE]
====
Document attributes listed below are unique to the processing of IEEE SA documents
in Metanorma.

For _common document attributes_, see link:/author/ref/document-attributes/[Document attributes reference] in general Metanorma author's documentation. That page describes attributes that apply to all Metanorma flavors, not just IEEE SA.

For an _introduction to Metanorma AsciiDoc document attributes_ and how Metanorma uses them, see link:/author/topics/document-format/meta-attributes/[the corresponding topic].
====

== Document information

`docnumber`:: In IEEE SA terms: the designation number for the document. Do not include the initial "P".
+
.Example for IEEE SA `docnumber`
[example]
====
[source,adoc]
----
:docnumber: 2830
----
====

`draft`:: The draft number. Use together with `:docstage: draft`. Do not include the initial "D".
+
.Example for IEEE SA `docstage`
[example]
====
[source,adoc]
----
:docstage: draft
:draft: 2
----
====

`edition`:: The edition number of the document. In case that a document is a
draft, the edition number indicates the intended edition number.
+
.Example for IEEE SA `edition`
[example]
====
[source,adoc]
----
:edition: 1
----
====

`amendment-number`:: (only when `docsubtype` is set to `amendment`) The number of the amendment.

`corrigendum-number`:: (only when `docsubtype` is set to `corrigendum`) The number of the corrigendum.

`isbn-pdf`:: The ISBN of the PDF document in ISBN-13 format.
+
.Example for IEEE SA `isbn-pdf`
[example]
====
[source,adoc]
----
:isbn-pdf: 978-1-5044-7724-6
----
====

`isbn-print`:: The ISBN of the print document in ISBN-13 format.
+
.Example for IEEE SA `isbn-print`
[example]
====
[source,adoc]
----
:isbn-print: 978-1-5044-7725-3
----
====

`stdid-pdf`:: The final standard identifier of the PDF document.
+
.Example for IEEE SA `stdid-pdf`
[example]
====
[source,adoc]
----
:stdid-pdf: STD24807
----
====

`stdid-print`:: The final standard identifier of the print document.
+
.Example for IEEE SA `stdid-print`
[example]
====
[source,adoc]
----
:stdid-print: STDPD24807
----
====

`doctype`::
Document type. Definitions of the document type are found on
the https://standards.ieee.org/develop/drafting-standard/resources/[IEEE SA Style Manual].
+
Choices:
+
--
`standard`:: This document is a Standard (default)
`recommended-practice`:: This document is a Recommended Practice
`guide`:: This document is a Guide
--

`docsubtype`::
Document subtype. Choices:
+
--
`document`:: Document is new or a revision (default)
`amendment`:: Document is an amendment
`corrigendum`:: Document is an corrigendum
`erratum`:: Document is an erratum
--

`trial-use`:: Document published for a limited period of time.
Can apply to any of the document types. (Default value: `false`.)
+
NOTE: A Trial-Use standard is only described in the text of the introduction,
it is not prominently displayed nor is it fielded data.
+
NOTE: Please see
https://standards.ieee.org/about/policies/opman/sect5/[Operations Manual, 5.7 Trial-Use standards]
for more details.

`docstatus`:: Status of document.
+
--
Allowed values are:

`developing`:: Document is under development.
`active`:: Document is active.
`inactive`:: Document is inactive.
+
NOTE: See https://standards.ieee.org/about/policies/opman/sect6/[Operations Manual, 6.3.3 Inactive standards] for details.

If not supplied, the value is `developing` if `draft` is supplied, else `active`.
--

`issued-date`:: The date on which the document was approved.
Like all dates in Metanorma, this must be supplied in `YYYY-MM-DD` format.
+
.Example for IEEE SA `issued-date`
[example]
====
[source,adoc]
----
:issued-date: 2021-06-16
----
====

`issued-date`:: The date on which the document draft was circulated.

`feedback-ended-date`:: (conditional). Only when `trial-use` is set to `true`.
Specific to trial-use documents: the final date at which comments about the
document will be accepted.

`obsoleted-date`::

*** When `trial-use` is set to `false`: the date on which the document will become `inactive`

*** When `trial-use` is set to `true`: the date on which the document will expire.
+
NOTE: A trial-use document is effective for not more than three years
(https://standards.ieee.org/about/policies/opman/sect5/[Operations Manual, 5.7 Trial-Use standards]).


`:keywords`:: Comma-delimited list of keywords associated with the document.
+
.Example for IEEE SA `keywords` (IEEE Std 2830(TM)-2021)
[example]
====
[source,adoc]
----
:keywords: data fusion, IEEE 2830™, shared machine learning, SML, trusted execution environment, TEE
----
====

`:doctitle:`:: Document title.
+
Do not include the words "Draft {Guide/Standard/Recommended Practice} for",
these words are supplied automatically by Metanorma.
+
NOTE: `:doctitle:` can be set using the first line of the
AsciiDoc markup, prefaced by `= ` instead of setting the document attribute.

`:document-scheme`:: The document scheme that this document aligns to: Metanorma will enforce alignment
as appropriate, including by supplying predefined sections. The default document scheme for Metanorma-IEEE
is "ieee-sa-2021"; unless a different document-scheme is nominated, Metanorma will supply a Word Usage
section at the end of the Overview, will supply the built-in boilerplate as defined in 2021, and
will overwrite the Participants clause in the built-in boilerplate with user-defined Participant clauses.
In order to prevent that behaviour in legacy documents, any other value can be nominated for the document attribute,
such as "legacy".

== Document relationships

`:merges:`:: This document incorporates the document(s) with the nominated
identifiers (semicolon-delimited).

`:updates:`:: This document is an update of the document(s) with the nominated
identifiers (semicolon-delimited).


[[document-contributors]]
== Document contributors

=== General

There are multiple types of contributors to an IEEE SA document, and the
document displays full provenance of where the document was developed, balloted
and eventually approved.

The basic information of these groups are entered as document attributes,
including:

* the working group
* the balloting group
* the standards board, at the time of publishing the document.

Members of these groups are entered in the
link:author/ieee/topics/markup#participants[Participants clause].


=== Society

An IEEE SA document is sponsored by or developed by an IEEE society.
This IEEE society is prominently displayed on the cover page.

NOTE: This is mandatory information.

`society`:: The IEEE society responsible for the document. Do not include the
"IEEE" prefix.
+
.Example for IEEE SA `society`
[example]
====
[source,adoc]
----
:society: Computer Society
----
====

=== Committee

An IEEE SA document is developed within a working group under an IEEE SA
committee.
This IEEE SA committee is prominently displayed on the cover page.

NOTE: This is mandatory information.

`committee`:: The committee responsible for the document.
+
.Example for IEEE SA `committee`
[example]
====
[source,adoc]
----
:committee: C/AISC - Artificial Intelligence Standards Committee
----
====
+
[example]
====
[source,adoc]
----
:committee: Standards Activities Board
----
====


=== Working group

An IEEE SA document is developed by a working group.

NOTE: This is mandatory information.

An IEEE SA working group can be one of two modes
(more details at link:/author/ieee/ref/process[process]):

* Entity-based: members are IEEE SA member organizations
* Individual-based: members are individual contributors

`working-group`:: The working group responsible for the document.
+
.Example for IEEE SA `working-group`
[example]
====
[source,adoc]
----
:working-group: Spatial Web Working Group
----
====

Members of the working group are to be listed in the
link:author/ieee/topics/markup#participants[Participants clause].


=== Balloting group

The balloting group, or balloting committee, is the group that recommends
the document for approval as a standard by the IEEE SA Standardization board.

The balloting group is composed of voting members of the working group, or the
committee that the working group belongs to.

`balloting-group`:: The Standards Association balloting group responsible for the document.
`balloting-group-type`:: The type of the Standards Association balloting group responsible for the document,
_individual_ or _entity_ (default: _individual_).

Members of the balloting group are to be listed in the
link:author/ieee/topics/markup#participants[Participants clause].


=== Standardization board

The IEEE Standardization Board at the time of document publication is rendered
in the document preface.

Members of the IEEE SA Standardization Board (SASB) are to be listed in the
link:author/ieee/topics/markup#participants[Participants clause].


== Visual appearance

`:hierarchical-object-numbering:`::
If set, do not number tables and figures consecutively throughout the body of the
document, but restart numbering with each clause (hierarchically). +
+
Use in complex documents, with multiple tables or figures, that need to be tracked against
clauses for ease of lookup (so _Figure 6-3, Figure 6-4_, instead of _Figure 21, Figure 22_.)

