---
layout: ieee-flavor
---

= Metanorma IEEE document attributes

[[note_general_doc_ref_doc_attrib_ieee]]
[NOTE]
====
Document attributes listed below are unique to the processing of ITU documents in Metanorma.

For _common document attributes_, see link:/author/ref/document-attributes/[Document attributes reference] in general Metanorma author’s documentation. That page describes attributes that apply to all Metanorma flavors, not just ITU.

For an _introduction to Metanorma AsciiDoc document attributes_ and how Metanorma uses them, see link:/author/topics/document-format/meta-attributes/[the corresponding topic].
====

== Document information

`docnumber`:: In IEEE terms: the designation number for the document. Do not include the initial "P".

`draft`:: The draft number. Do not include the initial "D".
`edition`:: The revision number of the document.

`isbn-pdf`:: The ISBN of the PDF document.
`isbn-print`:: The ISBN of the print document.

`stdid-pdf`:: The final standard identifier of the PDF document.
`stdid-print`:: The final standard identifier of the print document.

`doctype`::
Document type. Choices:
+
--
* `standard` (default): This document is a Standard
* `recommended-practice`: This document is a Recommended Practice
* `guide`: This document is a Guide
--

`docsubtype`::
Document subtype. Choices:
+
--
* `document`:: Document is new or a revision (default)
* `amendment`:: Document is an amendment
* `corrigendum`:: Document is an corrigendum
* `erratum`:: Document is an erratum
--

`trial-use`:: Document published for a limited period of time. Can apply to any of the document types. (Default value: `false`.)

`docstatus`:: Status of document. Legal values are `developing`, `active`, and `inactive`. If not supplied, the value is `developing` if `draft` is supplied, else `active`.

`confirmed-date`:: The date on which the document was approved. Like all dates in Metanorma, this must be supplied in YYYY-MM-DD format.
`issued-date`:: The date on which the document draft was circulated.
`feedback-ended-date`:: Specific to trial-use documents: the final date at which comments about the document will be accepted.
`obsoleted-date`:: The date on which the document was made no longer valid (inactive), or else will become no longer valid (trial-use).

`:keywords`:: Comma-delimited list of keywords associated with the document.

`:doctitle:`:: Document title (also can be given as the first line of the Asciidoctor markup, prefaced by `= `.
Do not include the words "Draft (Guide/Stadnard/Recommended Practice) for", they are supplied automatically
by Metanorma.

`:merges:`:: This document incorporates the document(s) with the nominated identifiers (semicolon-delimited).
`:updates:`:: This document is an update of the document(s) with the nominated identifiers (semicolon-delimited).

== Document participants

`society`:: The IEEE society responsible for the document. Do not include the "IEEE" prefix.
`committee`:: The standards committee, standards coordinating committee, standards subcommittee, or technical committee responsible for the document.
`working-group`:: The working group responsible for the document.
`balloting-group`:: The Standards Association balloting group responsible for the document.

IEEE requires listing the full membership of the working group, balloting group, and
the IEEE Standards Board responsible for the document. The current membership of the balloting group and
standards board is normally provided by IEEE during editing; if the information is not provided in
the document, dummy values will be provided to match those in the IEEE templates.
This information is provided as follows; all names are given inline as full names.

`wg-chair`:: The working group chair
`wg-vicechair`:: The working group vice-chair
`wg-secretary`:: The working group secretary
`wg-members`:: The individual working group members, semicolon-delimited
`wg-org-members`:: The organisations that are working group members, semicolon-delimited

`balloting-group-members`:: The balloting group members, semicolon-delimited

`std-board-chair`:: The Standards Board chair
`std-board-vicechair`:: The Standards Board vice-chair
`std-board-pastchair`:: The Standards Board past chair
`std-board-secretary`:: The Standards Board secretary
`std-board-members`:: The Standards Board members, semicolon-delimited. Any emeritus members should be given with an asterisk at the end of their names

== Visual appearance

`:hierarchical-object-numbering:`::
If set, do not number tables and figures consecutively throughout the body of the
document, but restart numbering with each clause (hierarchically) +
+
Use in complex documents, with multiple tables or figures, that need to be tracked against
clauses for ease of lookup (so _Figure 6-3, Figure 6-4_, instead of _Figure 21, Figure 22_.)

