---
layout: ogc-flavor
---

= Recommendations, requirements, and permissions

In this clause we will use the term "`requirement`" to refer to the generic
class of "`recommendations`", "`requirements`" and "`permissions`".

NOTE: This subsection supplements
link:/author/topics/document-format/requirements[Requirement, Recommendation, and Permission blocks]
in general Metanorma documentation.

In some instances, the naming of terms that Metanorma uses in general is used in
Metanorma markup instead of the nomenclature used in the
https://www.ogc.org/standards/modularspec[OGC Modular Specification]:

* In particular, Metanorma refers to what the requirement is about as the _subject_.

* The different types of requirement expressed by Metanorma-OGC are about
different things, and the more abstract types of requirement are about other
requirements.

* Metanorma uses _subject_ rather than the more specific language of the Modular
Specification, to ensure that requirements are represented consistently within
Metanorma.

== Basic encoding of Requirements

NOTE: In order to match the Metanorma encoding of requirements to existing OGC
AsciiDoc markup of requirements, users can refer to the rendering of Metanorma
requirements which is aligned the existing, tabular OGC encoding of
requirements.

An OGC requirement is marked up using the Metanorma conventions, of tagged
example blocks containing other tagged example blocks and open blocks. (We give
illustrations below.)

An OGC requirement is rendered as a table, as is consistent with current
practice.

* The CSS class of the requirement table, for HTML rendering, is the `type`
attribute of the requirement.
+
--
The only types recognised are:

** `verification`,
** `abstracttest`,
** `class`,
** `conformanceclass`

If no type attribute is given, this is considered to be a simple requirement.
The default CSS class currently assigned for HTML rendering is `recommend`.
In the rest of this section, we look at simple requirements.
--

* The heading of the table (spanning two columns) is its name (the AsciiDoc role
or style of the requirement, e.g. `[.permission] or [permission]`), optionally
followed by its title (the caption of the requirement, e.g. `.Title`).

* The title of the table (spanning two columns) is its `label` attribute.

* The initial rows of the body of the table give metadata about the requirement.
They include:

** The `obligation` attribute of the requirement, if given: _Obligation_
followed by the attribute value

** The `subject` attribute of the requirement, if given: _Subject_, followed by the attribute.
(In other classes of requirement, the `subject` attribute of the requirement
is rendered differently; see below.) The subject attribute can be marked up as a cross-reference
to another requirent given in the same document. If there are multiple values of the subject,
they are semicolon delimited [added in https://github.com/metanorma/metanorma-standoc/releases/tag/v1.10.4].

** The `inherit` attribute of the requirement, if given: _Dependency_ followed
by the attribute value. If there are multiple values of the subject,
they are semicolon delimited.

** The `component` components of the
requirement [added in https://github.com/metanorma/metanorma-ogc/releases/tag/v1.4.0],
which capture internal components of the requirement.
+
These are divided into two categories:

*** Components with a `class` attribute other than `part` are
extracted in order, with the class name normalised (title case), followed by the component contents.
So a component with a `class` attribute of `conditions` will be rendered as
as _Conditions_ followed by the component contents.

*** Components with the `class` attribute `part` are extracted and presented in
order: each Part is rendered as an incrementing capital letter (_A_, _B_, _C_
and so on), followed by the component contents. Any cross-references to part components
will automatically be labelled with the label of their parent requirement, followed by their ordinal
letter.

** The `classification` attributes of the requirement, if given: the
classification tag (in capitals), followed by the classification value.
The `classification` attribute is marked up as in the rest of Metanorma:
`classification="key1=value1;key2=value2..."`, where _value_ is either a single
string, or a comma-delimited list of values.

* The remaining rows of the requirement are the remaining components of the
requirement, encoded as table rows instead of as a definition table (as they are
by default in Metanorma).

** Components can include descriptive text.

** Components can include open blocks marked with role attributes. That includes the
legacy Metanorma components:
*** `[.specification]`
*** `[.measurement-target]`
*** `[.verification]`
*** `[.import]`


So the following simple recommendation:

[source,asciidoc]
----
=== Clause Four Point Five
[[a1]]
[recommendation,label=/ogc/recommendation/wfs/2,obligation=permission,subject=user,inherit=/ss/584/2015/level/1,classification="control-class:Technical;priority:P0"]
.Widgets
====
[.component,class=conditions]
--
. Candidate test subject is a witch
. Widget has been suitably calibrated for aerodynamics
--

[.component,class=part]
--
Determine travel distance by flight path
--

[[a2]]
[.component,class=part]
--
Independently verify flight path
--

Widgets are tested for aerodynamic flight potential in partnership with witches.
Consult local coven for more information.
====

== Clause Five
See <<a1>>, in particular <<a2>>.
----


will render as follows:

____
*4.5 Clause Four Point Five*

[cols="1,3"]
|===
2+a|Recommendation 1 +
Widgets

|Subject  |user
|Dependency   |/ss/584/2015/level/1A
|Conditions
a| . Candidate test subject is a witch
. Widget has been suitably calibrated for aerodynamics

|A | Determine travel distance by flight path
|B | Independently verify flight path
|Control-class |Technical
|Priority |P0
2+|Widgets are tested for aerodynamic flight potential in partnership with witches.
Consult local coven for more information.
|===

*5. Clause Five*

See Clause 4.5, Recommendation 1, in particular Clause 4.5, Recommendation 1 B.
____

As in the rest of Metanorma, attributes can also be expressed as a `[%metadata]`
definition list within the requirement:

[source,asciidoc]
.An exhaustive attribute example
-----
[requirement]
====
[%metadata]
model:: ogc
type:: class
label:: http://www.opengis.net/spec/waterml/2.0/req/xsd-xml-rules[*req/core*]
subject:: Encoding of logical models
inherit:: urn:iso:dis:iso:19156:clause:7.2.2
inherit:: urn:iso:dis:iso:19156:clause:8
inherit:: http://www.opengis.net/doc/IS/GML/3.2/clause/2.4
inherit:: O&M Abstract model, OGC 10-004r3, clause D.3.4
inherit:: http://www.opengis.net/spec/SWE/2.0/req/core/core-concepts-used
inherit:: <<ref2>>
inherit:: <<ref3>>
classification:: priority:P0
classification:: domain:Hydrology,Groundwater
classification:: control-class:Technical
obligation:: recommendation,requirement

Logical models encoded as XSDs should be faithful to the original UML conceptual
models.
====
-----


== OGC Classes of Requirement

=== General

To simplify the Modular Specification (Annex C),

* A Conformance Class consists of multiple Conformance Tests, associated to and
only to the requirements in a corresponding Requirements Class.

** A Conformance Class is thus about a single Requirement Class

* A Requirement Class consists of multiple Requirements, all about the same
standardization target type

* A Conformance Test checks if a set of Requirements is met by a single
standardization target (an entity)

** A Conformance Test is thus in a many-to-many relation with Requirements

** A Conformance Test is about a single standardization target

** Conformance Tests include Abstract Tests

* A Requirement is a condition to be satisfied by a single standardization
target type

These relations are captured in the structure below.

=== Requirement classes

A requirement with `type=class` is cross-referenced and captioned as a
"`{Requirement} Class`", and is rendered differently to the actual requirement
itself
[added in https://github.com/metanorma/metanorma-ogc/releases/tag/v0.2.11].

NOTE: Classes for Recommendations will be captioned as
Recommendation Classes, similarly for Requirement Classes and
Permission Classes.

Requirement Classes must use the following Metanorma Requirement attributes:

* Target Type. Specified in the `subject` attribute, and rendered as _Target
Type_.

* Name. Specified as the requirement's title.

* Dependencies (optional). Specified with the `inherit` attribute (which can
take multiple semicolon-delimited values).

* Nesting (optional). Requirements contained in a class are marked up as nested
requirements.

For example:

[source,asciidoc]
--
[requirement,type="class",label="http://www.opengis.net/spec/waterml/2.0/req/xsd-xml-rules[*req/core*]",obligation="requirement",subject="Encoding of logical models",inherit="urn:iso:dis:iso:19156:clause:7.2.2;urn:iso:dis:iso:19156:clause:8;http://www.opengis.net/doc/IS/GML/3.2/clause/2.4;O&M Abstract model, OGC 10-004r3, clause D.3.4;http://www.opengis.net/spec/SWE/2.0/req/core/core-concepts-used"]
.GWML2 core logical model
====

[requirement,type="general",label="/req/core/encoding"]
======
======

[requirement,type="general",label="/req/core/quantities-uom"]
======
======

[recommendation,type="general",label="/req/core/codelist"]
======
======

[requirement,type="general",label="/req/core/codelistURI"]
======
======

[requirement,type="general",label="/req/core/identifier"]
======
======

[requirement,type="general",label="/req/core/feature"]
======
======

====
--

renders as:

____

[cols="1,3"]
|===
2+a|Requirement Class 1 +
GWML2 core logical model

2+a|http://www.opengis.net/spec/waterml/2.0/req/xsd-xml-rules[*req/core*]
|Obligation   |Requirement
|Target Type  |Encoding of logical models
|Dependency   |urn:iso:dis:iso:19156:clause:7.2.2
|Dependency   |urn:iso:dis:iso:19156:clause:8
|Dependency   |http://www.opengis.net/doc/IS/GML/3.2/clause/2.4
|Dependency   |O&M Abstract model, OGC 10-004r3, clause D.3.4
|Dependency   |http://www.opengis.net/spec/SWE/2.0/req/core/core-concepts-used
|Requirement  |/req/core/encoding
|Requirement  |/req/core/quantities-uom
|Requirement  |/req/core/codelist
|Requirement  |/req/core/codelistURI
|Requirement  |/req/core/identifier
|Requirement  |/req/core/identifier
|===
____


Embedded requirements (such as are found within Requirement Classes) will automatically
insert cross-references to the non-embedded requirements with the same
label [added in https://github.com/metanorma/metanorma-ogc/releases/tag/v1.0.8]:

[source,asciidoc]
--
[requirement,type="class",label="/req/conceptual"]
.GWML2 core logical model
====

[requirement,type="general",label="/req/core/encoding"]
======
======

====

[requirement,type="general",label="/req/core/encoding"]
====
Encoding requirement
====
--

renders as:

____
|===
*Requirement Class 3: GWML2 core logical model* +
/req/conceptual

| Requirement 1:   | /req/core/encoding
|===

|===
*Requirement 1:*
/req/core/encoding

Encoding requirement
|====
____

=== Conformance classes

A requirement with `type=conformanceclass` is cross-referenced and captioned as
a "Conformance Class", and is otherwise rendered identically to a
Requirement Class [added in https://github.com/metanorma/metanorma-ogc/releases/tag/v1.0.4].

Conformance Classes must use the following Metanorma Requirement attributes:

* Associated requirement class. Specified with the `subject` attribute, which may be encoded as a cross-reference.
Rendered as _Requirement Class_.
* Name. Specified as the requirement's title.
* Dependencies (optional). Specified with the `inherit` attribute (which can take multiple semicolon-delimited values).
* Nesting (optional). Conformance tests contained in a conformance class are marked up as nested requirements.
* According to the Modular Specification, Conformance classes do not have a Target Type. If one must be encoded,
it should be encoded as a Classification key-value pair.

For example:

[source,asciidoc]
----
[requirement,type="conformanceclass",label="http://www.opengis.net/spec/ogcapi-features-2/1.0/conf/crs",subject="<<rc_crs,Requirements Class 'Coordinate Reference Systems by Reference'>>",inherit="http://www.opengis.net/doc/IS/ogcapi-features-1/1.0#ats_core",classification="Target Type:Web API"]
====
====
----

renders as:

____

[cols="1,3"]
|===
2+a|Conformance Class 1

2+a|http://www.opengis.net/spec/ogcapi-features-2/1.0/conf/crs
|Requirements Class  |_Requirements Class 'Coordinate Reference Systems by Reference_
|Dependency   |http://www.opengis.net/doc/IS/ogcapi-features-1/1.0#ats_core
|Target Type   |Web API
|===
____


===  Conformance Tests

A requirement with `type=verification` is a Conformance Test, and
is cross-referenced and captioned as
a "`{Requirement} Test`". It is rendered differently from the
actual requirement itself.

NOTE: Verifications for Recommendations will be captioned as
Recommendation Tests, similarly for Requirement Tests and
Permission Tests.

Conformance Tests must use the following Metanorma Requirement attributes and components:

* Associated requirement. Specified with the `subject` attribute, which may be encoded as a cross-reference.
Rendered as _Requirement_. Multiple semicolon-delimited values may be provided.
* Name. Specified as the requirement's title.
* Dependencies (optional). Specified with the `inherit` attribute (which can take multiple semicolon-delimited values).
* The `component` components of the requirement [added in https://github.com/metanorma/metanorma-ogc/releases/tag/v1.4.0].
** Components with the `class` attribute `test-purpose`, `test-method`, or `reference` are extracted and presented as _Test
Purpose_, _Test Method_, and _Reference_, followed by the component contents.
No other components are foreseen by the Modular Specification.
* The test type of the Conformance Test, is encoded as a Classification key-value pair.

Conformance Tests are excluded from the
"`Table of Requirements`" in Word output
[added in https://github.com/metanorma/metanorma-ogc/releases/tag/v0.2.10].

A requirement with `type=abstracttest` is cross-referenced and captioned as
an "Abstract Test", and is otherwise rendered identically to a
Conformance Test [added in https://github.com/metanorma/metanorma-ogc/releases/tag/v1.0.4].

For example:

[source,asciidoc]
----
[requirement,type="abstracttest",label="/conf/crs/crs-uri",subject="<<req_crs_crs-uri,/req/crs/crs-uri>>,<<req_crs_fc-md-crs-list_A,/req/crs/fc-md-crs-list A>>,<<req_crs_fc-md-storageCrs,/req/crs/fc-md-storageCrs>>,<<req_crs_fc-md-crs-list-global,/req/crs/fc-md-crs-list-global>>",classification="Test Type:Basic"]
====

[.component,class=test-purpose]
--
Verify that each CRS identifier is a valid value
--

[.component,class=test-method]
--
For each string value in a `crs` or `storageCrs` property in the collections and collection objects,
validate that the string conforms to the generic URI syntax as specified by
https://tools.ietf.org/html/rfc3986#section-3[RFC 3986, section 3].

. For http-URIs (starting with `http:`) validate that the string conforms to the syntax specified by RFC 7230, section 2.7.1.

. For https-URIs (starting with `https:`) validate that the string conforms to the syntax specified by RFC 7230, section 2.7.2.
--

[.component,class=reference]
--
<<ogc_07_147r2,clause=15.2.2>>
--

====
----

renders as:

____

[cols="1,3"]
|===
2+a|Abstract Test 1

2+a|/conf/crs/crs-uri
|Requirement  |_/req/crs/crs-uri, /req/crs/fc-md-crs-list A, /req/crs/fc-md-storageCrs, /req/crs/fc-md-crs-list-global_
|Test Purpose   |Verify that each CRS identifier is a valid value
|Test Method   a|For each string value in a `crs` or `storageCrs` property in the collections and collection objects,
validate that the string conforms to the generic URI syntax as specified by
https://tools.ietf.org/html/rfc3986#section-3[RFC 3986, section 3].
+
. For http-URIs (starting with `http:`) validate that the string conforms to the syntax specified by RFC 7230, section 2.7.1.
. For https-URIs (starting with `https:`) validate that the string conforms to the syntax specified by RFC 7230, section 2.7.2.

|Reference | OGC-07-147r2: cl. 15.2.2
|Test Type | Basic
|===
____


== Legacy Metanorma AsciiDoc syntax

For legacy reasons, a second Metanorma AsciiDoc syntax is permitted for
recommendations, requirements and permissions.

In this syntax, Metanorma AsciiDoc tables are used to express the
data needed for requirements:

* Type of requirement. Specified in the first table cell,
  one of `Recommendation`, `Requirement` or `Permission`.
  Optionally followed by a number
  (which is ignored in parsing; the elements are renumbered
  automatically in rendering.)
* Internal label. First paragraph of the second table cell.
* Body of requirement. Second and subsequent paragraphs of the second table cell.

[example]
====
[source,asciidoc]
----
[[recommendation1]]
|===
|Recommendation |/ogc/recommendation/wfs/2 +

If the API definition document uses the OpenAPI Specification 3.0,
the document SHOULD conform to the
<<rc_oas30,OpenAPI Specification 3.0 requirements class>>.
|===
----
====

