---
title: Metanorma-CC library documentation
description: >-
  Library documentation for Metanorma-CC, the Metanorma flavor for CalConnect standards.
  Synced from the upstream gem README at github.com/metanorma/metanorma-cc.
source_url: https://github.com/metanorma/metanorma-cc/blob/main/README.adoc
is_library_doc: true
layout: page
---


== Functionality

This gem processes https://www.metanorma.com/[Metanorma documents] following
the Metanorma model for generating CalConnect Standards.

The gem currently inherits from the https://github.com/metanorma/metanorma-standoc
gem, and aligns closely to it. Refer to https://metanorma.com[] for guidance.

== Usage

The preferred way to invoke this gem is via the `metanorma` script:

[source,console]
----
$ metanorma --type cc a.adoc                   # output HTML and PDF
$ metanorma --type cc --extensions html a.adoc # output just HTML
$ metanorma --type cc --extensions pdf a.adoc  # output just PDF
$ metanorma --type cc --extensions xml a.adoc  # output Metanorma XML
----

The gem translates the document into Metanorma XML format, and then
validates its output against the CC Metanorma XML document model; errors are
reported to console against the XML, and are intended for users to
check that they have provided all necessary components of the
document.

The gem then converts the XML into output formats such as HTML and PDF.

=== Installation

If you are using a Mac, the https://github.com/metanorma/metanorma-macos-setup
repository has instructions on setting up your machine to run Metanorma
scripts such as this one. You need only run the following in a Terminal console:

[source,console]
----
$ bash <(curl -s https://raw.githubusercontent.com/metanorma/metanorma-macos-setup/master/metanorma-setup)
$ gem install metanorma-cc
----

== Documentation

See https://www.metanorma.com/author/cc/[Author CalConnect documents with Metanorma CC].

== Examples

* Example documents are available at the https://github.com/metanorma/mn-samples-cc[mn-samples-cc] repository.
* Document templates are available at the https://github.com/metanorma/mn-templates-cc[mn-templates-cc] repository.

== Notes

Metanorma-CC was formerly published as `asciidoctor-csd` and `metanorma-csd`.
