---
title: Metanorma-Ribose library documentation
description: >-
  Library documentation for Metanorma-Ribose, the Metanorma flavor for Ribose documents.
  Synced from the upstream gem README at github.com/metanorma/metanorma-ribose.
source_url: https://github.com/metanorma/metanorma-ribose/blob/main/README.adoc
is_library_doc: true
layout: page
---


== Functionality

This gem processes https://www.metanorma.com[Metanorma documents] following
the Metanorma model for generating Ribose standards.

The gem currently inherits from the https://github.com/metanorma/metanorma-standoc
gem, and aligns closely to it. Refer to https://metanorma.com[] for guidance.

== Usage

The preferred way to invoke this gem is via the `metanorma` script:

[source,console]
----
$ metanorma --type ribose a.adoc                   # output HTML and DOC
$ metanorma --type ribose --extensions html a.adoc # output just HTML
$ metanorma --type ribose --extensions doc a.adoc  # output just DOC
$ metanorma --type ribose --extensions xml a.adoc  # output Metanorma XML
----

The gem translates the document into Metanorma XML format, and then
validates its output against the Ribose Metanorma XML document model; errors are
reported to console against the XML, and are intended for users to
check that they have provided all necessary components of the
document.

The gem then converts the XML into output formats such as HTML and PDF.

=== Installation

See https://www.metanorma.com for installation documentation.

== Documentation

See https://www.metanorma.com/author/ribose/[The Ribose flavor of Metanorma]

== Data Models

The Ribose Standard Document format is an instance of the
https://github.com/metanorma/metanorma-model-standoc[StandardDocument model]. Details of
this general model can be found on its page. Details of the Ribose modifications
to this general model can be found on the https://github.com/metanorma/metanorma-model-ribose[Metanorma-Ribose model]
repository.

== Examples

Example documents may be found in the https://github.com/metanorma/mn-samples-ribose[mn-samples-ribose]
repository.

== Notes

Metanorma-Ribose was formerly published as `metanorma-rsd`.
