---
layout: post
title: "Installing LaTeXML for Metanorma (and tex2mn)"
date: 2020-05-11
categories: about
authors:
  -
    name: Alex Bobrikovich
    email: abobrikovich@gmail.com
    social_links:
      - https://stackoverflow.com/story/camobap
      - https://github.com/camobap
  -
    name: Ronald Tse
    email: tse@ribose.com
    use_picture: assets
    social_links:
      - https://www.linkedin.com/in/rhtse/
      - https://github.com/ronaldtse

excerpt: >-
    There are many ways to install LaTeXML depending on your needs
redirect_from:
  - /blog/05-11-2020/latexml-installation/
---

== Introduction

Metanorma's processor for the StandardDocument model
(aka https://github.com/metanorma/metanorma-standoc[`metanorma-standoc`])
depends on the excellent https://dlmf.nist.gov/LaTeXML/[LaTeXML] package from
NIST to process MathML fragments.

Typically, you will only need the latest stable version of LaTeXML to use
Metanorma: version 0.8.4 as of today.

However, if you are using or plan on using TeX syntax input for Metanorma
(i.e. https://github.com/metanorma/tex2mn[`tex2mn`], see our previous post,
link:../2019-10-08-metanorma-with-latex-support-alpha[Metanorma now supports LaTeX input]),
you will need the currently unreleased version of LaTeXML 0.8.5 for
its additional features.

This post explains how to install the "`edge`" version of LaTeXML.

NOTE: Special thanks to https://github.com/brucemiller/[Bruce Miller] and
https://github.com/dginev[Deyan Ginev] for their unwavering support!


== Installing the latest stable LaTeXML

=== Windows

The https://chocolatey.org/packages/latexml[LaTeXML package] is available on
https://chocolatey.org[Chocolatey package manager] and can be easily installed
via the Chocolatey command-line interface.

[source,cmd]
----
choco install -y latexml
----

=== Linux

The https://snapcraft.io/latexml[LaTeXML snap] is available on
the https://snapcraft.io[Snap store] and can be installed on Ubuntu
and Linux platforms that are Snap-enabled.

[source,bash]
----
sudo snap install latexml
----

=== MacOS

The https://formulae.brew.sh/formula/latexml[LaTeXML formula] is available
from the https://brew.sh[Homebrew package manager].

[source,bash]
----
brew install latexml
----

=== CPANM

If the latest stable LaTeXML version isn't available from the
package manager of your choice, you can always install it with `cpanm`:

[source,bash]
----
# Download and install cpanminus
curl -L http://cpanmin.us | perl - App::cpanminus

cpanm LaTeXML
----


== Installing pre-release LaTeXML

In order to utilize unreleased features, you may follow the instructions
below to install pre-release versions of LaTeXML.


=== Windows

The following command installs the latest beta release of LaTeXML
via Chocolatey.

[source,cmd]
----
choco install -y latexml.beta
----


=== Linux

The following command installs the latest "`edge channel`" release of LaTeXML
via the Snap store.

[source,cmd]
----
sudo snap install latexml --edge
----


=== MacOS

There is currently no easy to install a pre-release version via Homebrew --
use the CPANM method instead.


=== CPANM

If you have to use the specific dev version of `LaTeXML` it can be installed with `cpanm`.

Notice that CPAN is a prerequisite, and its installation methods
differ per platform:

macOS:
[source,bash]
----
brew install cpanminus
----

Windows:
[source,bash]
----
choco install -y strawberryperl imagemagick.tool
----

Linux/Unix:
[source,bash]
----
curl -L http://cpanmin.us | perl - App::cpanminus
----

Once CPAN is installed, the remaining command is to install LaTeXML via `cpanm`:

[source,bash]
----
cpanm git://github.com/brucemiller/LaTeXML.git@9a0e7dc5
----



== Troubleshooting

In most cases, problems occur with installation dependencies that
depend on native libraries, such as:

* XML::LibXSLT
* XML::LibXML

The fix is to install the specific version of the dependency that correlates with the version of the native library installed on your machine.

This command on macOS, for example, ensures that XML::LibXSLT matches
the version of `libxml2` installed:

[source,bash]
----
brew install libxml2 cpanminus
env PATH=$(brew --prefix libxml2)/bin:$PATH \
  cpanm --notest XML::LibXSLT@1.96 \
  git://github.com/brucemiller/LaTeXML.git@9a0e7dc5
----


== References

* https://dlmf.nist.gov/LaTeXML/get.html[More options to install LaTeXML]
