---
layout: post
title: 'Metanorma Collection'
date: 2022-05-13
categories: documentation
authors:
  -
    name: Aliaksandr Babrykovich
    email: abobrikovich@gmail.com
    social_links:
      - https://github.com/CAMOBAP

excerpt: >-
  How to use Metanorma collection subcommand
---

== Intro

Additionally to `compile` and `site generate` sub-commands `metanorma` supports `collection` sub-command

== Example

Let's check on a real-world example https://github.com/metanorma/bipm-si-brochure[SI Brochure]

Make sure that you have link:/install[installed metanorma], once done you are ready to do the actual compilation

. Generate `site` first with:

  metanorma site generate . --agree-to-terms

Once it is finished you will be able to see compilation results in `site` directory (this is the default directory but you can change the target directory with `--output-dir` flag)

. Generate collection document with:

  metanorma collection collection.yml -w collection -x xml,html,presentation,pdf -c sources/collection_cover.html --agree-to-terms --no-continue-without-fonts

The resulting document will be in the directory `collection`

== Reference

* https://github.com/metanorma/metanorma-cli#compile-a-document-collection-metanorma-collection[Compile a document collection]
* link:/install[How metanorma can be installed]
