---
layout: post
title: 'Validating against ISO House Style'
date: 2022-03-13
categories: documentation
authors:
  -
    name: Nick Nicholas
    email: nick.nicholas@ribose.com
    social_links:
      - https://github.com/opoudjis

excerpt: >-
  Metanorma has just been updated to take the rules in the 
  https://www.iso.org/ISO-house-style.html[ISO house style] into account.
---
== Summary

ISO and IEC have a comprehensive prescription of the expected style and content arrangement
for their standards, https://www.iso.org/sites/directives/current/part2/index.xhtml[ISO/IEC DIR 2].
Metanorma since the beginning has applied the rules laid out in ISO/IEC DIR 2, to validate
ISO and IEC standards authored in Metanorma, and communicates the associated warnings to users
during document compilation. The rules that Metanorma validates for are laid out in
link:/author/iso/topics/content-validation/[ISO Content style validation], and include such
rules as:

* "see" and "refer to" can only introduce informative references. 
* Undated references may be made only to a complete document.
* Forewords shall not be subdivided

Metanorma has just been updated to take the rules in the https://www.iso.org/ISO-house-style.html[ISO house style]
into account. Metanorma now validates against the following requirements:

* https://www.iso.org/ISO-house-style.html#iso-hs-s-text-r-r-ref_clause3[References in Clause 3 (Terms and definitions)]:
Cross-references in terms clauses can only reference content within terms clauses.
Cross-references outside of terms clauses can only reference content outside of terms clauses.
So terms clauses and other content are self-contained in cross-referencing.
* https://www.iso.org/ISO-house-style.html#iso-hs-s-text-r-p-lists[Lists]:
List punctuation needs to be consistent with that of the sentence preceding it.
+
____
* If the list comprises several sentences, then use the following list format.
** The introductory sentence is a complete sentence and ends with a colon or a full stop.
** The list items are complete sentences that start with a capital letter and end with a full stop.
* If the list comprises one sentence broken into a list format, then:
** the introductory sentence is a partial sentence and preferably ends with a colon;
** the list items start in lower case and end with a semicolon (preferred) or a comma, used consistently;
** the final list item ends with a full stop.
____

* https://www.iso.org/ISO-house-style.html#iso-hs-s-text-r-p-lists[Lists]:
There should not be more than one ordered list in a numbered clause.
* https://www.iso.org/ISO-house-style.html#iso-hs-s-text-r-p-lists[Lists]:
No list should be more than four levels deep.
* https://www.iso.org/ISO-house-style.html#iso-hs-s-formatting-r-vocabulary[Vocabulary documents]:
Single terms clause in vocabulary document should have normal Terms and definitions heading.
Multiple terms clauses in vocabulary document should be prefixed with "Terms related to".
* https://www.iso.org/ISO-house-style.html#iso-hs-s-text-r-n-numbers[Numbers]:
The Unicode minus sign, U+2212, should be used instead of the hyphen.
* https://www.iso.org/ISO-house-style.html#iso-hs-s-text-r-p-and[And/Or]:
The conjunction _and/or_ should be avoided.
* https://www.iso.org/ISO-house-style.html#iso-hs-s-text-r-p-andor[And or &]:
Avoid ampersand in ordinary text
* https://www.iso.org/ISO-house-style.html#iso-hs-s-text-r-p-full[Full stops]:
Do not use full stop at the end of a title or caption.
