---
layout: post
title: "Encoding and rendering special characters (PDF, HTML)"
date: 2024-08-12
categories: documentation
authors:
  -
    name: Alexander Dyuzhev
    email: dyuzhev@gmail.com
    social_links:
      - https://www.linkedin.com/in/alexander-dyuzhev/
      - https://github.com/Intelligent2013/
  -
    name: Ronald Tse
    email: ronald.tse@ribose.com
    social_links:
      - https://github.com/ronaldtse

excerpt: >-
  Metanorma allows extending the default font set for rendering, ensuring that
  even the most complex documents are rendered accurately and in compliance with
  international standards.
---

== Introduction

Metanorma supports multiple rendering outputs from a unified body of
information. It is important to ensure that characters and symbols render
correctly across different formats and platforms, to maintain the integrity and
consistency of information.

The most common output formats generated by Metanorma are HTML and PDF, and for
these two formats, character rendering considerations are vastly different,
particularly when dealing with specialized symbols that may not be included in
standard fonts.


== How are symbols and characters rendered?

It is necessary to first understand how digital character encoding and rendering
works to appreciate the challenges associated with rendering special characters
and symbols.

The relevant technologies are:

* Unicode (ISO/IEC 10646)
* Fonts (individual font files: TrueType, OpenType; web fonts: WOFF)
* HTML (HyperText Markup Language)
* PDF (Portable Document Format)

Unicode is an character encoding standard that assigns a unique code
point to most characters, symbol, and script used worldwide. This code set
allows for the unambiguous representation of text across different platforms and
languages. Unicode is standardized as ISO/IEC 10646 and the registry of codes
is managed by the Unicode Consortium.

Fonts include a set of glyphs, which are the visual representations of
characters and symbols. When a character is rendered, the font is used to
display the corresponding glyph on the screen or in print. Modern fonts contain
glyphs with code points mapped to Unicode, allowing for the accurate display of
characters and symbols across fonts for a given Unicode code point.

Digital display of characters and symbols rely on the availability of the
necessary glyphs in the fonts used for rendering. If a font does not include a
specified glyph, the character will not be rendered correctly.


== Unicode and its planes

The [Unicode Standard](https://unicode.org/standard/standard.html) standardized
as [ISO/IEC 10646](https://www.iso.org/standard/76897.html) is the character
encoding standard that underpins text representation in virtually every modern
software application.

It was created to address the limitations of earlier character encoding systems,
which were often language-specific and could not accommodate the full range of
characters needed for global communication.

The Unicode registry is maintained by the
[Unicode Consortium](http://unicode.org), which assigns a unique code point to
every character, symbol, and script used in the world's writing systems. This
universal approach allows for the consistent representation and manipulation of
text across different platforms and languages.

Unicode characters are organized into planes, with each plane containing a
specific range of characters. The Basic Multilingual Plane (BMP) is the most
commonly used plane and includes characters from a wide range of scripts and
languages.

However, specialized symbols and characters are often found in higher planes,
such as the Supplementary Multilingual Plane (SMP) and the Supplementary
Ideographic Plane (SIP), including the emoji and dingbat symbols.

These specialized symbol planes are not always fully supported by standard
fonts, leading to rendering issues when displaying documents that contain these
symbols.

The Dingbats block, for example, is located in the SMP and contains a variety
of symbols and shapes that are commonly used in documents. These symbols are
frequently missing in standard fonts, leading to rendering issues when
displayed in PDF documents.

Many commonly used fonts do not implement the Dingbats block:

* Times New Roman
* Arial
* Helvetica
* Source Sans Pro
* Noto Sans


== Font support for Unicode symbols

One of the main reasons why not every font supports all Unicode symbols is the
sheer size and complexity of the Unicode standard. Unicode currently defines
over 140,000 characters, encompassing a vast array of symbols, letters, and
scripts from around the world. Creating a font that supports every single
Unicode character is a significant challenge in terms of both design and file
size.

Fonts are typically designed with a specific purpose or audience in mind, and
they prioritize certain ranges of Unicode characters over others. For example, a
font designed for use in Latin language documents may focus on supporting the
Latin alphabet and common punctuation marks, while a font designed for technical
or mathematical documentation might prioritize symbols and characters relevant
to those fields.

As a result, many fonts do not include the full range of Unicode characters,
particularly those in specialized blocks like "Dingbats", "Miscellaneous Symbols
and Pictographs", or "Emojis."

This is why documents that rely on these symbols may encounter rendering issues
when the selected font does not include the necessary glyphs.


== HTML font rendering

HTML is the standard markup language used for creating web pages, originally
standardized by the World Wide Web Consortium (W3C) and now maintained by the
WHATWG.

HTML supports the full range of Unicode character encoding in the document.

On the other hand, HTML glyph rendering is implemented by the browser, which
uses the system fonts installed on the user's device. This allows for a wide
range of fonts to be used for rendering symbols and characters.

When rendering a webpage and if a particular needed glyph is not found in the
specified font, the browser can dynamically fall back to another font that
includes the necessary glyph if it is not available in the primary font
specified by the webpage.

This fallback mechanism is seamless and generally goes unnoticed by the user,
allowing for a wide range of symbols and characters to be displayed correctly,
even if the primary font does not include them.


== PDF font rendering

PDF (Portable Document Format) is the most widely used format for the
publication and usage of electronic documents.

Originally developed by Adobe Systems in the early 1990s, PDF has since become
an ISO standard under [ISO 32000](https://www.iso.org/standard/63534.html). This
standardization has solidified PDF's role as the go-to format for documents that
need to be preserved in their original layout across different devices and
platforms.

The key advantage of PDF lies in its ability to embed all necessary components
-- such as text, fonts, and images -- within the document itself. This ensures
that the document will look the same regardless of the device or software used
to view it.

When a PDF is generated, the fonts used during the document creation process are
typically embedded into the file. While crucial for maintaining the document's
appearance, it also means that if a required glyph is not included in the
embedded fonts, it cannot be displayed correctly. This is a notable difference
from HTML, where the browser can access and use any available system fonts to
render content dynamically.

While HTML can dynamically fall back to another font that includes the
necessary glyph if it is not available in the primary font specified by the
webpage, PDF does not support dynamic font fallback. This can lead to issues
when rendering symbols that are not included in the embedded fonts, and the
resulting missing characters will be rendered in the PDF as placeholder
characters like `#`.

Furthermore, PDF supports not only Unicode characters but also specialized
symbols and characters from other character sets. While this is a powerful
feature, it also presents challenges when the selected font does not include the
necessary glyphs for these specialized symbols.


== Challenges of integrating specialized fonts in PDF documents

Here are some commonly-used symbols from the Unicode block "Dingbats"
(https://www.compart.com/en/unicode/block/U+2700[Compart "Dingbats"])
are frequently missing in many fonts, leading to missing characters in PDF
documents.

* ☑ (`U+2611` CHECK BOX)
* ✅ (`U+2705` WHITE HEAVY CHECK MARK)
* ✓ (`U+2713` CHECK MARK)
* ❌ (`U+274C` CROSS MARK)

This problem is particularly relevant when producing documents that must adhere
to international standards and be consistent across all platforms.


== Metanorma support for specialized fonts and characters in PDF

Metanorma touches on multiple areas of PDF font rendering, starting from
encoding.

* Metanorma supports both the embedding of Unicode characters in the document
and explicit glyph rendering using Unicode points, ensuring that all characters
and symbols are accurately encoded in the document.

* Dynamic font selection for glyph rendering is supported in Metanorma, allowing
users to specify exactly which fonts should be used when rendering a PDF. This
is particularly important for ensuring that specialized symbols and characters
are correctly rendered in the final document.

* Specific glyph and font pairs are supported in Metanorma, ensuring that if a
particular glyph from a particular font is needed, the output would be
consistent and accurate across all platforms.

* Metanorma's PDF rendering mechanism is based on the Apache FOP (Formatting
Objects Processor) engine. Metanorma ensures that font glyph fallback is
supported, allowing for seamless rendering of specialized symbols and characters
across different platforms.


== Challenges to integrate specialized fonts in PDF documents

Integrating specialized fonts in PDF documents comes with its own set of
challenges.

One of the primary issues is ensuring that the selected fonts are embedded
correctly in the PDF. In order to embed a font in a PDF, the font file must be
available at the compilation of the PDF document.

Metanorma uses the https://www.fontist.org[Fontist] software to manage local and
remote font loading, ensuring that all necessary fonts are accessible by
Metanorma's PDF engine during the document compilation process, in order to
facilitate the embedding of fonts in the final PDF document.

That said, the availability of specialized fonts can vary depending on the
platform and the fonts installed on the user's device due to licensing and
issues. Some platforms may provide additional proprietary fonts that are not
available on other platforms. These are concerns that designers should be aware
of when selecting fonts for organizational publications using Metanorma for
the cross-platform portability of the compilation process.

Windows and macOS both provide a set of system fonts that are commonly used, and
they also provide extended font sets that contain attractive and specialized
fonts. However, these fonts may not be available on other platforms, leading to
inconsistencies in the rendering of specialized symbols and characters across
different devices.


== Predefined fonts in Metanorma flavors

Metanorma supports a variety of document flavors, each of which is tailored to
the specific needs of different standards organizations. For each flavor,
Metanorma comes with a set of predefined fonts that are selected to ensure that
the most commonly used symbols and characters are supported.

For example, the ISO flavor in Metanorma uses the following fonts:

* Cambria
* Times New Roman
* Cambria Math
* Noto Serif
* Noto Serif HK/JP/KR/SC/TC

On the other hand, the OGC (Open Geospatial Consortium) flavor uses:

* Lato
* STIX Two Math
* Noto Sans
* Noto Sans HK/JP/KR/SC/TC

These fonts are chosen to ensure that the documents produced in each flavor meet
the specific requirements of the respective standards organizations, including
the accurate rendering of all necessary symbols and characters.


== Metanorma supports extended font support

While the predefined fonts in each Metanorma flavor are carefully selected,
there are situations where additional font support may be required, particularly
when dealing with documents that include specialized symbols.

Metanorma allows users to extend the font set used for PDF rendering by
specifying additional fonts through the document attribute `:fonts:`.

This flexibility is crucial for ensuring that all symbols and characters are
rendered correctly, even in complex documents.

For instance, the free font `Noto Emoji` can be added to the font set to ensure
that a wide range of emoji and symbols are supported:

[source,asciidoc]
----
:fonts: Noto Emoji
----

Similarly, the free font `FreeSerif` can be used to provide additional coverage
for a broader range of Unicode symbols:

[source,asciidoc]
----
:fonts: FreeSerif
----

For users on the Windows platform, the `Segoe UI Emoji` font can be specified to
ensure comprehensive emoji support:

[source,asciidoc]
----
:fonts: Segoe UI Emoji
----

By allowing users to customize the fonts used in PDF rendering, Metanorma
ensures that even the most complex documents are rendered accurately and in full
compliance with international standards.


When using the additional `:fonts:` attribute, the implication is that the HTML
output will also be subject to the same font requirement. This means that while
the HTML rendering engine will use the system fonts available on the user's
device to render any missing glyphs, the implementation of glyphs across
different fonts will vary.

The benefit of choosing an open-source font, such as those from Google Fonts,
would be that the font is freely available and can be used across different
platforms without licensing restrictions, allowing the HTML page to load those
fonts as a "web font" (WOFF), such that the browser can render the glyphs
correctly.



== Conclusion

Accurate rendering of special characters and symbols in PDF documents is crucial
for maintaining the integrity and consistency of information across platforms.
The challenges associated with rendering these characters stem from the inherent
differences between HTML and PDF in how they handle fonts and characters, as
well as the limitations of font support for the full range of Unicode symbols.

Metanorma provides a robust solution to these challenges by allowing users to
extend the font set used for PDF rendering, ensuring that all necessary symbols
and characters are correctly rendered in the final document. By ensuring the
accurate encoding and rendering of glyphs, Metanorma enables the production of
high-quality, standards-compliant PDF and HTML output that meet the rigorous
requirements of international standards organizations.

// == Bibliography

// * https://www.metanorma.org/author/ref/document-attributes/#visual-appearance
// * https://www.compart.com/en/unicode/block/U+2600
// * https://www.compart.com/en/unicode/block/U+2700
// * https://www.compart.com/en/unicode/block/U+2b55
// * https://unicode.org/standard/standard.html
// * https://www.iso.org/standard/63534.html
// * https://www.iso.org/standard/76897.html
// * https://www.iso.org/iso-8601-date-and-time-format.html
