---
layout: post
title: "Special characters rendering in the PDF"
date: 2024-08-12
categories: documentation
authors:
  -
    name: Ronald Tse
    email: ronald.tse@ribose.com
    social_links:
      - https://github.com/ronaldtse
  -
    name: Alexander Dyuzhev
    email: dyuzhev@gmail.com
    social_links:
      - https://www.linkedin.com/in/alexander-dyuzhev/
      - https://github.com/Intelligent2013/

excerpt: >-
  Metanorma allows extending the fonts set for the PDF rendering.
---

== Introduction

There are cases when the symbols rendering ok in HTML, but doesn't in the PDF.
In this case, you can see the hash symbol `#` in the PDF instead of the required glyph.
It means that the fonts which used in the PDF rendering mechanism (Times New Roman, Arial,
Lato, STIX Two Math, Noto Sans, etc.) don't contain the required glyph.

For instance, the commonly used glyphs are:

* ☑(`U+2611`),
* ✅(`U+2705`),
* ✓(`U+2713`)
* ❌(`U+274C`)

from the Unicode Block “Dingbats” (https://www.compart.com/en/unicode/block/U+2700) usually missing
in the most fonts.


== Solution

PDF rendering mechanism in the Metanorma based on the Apache FOP engine. The Apache FOP
requires setting the exactly fonts for the PDF rendering vs. HTML engine in the browser or
MS Word which manipulate all available fonts in the operating system (OS).

Each Metanorma flavor has the predefined fonts, for example:

ISO:: Cambria, Times New Roman, Cambria Math, Noto Serif, Noto Serif HK, Noto Serif JP, Noto Serif KR, Noto Serif SC, Noto Serif TC
OGC:: Lato, STIX Two Math, Noto Sans, Noto Sans HK, Noto Sans JP, Noto Sans KR, Noto Sans SC, Noto Sans TC

There are fonts, often with the 'Emoji' in the name, which contains the extended set of special glyphs.

You can expand this font set by the document attribute `:fonts:` (https://www.metanorma.org/author/ref/document-attributes/#visual-appearance).

For instance, for the free font `Noto Emoji`:

```
:fonts: Noto Emoji
```

Also, for one more free font `FreeSerif`:

```
:fonts: FreeSerif
```

If you're working on the Windows platform, there is the font `Segoe UI Emoji`

```
:fonts: Segoe UI Emoji
```


== Bibliography

* https://www.metanorma.org/author/ref/document-attributes/#visual-appearance
* https://www.compart.com/en/unicode/block/U+2600
* https://www.compart.com/en/unicode/block/U+2700
* https://www.compart.com/en/unicode/block/U+2b55
