---
layout: bipm-flavor
title: Metanorma BIPM document attributes
---

[[note_general_doc_ref_doc_attrib]]
[NOTE]
====
The document attributes listed below are unique to Metanorma's processing of BIPM documents.

For _common document attributes_, see link:/author/ref/document-attributes[Document attributes reference] in general Metanorma author's documentation. That page describes attributes that apply to all Metanorma flavors, not just BIPM.

For an _introduction to Metanorma AsciiDoc document attributes_ and how Metanorma uses them, see link:/author/topics/document-format/meta-attributes/[the corresponding topic].
====

== Document information

`:edition:`:: The document edition.

`:revdate:`:: The date the document was last updated.

`:copyright-year:`:: The year which will be claimed as when the copyright for
the document was issued.

`:doctype:`:: *Mandatory.* The document type. Permitted types are:
+
--
* `brochure` (default)
* `mise-en-pratique`
* `rapport`
* `monographie`
* `guide`
* `meeting-report`
* `technical-report`
* `working-party-note`
* `strategy`
* `cipm-mra`
* `resolution`
--

`:status:`:: The document status. Permitted types are:
+
--
* `draft-proposal`
* `draft-development`
* `in-force`
* `retired`
--

`:language:`:: *Mandatory.* The language of the document (`en` or `fr`)

`:title-en:`:: *Mandatory.* The title of the document in English. For JCGM documents treated as equivalent to `title-main-en` in ISO.
`:title-fr:`:: *Mandatory.* The title of the document in French. For JCGM documents treated as equivalent to `title-main-fr` in ISO.

`:title-cover-en:`:: The title of the front cover of the document in English (where different from the title proper).
`:title-cover-fr:`:: The title of the front cover of the document in French (where different from the title proper).

`:title-part-en:`:: The title of the document part in English (if applicable).
`:title-part-fr:`:: The title of the document part in French (if applicable).

`:title-subpart-en:`:: The title of the document subpart in English (if applicable).
`:title-subpart-fr:`:: The title of the document subpart in French (if applicable).

`:title-appendix-en:`:: The title of the appendix in English, if this document is an appendix published separately; `title-en` becomes the title of the main document, as presented within the standalone appendix.
`:title-appendix-fr:`:: The title of the appendix in French, if this document is an appendix published separately; `title-fr` becomes the title of the main document, as presented within the standalone appendix.

`:title-annex-en:`:: The title of the annex in English, if this document is an annex of an appendix published separately [added in https://github.com/metanorma/metanorma-bipm/releases/tag/v1.0.2]; `title-appendix-en` becomes the title of the main document, as presented within the standalone appendix.
`:title-annex-fr:`:: The title of the annex in French, if this document is an annex of an appendix published separately [added in https://github.com/metanorma/metanorma-bipm/releases/tag/v1.0.2]; `title-appendix-fr` becomes the title of the main document, as presented within the standalone appendix.

`:title-provenance-en:`:: A subtitle giving the provenance of the document, in English [added in https://github.com/metanorma/metanorma-bipm/releases/tag/v1.0.8].
`:title-provenance-fr:`:: A subtitle giving the provenance of the document, in French [added in https://github.com/metanorma/metanorma-bipm/releases/tag/v1.0.8].

`:partnumber:`:: The number of the document part, if applicable. If it is in the format `m.n`, the portion after the period becomes the subpart number.

`:appendix-id:`:: The number of the appendix, if this document is an appendix published separately.

`:annex-id:`:: The number of the annex of the appendix, if this document is an annex of an appendix published separately [added in https://github.com/metanorma/metanorma-bipm/releases/tag/v1.0.2].

`:si-aspect:`:: The domain of SI covered by the document; used to select logo in PDF cover page. The logo nominates one primary SI base units, and defining consonants for that unit and possibly others as well. Permitted values are:
+
--
* `A_e_deltanu` (ampere; time)
* `A_e` (ampere)
* `cd_Kcd_h_deltanu` (candela; mass, time)
* `cd_Kcd` (candela)
* `full` (all units)
* `K_k_deltanu` (kelvin; mass, time)
* `K_k` (kelvin)
* `kg_h_c_deltanu` (kilogram; length, time)
* `kg_h` (kilogram)
* `m_c_deltanu` (metre; time)
* `m_c` (metre)
* `mol_NA` (mole)
* `s_deltanu` (second)
--
+
NOTE: See the https://github.com/metanorma/metanorma-bipm/issues/14[SI Aspect implementation issue] for rendering details.

`:meeting-note:`:: Note on when and where a guide was adopted.

The attribute `:draft:`, if present, includes review notes in the XML output;
these are otherwise suppressed.


== Document dates and relationships

`:supersedes:`:: One or more BIPM document that this BIPM document standard supersedes; the superseded
document may still remain in effect. Identified with document identifier. Comma delimited.

`:superseded-by:`:: One or more BIPM document that this BIPM document standard is superseded by; this
document may still remain in effect. Identified with document identifier. Comma delimited.

`:supersedes-date_{i}:`:: Date of the document draft or version which this document supersedes.
Assumes superseded document does not have distinct identifier.
`:supersedes-draft_{i}:`:: Draft of the document which this document supersedes.
Assumes superseded document does not have distinct identifier.
`:supersedes-edition{i}:`:: Version of the document which this document supersedes.
Assumes superseded document does not have distinct identifier.

`:comment-period-from:`:: Start of the period during which comments are allowed on the document draft.
`:comment-period-to:`:: End of the period during which comments are allowed on the document draft. (optional)

`:obsoleted-date:`:: The date a document was superseded.
`:implemented-date:`:: The date a document became effective.

`:supersedes-date_{i}:`:: Date of the document draft or version which this document supersedes.
`:supersedes-draft_{i}:`:: Draft of the document which this document supersedes.
`:supersedes-version_{i}:`:: Version of the document which this document supersedes.



== Contribution information

`:committee-en:`:: *Mandatory.* The name of the relevant committee in English. This includes inter-organization entities.
`:committee-fr:`:: *Mandatory.* The name of the relevant committee in French. This includes inter-organization entities.
`:committee-acronym:`:: *Mandatory.* The acronym of the relevant committee. This includes inter-organization entities.
+
--
* `CGPM`: General Conference on Weights and Measures / Conférence générale des poids et mesures
* `CIPM`: International Committee for Weights and Measures / Comité international des poids et mesures
* `BIPM`: International Bureau of Weights and Measures / Bureau International des Poids et Mesures
* `CCAUV`: Consultative Committee for Acoustics, Ultrasound and Vibration / Comité consultatif de l'acoustique, des ultrasons et des vibrations
* `CCEM`: Consultative Committee for Electricity and Magnetism / Comité consultatif d'électricité et magnétisme
* `CCL`: Consultative Committee for Length / Comité consultatif des longueurs
* `CCM`: Consultative Committee for Mass and Related Quantities / Comité consultatif pour la masse et les grandeurs apparentées
* `CCPR`: Consultative Committee for Photometry and Radiometry / Comité consultatif de photométrie et radiométrie
* `CCQM`: Consultative Committee for Amount of Substance: Metrology in Chemistry and Biology / Comité consultatif pour la quantité de matière : métrologie en chimie et biologie
* `CCRI`: Consultative Committee for Ionizing Radiation / Comité consultatif des rayonnements ionisants
* `CCT`: Consultative Committee for Thermometry / Comité consultatif de thermométrie
* `CCTF`: Consultative Committee for Time and Frequency / Comité consultatif du temps et des fréquences
* `CCU`: Consultative Committee for Units / Comité consultatif des unités
* `CCL-CCTF-WGFS`: CCL-CCTF Frequency Standards Working Group
* `JCGM`: Joint Committee for Guides in Metrology / Comité commun pour les guides en métrologie
* `JCRB`: Joint Committee of the Regional Metrology Organizations and the BIPM / Comité mixte des organisations régionales de métrologie et du BIPM
* `JCTLM`: Joint Committee for Traceability in Laboratory Medicine / Comité commun pour la traçabilité en médecine de laboratoire
* `INetQI`: International Network on Quality Infrastructure
--

`:workgroup:`:: The name of the relevant workgroup.
`:workgroup-acronym:`:: The acronym of the relevant workgroup.

`:role_{i}:`:: If provided and is other than `author` or `editor` (e.g. "`WG-N co-chair`"),
is treated as a subclass of `editor`.
