# Content root directories.
# Each directory is scanned for _nav.yml files. Any directory with a
# _nav.yml gets a sidebar with its content defined in that YAML file.
roots:
  - author
  - flavors
  - develop
  - learn
  - software
  - specs
  - samples
  - library
