---
layout: author-docs
title: Writing in Metanorma
redirect_from:
  - /overview/getting-started/
  - /docs/getting-started/
---

== How do I write in Metanorma?

Metanorma adopts the WYSIWYM ("`what you see is what you mean`") paradigm
based on the AsciiDoc markup syntax, allowing authoring standards with
output exactly what you meant and how you wanted, without unnecessary
formatting worries. This is similar in spirit to La(TeX) and Markdown.

That also means it is not WYSIWYG -- you'll be dealing with a plain-text editor
and the command-line interface, rather than something that resembles,
say, a Microsoft Word document.
It might be confusing at first, but the upsides far outweigh the difficulty
in learning how to use Metanorma.

For example, Metanorma facilitates machine-readability, automation, validation,
automatic formatting, auto-numbering, and enables using a single canonical
format for the re-generation of all document output formats.

Read more about the link:/basics/approach[Metanorma approach].

TIP: If you are new to AsciiDoc,
you might want to use the http://asciidoctor.org/docs/user-manual/[Asciidoctor AsciiDoc manual]
alongside this guidance.

We have also published four blog entries on how to author a Metanorma document, step by step:

* link:/blog/2018-12-11-writing-metanorma-in-asciidoc/[Part 1]
* link:/blog/2018-12-15-writing-metanorma-in-asciidoc-2/[Part 2]
* link:/blog/2018-12-16-writing-metanorma-in-asciidoc-3/[Part 3]
* link:/blog/2019-01-15-writing-metanorma-in-asciidoc-4/[Part 4]


== Recommended text editors

These editors have been reported to work well for writing Metanorma AsciiDoc:

* https://atom.io/[Atom] with https://atom.io/users/asciidoctor[Asciidoctor plugins]
* https://code.visualstudio.com/[Microsoft Visual Studio Code]
  with https://marketplace.visualstudio.com/items?itemName=joaompinto.asciidoctor-vscode[AsciiDoc extension]
  for live preview

It's perfectly fine to use any plain-text editor: and many developer-oriented editors
support AsciiDoc live previews and syntax highlighting.
For those that don't, you will have to rely on log output from Metanorma
during document generation.
