---
layout: author-docs
description: >-
  <p>
  This is a general guidance for authoring Metanorma documents.

  <p>
  Since Metanorma uses AsciiDoc markup
  (see <a href="../approach/">Approach</a> for technical background),
  this section details the specific ways in which Metanorma interprets AsciiDoc markup,
  as well as custom markup directives.
  
  <p>
  This section applies across most of the
  <a href="/flavours/">officially supported flavours of Metanorma</a>.
  If you are using one of those flavours,
  be sure to also check out guidelines for your flavour.
---

= Document format

== How does authoring with AsciiDoc work, for&nbsp;beginners

The AsciiDoc approach Metanorma suggests for authoring standards
is not WYSIWYG—meaning that you’ll be dealing with a plain-text editor and a command line,
rather than something that resembles, say, a Microsoft Word document.

The text you’ll be authoring would look more like HTML or Markdown,
and it will be formatted like the end document during build stage.

This might look confusing at first, but the upside, in our opinion, far outweighs that:
with documents formatted using semantic markup like Asciidoctor
it is much easier to automate key validation and formatting processes
such as checking for missing document components, automatic numbering,
and generating output in multiple formats from one source text.

If you are new to AsciiDoc (and maybe if you aren’t),
you are encouraged to use the http://asciidoctor.org/docs/user-manual/[Asciidoctor manual]
alongside this guidance.

== Unsupported AsciiDoc features

* Sidebars (`aside`s) are not supported: they have been repurposed for link:./reviewer-notes/[reviewer comments].
* Page breaks (`thematic break`) are not supported.
* ASCII art/preformatted text (`literal`) are not supported in most Metanorma flavours.

== Autonumbering

Autonumbering in Metanorma extends to formulas (which are encoded as "stem" blocks) and notes.
Autonumbering is applied in the conversion from Metanorma XML to output formats (`isodoc`);
by default it restarts for each annex, but is continuous for the main body of text.
