---
layout: author-docs
description: >-
  <p>
  This section provides general guidance for authoring Metanorma documents using
  Metanorma AsciiDoc.

  <p>
  This describes the Metanorma AsciiDoc language and how it extends the AsciiDoc
  markup language (see <a href="/basics/approach/">Approach</a> for technical
  details).

  <p>
  Content here applies across most of the
  <a href="/flavors/">supported flavors of Metanorma</a>, for additional
  features available for specific flavors, please refer to the flavor's
  documentation.
---

= Metanorma AsciiDoc

== Basic syntax

Metanorma AsciiDoc is based on the AsciiDoc syntax used by Asciidoctor,
and inherits most of its syntax.

Please refer to the https://asciidoctor.org/docs/user-manual/[Asciidoctor manual]
for general markup mechanisms offered in typical AsciiDoc.


== Unsupported AsciiDoc features

* Sidebars (``aside``s) are not supported.
Instead, see link:./annotations/[annotations].

* ASCII art, or preformatted text ("literal content"), are only supported in
selected Metanorma flavors, as they are disallowed in most standardization
organizations.


== Auto-numbering

Metanorma auto-numbering extends beyond typical AsciiDoc, applying to document
elements including:

* tables
* figures
* formulas
* notes

Auto-numbering is applied during conversion from Metanorma semantic XML to Metanorma presentation XML.

NOTE: Auto-numbering rules are implemented according to the needs of specific
flavors.
For most flavors, the numbering is continuous within the main body of text
and restarts for each annex.
