---
layout: author-docs
---

= How to install Metanorma

To be able to build Metanorma documents of any flavor, you need to have the
`metanorma-cli` Ruby gem installed.
To simplify installation of the gem and its dependencies,
following installation methods are currently supported.


[TIP]
====
.Full manual

Assuming you know what you’re doing, you can install Metanorma CLI gem by hand.
You will have to take care of dependencies: an appropriate Ruby version,
plus other software depending on the end documents you’re building.

Refer to link:/software/metanorma-cli/docs/installation/[Metanorma CLI installation docs]
for more.
====


[[docker-setup]]
== Docker setup

This setup method works for all platforms that support the Docker container
framework.

[TIP]
====
This method is the recommended way of getting Metanorma installed, although
for certain reasons (such as performance)
that you may wish to setup the components directly on your machine.
====

. Pull the container:
+
[source,sh]
----
docker pull ribose/metanorma
----
. Specify the `:local-cache-only:` AsciiDoc attribute
in document header to speed up rendering (optional)
. To render the document into HTML, Word and XML,
execute from within the directory containing the Metanorma document
(replacing `{my-document-file}` with your actual document's filename):
+
[source,sh]
----
docker run -v "$(pwd)":/metanorma/ -w /metanorma ribose/metanorma "metanorma -t iso -x html,doc,xml {my-document-file}"
----

[TIP]
====
See https://github.com/riboseinc/metanorma-docker[metanorma-docker] for more information.
====


[[macos-setup]]
== macOS

=== Using https://brew.sh/[Homebrew]

[source,sh]
----
brew tap riboseinc/metanorma
brew install metanorma
----

This uses Metanorma’s link:/software/homebrew-metanorma[Homebrew formula].
To install using the HEAD development version of the formula, run:

[source,sh]
----
brew install --HEAD https://raw.githubusercontent.com/riboseinc/homebrew-metanorma/master/metanorma.rb
----


=== All-in-one script

Run the following for an automatic install
that would prepare a fresh system to work with Metanorma.

NOTE: This installs not just the Metanorma components, but also prerequisites
such as Homebrew and basic tools like Sublime Text.

This should take less than 15 minutes depending on your machine and Internet connection:

[source,sh]
----
bash <(curl -s https://raw.githubusercontent.com/riboseinc/metanorma-macos-setup/master/metanorma-setup)
----


== Linux

Linux setup uses all-in-one script. You need to have `curl` installed beforehand.

TIP: See more in https://github.com/riboseinc/metanorma-linux-setup[metanorma-linux-setup] repository.

=== Ubuntu

[source,sh]
----
sudo bash -c "curl -L https://raw.githubusercontent.com/riboseinc/metanorma-linux-setup/master/ubuntu.sh | bash"
curl -L https://raw.githubusercontent.com/riboseinc/metanorma-linux-setup/master/install-gems.sh | bash
----

=== CentOS

[source,sh]
----
sudo bash -c "curl -L https://raw.githubusercontent.com/riboseinc/metanorma-linux-setup/master/centos.sh | bash"
curl -L https://raw.githubusercontent.com/riboseinc/metanorma-linux-setup/master/install-gems.sh | bash
----

== Windows

=== Using https://chocolatey.org/[Chocolatey]

Execute the following:

[source,console]
----
Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
refreshenv
cinst msys2 --params "/NoUpdate" -y # install msys2 without system update
cinst metanorma -y
refreshenv
----

[TIP]
====
See also
link:/blog/12-25-2018/metanorma-on-windows-via-chocolatey/[the blog post on Metanorma Chocolatey package].
====

=== Docker installation shortcut

Run this command in your `cmd.exe` or `PowerShell` to install
the Metanorma Docker container and all prerequisites (see <<docker-setup>>):

[source,sh]
----
bitsadmin /transfer get https://raw.githubusercontent.com/riboseinc/metanorma-windows-setup/master/install.bat %cd%\install.bat & .\install.bat
----

== Installing gems separately

See link:/software/metanorma-cli/[Metanorma CLI docs]
on how to install that gem on its own, be sure to note the dependencies.
