---
layout: author-docs
---
= Adding Metadata Using Document Attributes

tag::tutorial[]
The header contains information about the document (metadata). You specify these metadata by using predefined document attributes, that look like this: `:document-attribute:`. Most of the attributes take a value, while others are simple flags without a value, like `:draft:`. 

Some of the metadata will be visible in your document, such as `:title:`, while others are not visible but still affect how your document is generated. The order of attributes doesn’t matter to Metanorma.
You can specify metadata about:

* Authors: Issuing organization, authors, and their location
* Document info: Language, document stages (draft, published, etc.) copyright holder, etc.
* Dates: Draft dates, revision dates, publishing date, copyright year, etc. 
* Identifiers: Document numbers, ISBNs, URIs (Uniform Resource Identifiers)

NOTE: Other metadata influence how the document is generated and should only be used by advanced users. Often, they will require familiarity with your SDO's structures and processes.

Here’s an example:

[source, AsciiDoc]
----
= Rice model <1>
Author <2>
:docnumber: 17301 <3>
:doctype: standard <4>
:copyright-year: 2021
:language: en
:mn-document-class: iso <5>
:technical-committee: Food products <6>
:fullname: Your Name <7> 
:fullname_2: Co-Authors Name
:address: Chemin de Blandonnet 8 + \ <8>
CP 401 - 1214 Vernier + \
Geneva + \
Switzerland
:draft: <9>
:mn-output-extensions: xml,html,doc,html_alt <10>
----

<1> Document title
<2> The author line is ignored by Metanorma, but needs to be present for Asciidoctor to process document attributes correctly.
<3> `:docnumber:` is the first document attribute, and it has the value _17301_
<4> `:doctype:` defines the type of document, for example standard, report, guide, etc. The allowed values for this attribute are specific to each SDO.
<5> `:mn-document-class:` indicates the Metanorma flavor the document should be checked against. 
<6> The committee responsible for the document
<7> The author’s name. You can add co-authors by appending the attribute with a number:  `_2`, `_3`, and so on. 
<8> When you add an address that contains multiple lines, end each line except for the last with `+ \`. Alternatively, you can enter each line into its own attribute, such as `:street:`, `:postcode:`, `:city:`, `:country:`. 
<9> `:draft:` renders comments as well. The attribute does not take any values: it is either present or not. 
<10> `mn-output-extensions` specifies the generated outputs. It can take several values that must be comma-delimited.

end::tutorial[]


== Which attributes to specify?

The attributes required or allowed to be specified for given document
depend on the type of document and the Metanorma flavor used.

See link:/author/ref/document-attributes/[generic attribute reference]
for attributes supported by most Metanorma flavors.
If you’re using one of the officially supported Metanorma flavors,
consult your flavor’s author documentation as well.


== Referencing attributes in the text

The body of the document can reference the values of document attributes.
Here’s an example of referencing committee-related metadata entries:

[source,asciidoc]
--
This document was prepared by Technical Committee ISO/TC {technical-committee-number}, _{technical-committee}_, Subcommittee SC {subcommittee-number}, _{subcommittee}_.
--

If the corresponding document attributes are not populated in the header, then the references
themselves will not be populated.


== Dealing with HTML entities

Document attribute values, unlike document text, cannot deal with HTML entities.
If you need to have non-ASCII characters in document title, or dashes for compound titles,
you will need to enter them directly as Unicode.

As an example, this would work:

[source,adoc]
--
:title-part-en:Information Technology—Security
:title-main-fr: Spécification et méthodes d'essai
--

However, this wouldn’t:

[source,adoc]
--
:title-part-en:Information Technology\&mdash;Security
:title-main-fr: Sp\&eacute;cification et m\&eacute;thodes d'essai
--
