---
layout: bsi-flavor
title: Metanorma BSI attribute notes
---

This page collects the document-type lists, identifier-construction rules,
and adoption and commentary guidance that accompany the
link:/flavors/bsi/ref/document-attributes[Metanorma BSI document attributes]
reference. The attributes themselves (including the visual-appearance
attributes such as `:coverpage-image:` and `:document-scheme:`) are documented
there.

== Document types

The following document types are recognised in the `:doctype:` document attribute:

BSI document types::
+
--
* `british-standard`
* `draft-for-development`
* `published-document`
* `privately-subscribed-standard`
* `publicly-available-specification`
* `flex-standard`
--

Adoptable types, ISO::
+
--
* `international-standard`
* `technical-specification`
* `technical-report`
* `guide`
* `publicly-available-specification`
* `international-workshop-agreement`
--

Adoptable types, IEC::
+
--
* `international-standard`
* `technical-specification`
* `technical-report`
* `industry-technical-agreement`
--

Adoptable types, CEN and CENELEC::
+
--
* `standard`
* `technical-specification`
* `technical-report`
* `guide`
* `european-workshop-agreement`
--

The following document types are recognized in the `:docsubtype:` document attribute:

* `specification`
* `method-of-test`
* `method-of-specifying`
* `vocabulary`
* `code-of-practice`

== Document numbers

In the case of native BS standards, the identifier is compiled from a combination of the `doctype`,
`docnumber`, and `copyright-year` document attributes, with a numeric `docnumber` value.

So

[source,adoc]
----
:docnumber: 1000
:doctype: publicly-available-specification
:copyright-year: 2021
----

generates the document identifier "PAS 1000:2021".

In the case of document adoptions, the `docidentifier` attribute should be used (to which `BS` will be prefixed),
instead of assembling an identifier out of components, so that the source document identifier can be built up accurately.

Part numbers of the original document should also be included in the `docidentifier` attribute,
instead of being named with the `partnumber` attribute.

So

[source,adoc]
----
:docidentifier: ISO/TR 123-2:1985
:doctype: technical-report
----

generates the document identifier "BS ISO/TR 123-2:1985".

Note that the `:copyright-year:` attribute is added to the identifier of a native BSI document,
but not to that of an adopted document. So a 2022 adoption of ISO 123:1985 will still have the identifier
"BS ISO 123:1985".

== Related BSI Standards

The frontispiece of BSI Standards includes text like the following:

____
The following BSI references relate to the work on this document: +
Committee reference DEF/1 +
Draft for comment 20/30387670 DC
____

This text is created by adding the BSI list of documents that the document relates to
as a semicolon-delimited list of references, using `:bsi-related:`:

[source,adoc]
----
:bsi-related: Committee reference DEF/1;Draft for comment 20/30387670 DC
----

The introductory phrase is added automatically.

== Adoption of standard

An adopted external standard is defined as `:adopted-from:`:

[source,adoc]
----
:docidentifier: NA to BS EN 1991-1-2
:adopted-from: EN 1991-1-2
----

[source,adoc]
----
:docidentifier: BS ISO 639-2
:adopted-from: ISO 639-2
----

The identifier for such adoptions is generated based on the `:adopted-from:` value, if
`:docidentifier:` is not supplied.

== Expert Commentaries

Expert commentaries are of type `:doctype: expert-commentary`, and are commentaries of another
document; the related document is indicated with `:annotation-of:`.

The author of the commentary is indicated as the author of the document, including credentials
(indicated with `:contributor-credentials:`) and their position (`:contributor-position:`) and
possibly organizational affiliation (`:affiliation:`). The position can be discursive.

[source,adoc]
----
:docidentifier: BS ISO 639-2
:annotation-of: ISO 639-2
:fullname: Eamonn Hoxey
:contributor-credentials: PhD, F.R.Pharm.S.
:contributor-position: Vice President, Medical Devices Quality & Compliance -- Strategic programmes, Johnson & Johnson Medical Ltd, Former Chair ISO TC 210, Quality management and related general aspects for medical devices, and Principal UK Expert to ISO TC 210 WG 1, Quality Management Systems.
:role: author
----
