---
layout: author-docs
---

= Metanorma's approach to authoring documents

== General

Essentially, Metanorma converts given source document --
a set of files authored using AsciiDoc markup—to an XML-based presentation
of the document according to the document model.

The XML format intends to introduce rigour into the each
standard’s authoring process, and is described in corresponding documentation.

Metanorma validates the resulting XML document based on formal schema, and
outputs end deliverables in appropriate formats (HTML, PDF, MS Word, etc.)
according to the Metanorma flavor used.


== Metanorma document model

The https://github.com/metanorma/metanorma-model-standoc[Metanorma Standard Document document model]
provides rigour in the standards authoring process; existing
document templates do not support such rigour down to the element level.
It also introduces flexibility by decoupling the document structure from
its presentation.

Formal definitions of standards prescribe the contents of standards to a level
amenable to an explicit document model.
The ISO International Standard format, as prescribed in
http://www.iec.ch/members_experts/refdocs/iec/isoiecdir-2%7Bed7.0%7Den.pdf[ISO/IEC DIR 2 "Principles and rules for the structure and drafting of ISO and IEC documents"],
is one of the more detailed such prescriptions available.

A formal document model allows checking for consistency in format and content, and expedite
authoring and quality control of standardized documents. Authoring standards through a
more abstract formal model also permit enhanced functionality such as
cross-reference link checking and auto-numbering of sections, figures, tables and formulas.
Outputting a document in different languages also becomes straightforward.

== Input syntax: AsciiDoc and Asciidoctor

Metanorma supports input using Metanorma AsciiDoc, based on the AsciiDoc syntax.
Specifically, the Asciidoctor version of AsciiDoc is adopted as the basis of Metanorma AsciiDoc.

AsciiDoc is somewhat similar to both https://daringfireball.net/projects/markdown/[Markdown]
and https://docbook.org/[DocBook]: it combines the relative ease of use of the former
(using relatively lightweight markup), and the rigour and expressively of the
latter (it has a well-defined syntax, and was in fact initially developed as a
DocBook document authoring tool).

NOTE: Since Metanorma uses the Asciidoctor parser, and Asciidoctor can output text and HTML,
the Asciidoctor toolchain could be used to preview a Metanorma document, with the caveat
that Metanorma AsciiDoc features and flavor-specific markup may not be rendered by Asciidoctor.
Metanorma also renders HTML and Microsoft Word output, which greatly differs from that of Asciidoctor.

TIP: See link:/author/topics/writing-asciidoc[Writing AsciiDoc] for an introduction
and advice on authoring with AsciiDoc.

=== Differences from typical AsciiDoc syntax

While Metanorma uses AsciiDoc markup, there are some specifics in how it is interpreted.
This is especially important to know for those coming from an
AsciiDoc / Asciidoctor-AsciiDoc background.

Metanorma imposes a much more strict and hierarchical document model than
typical AsciiDoc does.

In particular, it has a strict hierarchy of sections, then blocks,
then inline markup, which cannot be mixed. A table for example cannot occur inside a list,
and a section cannot occur inside a table.

For example, while Asciidoctor allows some flexibility in
table markup (though its `a` table cell format taking arbitrary Asciidoctor markup),
Metanorma will not process arbitrary formatting.

Asciidoctor has some formatting constraints because of its own document model
that users need to be aware. For example, Asciidoctor disallows
multiple paragraphs in footnotes
http://discuss.asciidoctor.org/footnotes-with-paragraph-breaks-td4130.html[by design];
and it has a strict hierarchy about how elements can be embedded within other elements,
though still less strict than in Metanorma
(so for example a list cannot be nested within a paragraph, it can only be used as a separate paragraph.)

TIP: See link:/author/topics/document-format/[Document format] section of author’s documentation
for some differences of how Metanorma’s interpretation of basic AsciiDoc features differs
from that of Asciidoctor, and for custom macros Metanorma has added.

[NOTE]
====
Metanorma document model does not impose AsciiDoc/Asciidoctor constraints,
so if desired you can edit the generated XML presentation (say, to break up paragraphs
within a footnote) and subsequently regenerate final deliverables from that edited XML.
====
