---
layout: author-docs
title: Get started
description: >-
  Metanorma installation, samples, customization & usage tips.
html-class: getting-started
redirect_from:
  - /overview/getting-started/
  - /docs/getting-started/
---

== Choose your starting point

If you'd like to *adopt Metanorma for your organization's standard & specification management workflows*,
the best starting point is to customize an existing processor that
matches your requirements best, such as Metanorma-ISO.

* link:/docs/[Learn more] about Metanorma's features
aiming to help organizations with management of standardization documents

* Check out link:/author/topics/document-format/custom-styling/[Metanorma customization guidelines]

To *author documents compliant with the requirements of certain established standard bodies*,
you may already find an existing Metanorma processor:
see link:/flavors/[Metanorma's officially supported document flavors]


[[install-metanorma]]
== Quick install guide

The simplest way to install Metanorma on any OS is using Docker.

[TIP]
====
If you would rather avoid using Docker, such as for performance / access reasons,
refer to the link:/install/[complete installation guide] that covers
different ways of setting up Metanorma.
====

Steps:

. Install Docker. Get the latest version for your operating system at the https://www.docker.com[Docker website].

. Pull the container:
+
[source,console]
--
docker pull metanorma/metanorma
--

Now you should be able to run Metanorma executable like this:

.Running the Metanorma container on macOS and Linux
[source,console]
--
docker run -v "$(pwd)":/metanorma/ -w /metanorma metanorma/metanorma metanorma compile -t {flavor} -x {output-formats} {my-document-path}
--

.Running the Metanorma container on Windows
[source,console]
--
docker run -v "%cd%":/metanorma/ -w /metanorma metanorma/metanorma metanorma compile -t {flavor} -x {output-formats} {my-document-path}
--

[NOTE]
====
To speed up document generation when using Metanorma in Docker,
it is recommended to specify the `:local-cache-only:` document attribute.
====

// == [tbd]#Write your first standard#
