---
layout: jis-flavor
title: Metanorma for JIS markup
---

== Sections

=== Participant clauses

The membership of the investigative committee for the standard appears before
the table of contents in JIS documents, in tabular form.

The title of the participant clause includes the name of the investigative
committee, and is generated automatically.

NOTE: The name of the investigative committee is set as a
link:/author/jis/ref/document-attributes/[document attribute].

This information is entered in a YAML table within a clause of type
`participants`, with the following structure:

[source,asciidoc]
-----
[type=participants]
== {blank}

[source,yaml]
----
- name:
    surname: Surname 1
    givenname: Given Name 1
  affiliation: Affiliation 1
  role: Role 1 [optional]
- name:
    surname: Surname 2
    givenname: Given Name 2
  affiliation: Affiliation 2
  role: Role 2 [optional]
----
-----

.Entering the JIS participant clause for JIS Z 8301:2019
[example]
====
[source,asciidoc]
-----
[type=participants]
== {blank}

[source,yaml]
----
- name:
    surname: 酒井
    givenname: 信介
  affiliation:  横浜国立大学
  role: 部会長
- name:
    surname: 伊藤
    givenname: 弘
  affiliation: 国立研究開発法人建築研究所
  role: 委員
- name:
    surname: 宇治
    givenname: 公隆
  affiliation: 国立研究開発法人建築研究所
----
-----
====



=== Commentary as appendix

Commentary clauses are marked up as annexes with a `commentary` option attribute:

[source,asciidoc]
----
[appendix%commentary]
== Commentary
...
----


=== Visual appearance for the PDF vertical layout document

By default, almost all text in the vertical layout PDF renders by characters one under one with rotation for 
the reading without the page rotation.

The `span` commands are used to introduce addition markup into the Metanorma text for change this behaviour:

* `span:horizontal` - output text in one line (horizontally)

[source,asciidoc]
----
span:horizontal[JSA]
----

* `span:norotate` - don't rotate the characters, output one under one, but rotated 90 degress clockwise

[source,asciidoc]
----
span:norotate[*JIS Z 8301:2011*]
----

* `span:halffontsize` - output the text with half font size

[source,asciidoc]
----
span:halffontsize[出願公開後の特許出願又は実用新案権]
----
