---
layout: jis-flavor
title: Metanorma for JIS markup
---

== Sections

=== Participant clauses

The membership of the investigative committee for the standard appears before
the table of contents in JIS documents, in tabular form.

By default, the title of the participant clause includes the name of the investigative
committee, and is generated automatically; for that to happen, the title of the clause
must be left blank, as `{blank}`..

NOTE: The name of the investigative committee is set as a
link:/author/jis/ref/document-attributes/[document attribute].

The title of the participant clause is overridden by providing an explicit title for it.
This is necessary if there are more than one participant clauses 
in the document [added in https://github.com/metanorma/metanorma-jis/releases/tag/v0.4.4].

This information is entered in a YAML table within a clause of type
`participants`, with the following structure:

[source,asciidoc]
-----
[type=participants]
== {blank}

[source,yaml]
----
- name:
    surname: Surname 1
    givenname: Given Name 1
  affiliation: Affiliation 1
  role: Role 1 [optional]
- name:
    surname: Surname 2
    givenname: Given Name 2
  affiliation: Affiliation 2
  role: Role 2 [optional]
----
-----

.Entering the JIS participant clause for JIS Z 8301:2019
[example]
====
[source,asciidoc]
-----
[type=participants]
== {blank}

[source,yaml]
----
- name:
    surname: 酒井
    givenname: 信介
  affiliation:  横浜国立大学
  role: 部会長
- name:
    surname: 伊藤
    givenname: 弘
  affiliation: 国立研究開発法人建築研究所
  role: 委員
- name:
    surname: 宇治
    givenname: 公隆
  affiliation: 国立研究開発法人建築研究所
----
-----
====

In order to provide the title of the clause explicitly, `{blank}` is replaced with the desired title:

====
[source,asciidoc]
-----
[type=participants]
== JSA-S1020 Working Group
-----
====

Participation clauses can have a key explaining abbreviations used for roles; this is encoded, as elsewhere
in Metanorma, as a definition list with a `key` option attribute,
following after the sourcecode snippet: [added in https://github.com/metanorma/metanorma-jis/releases/tag/v0.4.4].

====
[source,asciidoc]
-----
[type=participants]
== {blank}

[source,yaml]
----
- name:
    surname: Surname 1
    givenname: Given Name 1
  affiliation: Affiliation 1
  role: GM
----

[%key]
GM:: General Manager
-----
====


=== Commentary as appendix

Commentary clauses are marked up as annexes with a `commentary` option attribute:

[source,asciidoc]
----
[appendix%commentary]
== Commentary
...
----

