---
layout: csa-flavor
---


== Document attributes

[[note_general_doc_ref_doc_attrib_csa]]
[NOTE]
====
Below are listed only document attributes that are unique to Metanorma’s processing of CSA documents.

For _common document attributes_, see link:/author/ref/document-attributes/[Document attributes reference] in general Metanorma author’s documentation. That page describes attributes that apply to all Metanorma flavors, not just CSA

For an _introduction to Metanorma AsciiDoc document attributes_ and how Metanorma uses them, see link:/author/topics/document-format/meta-attributes/[the corresponding topic].
====

`:doctype:`::
*Mandatory.*
The document type (see _CSA deliverables: The different types of CSA publications_).
Permitted types:
`guidance`, `proposal`, `standard`, `report`, `whitepaper`, `charter`, `policy`, `glossary`, `case-study`.

`:status:`::
Document status. Permitted types: `proposal`,
`working-draft`, `committee-draft`, `draft-standard`, `final-draft`,
`published`, `withdrawn`.
Synonym: `:docstage:`.

`:committee:`::
*Mandatory.* Name of relevant CSA technical committee

== Metanorma AsciiDoc markup

* The `+[keyword]#...#+` markup encodes keywords, such as "MUST" and "MUST NOT".
(The result is formatted as `<span class="keyword">...</span>`.)
