---
layout: ietf-flavour
---

= Document attributes

`:doctype:`::
    Set the `doctype` attribute to specify the status of this document.

    - `:doctype: internet-draft` sets the document as an Internet-Draft (default value):
        * `rfc/front/seriesInfo@name` attribute will be set to `Internet-Draft` (in v3)
        * `rfc/front/seriesInfo@value` will be set to the `:name:` attribute, stripping any file suffixes, but including any draft number; e.g. `draft-ietf-somewg-someprotocol-07` (in v3)
        * `rfc@docName` will be set to the `:name:` attribute (in v2)

    - `:doctype: rfc` sets the document as an RFC:
        * `rfc/front/seriesInfo@name` attribute will be set to `RFC` (in v3)
        * `rfc/front/seriesInfo@value` will be set to the `:name:` attribute, stripping the initial `rfc-` prefix and any file suffixes (in v3)
        * `rfc@number` will be set to the `:name:` attribute (in v2)

`:no-rfc-bold-bcp14:`::
Optional. Default value `true`. Allowed values: `true`, `false`.
verride default assumption that boldface uppercase BCP14 word is to be rendered with `bcp14` tag.

`:inline-definition-lists:`::
Optional. Default value `false`. Allowed values: `true`, `false`.
(Only applies to v2. By default, `<vspace blankLines="1">` is inserted after
the definition in a v2 definition list, to satisfy the requirement from `idnits` validation
that definition terms be separated by a carriage return from the definition. That is, by
default inline definition lists are rendered as paragraphing definition lists. If the option is
on, the additional `vspace` element is not added, and inline definition lists are left as is.)
