---
layout: ietf-flavor
---

= Document attributes

`:doctype:`::
Specifies document status. Choices:
+
- `:doctype: internet-draft` sets the document as an Internet-Draft (default value):
    * `rfc/front/seriesInfo@name` attribute will be set to _Internet-Draft_ (in v3)
    * `rfc/front/seriesInfo@value` will be set to the value of `:name:` attribute, stripping any file suffixes, but including any draft number; e.g. _draft-ietf-somewg-someprotocol-07_ (in v3)
    * `rfc@docName` will be set to the `:name:` attribute (in v2)
- `:doctype: rfc` sets the document as an RFC:
    * `rfc/front/seriesInfo@name` attribute will be set to _RFC_ (in v3)
    * `rfc/front/seriesInfo@value` will be set to the value of `:name:` attribute, stripping the initial `rfc-` prefix and any file suffixes (in v3)
    * `rfc@number` will be set to the `:name:` attribute (in v2)
+
Defaults to _internet-draft_.

`:no-rfc-bold-bcp14:`::
Defaults to _true_. Choices: _true_, _false_.
Overrides the default behavior that renders the boldface uppercase BCP14 with `bcp14` tag.

`:inline-definition-lists:`::
Defaults to _false_. Choices: _true_, _false_.
(Only applies to v2. By default, `<vspace blankLines="1">` is inserted after
the definition in a v2 definition list, to satisfy the requirement from `idnits` validation
that definition terms be separated by a carriage return from the definition. That is, by
default inline definition lists are rendered as paragraphing definition lists. If the option is
on, the additional `vspace` element is not added, and inline definition lists are left as is.)
