---
layout: itu-flavor
title: Supported ITU publications in Metanorma
---

Metanorma supports the publication of a vast number of ITU document types,
and all document types now support the new ITU cover page layout.

In line with ITU policy, Metanorma supports the internalization of the cover
page into all 6 official languages of the ITU, namely, Arabic, Chinese, English,
French, Russian, and Spanish.

For details on how to create ITU documents in Metanorma, refer to the
link:/author/itu/[Authoring for ITU] page.


.List of supported ITU documents in Metanorma
[cols="a,a,a,a",options="header"]
|===
| Document type | ITU-D | ITU-T | ITU-R

| Technical
|
* Recommendations
|
* Recommendations
* Technical Papers
* Technical Reports
* Supplements
* Handbooks
* Focus Group publications
* Resolutions
* Implementers Guide
|
* Recommendations
* Reports
* Handbooks
* Resolutions

| Flagship
|
|
|
* Service publication

|===

NOTE: The "Recommendation" type includes the related types such as
amendment, supplement, etc.

NOTE: See link:/author/itu/ref/document-attributes/[ITU document attributes] for
full details.

Metanorma supports the "document scheme" concept for a number of organizations,
allowing documents to appear in different layout schemes. This is now
implemented for ITU differentiating the pre-2021 and the 2021 layouts.

The document attribute `:document-scheme:` allows to specify the layout of
an ITU document:

* `current` (new default) identifies the 2021 ITU layout.
* `legacy` identifies the pre-2021 ITU layout.

The new ITU cover page contains some new elements not previously in the legacy
layout. The corresponding document attributes that affect those elements are now
present in Metanorma.

The following document attributes are now supported for all documents:

`:collection-title:`:: The collection of documents that this document
appears in. Accepts a text value. Appears on the top left of the cover page.

`:sector:`:: Standardization sector that publishes the document, if the document
is published outside of the defined bureaus. Only use this attribute if it does
not belong to the ITU-{D/R/T} sectors, otherwise use `:bureau:` instead.

Flagship publications require a few additional document attributes.

NOTE: The only flagship publication currently supported in Metanorma is the
Service Publication.

`:coverpage-image:`:: Cover page image for PDF output. Accepts comma-delimited
list of image locations (and title page for logos). The first image will be
applied on the cover page. The second image will apply to the inner cover.
+
Recommend using a one-paged PDF for the cover page image.
+
Image files referenced shall be in supported image formats including PNG, JPEG,
GIF, SVG, or in PDF.
The image locations are relative to the source root document.
+
The cover page image should contain also event, partner and co-publisher logos
(if applicable). There is no need to include the ITU logo at the right bottom
corner as it is inserted by Metanorma. If there is insufficient space on the
cover to include all the logos, then specify the second image location to render
them on the inner cover page.

`:presentation-metadata-color-cover-title:`:: Title color on PDF cover. Valid values
are `black` (default) or `white`. Select depend on the contrast with the background.

`:presentation-metadata-cover-header-hide:`:: Whether to hide page header titles.
The header titles are the "ITUPublications", "International Telecommunication Union", with the Sector or Bureau name on the cover page. Valid values: `false` (default) or `true`.
Some Flagship publications opt to omit the cover page header.

`:presentation-metadata-color-cover-itu-logo:`:: Color of the ITU logo. Typically `#1DA0DB` (default) or 'white' depending on the contrast with background.

`:slogan-title:`:: Slogan that this document is branded with, in connection with
an event. Some Flagship publications allow the slogan title.
+
[NOTE]
--
When using the slogan title, be aware that the ITU official style guide
specifies proprietary fonts for the slogan title that are not freely available
cross-platforms.

* "Adelle Italic" for Latin and Cyrillic scripts;

* "Traditional Arabic" for Arabic;

* "STKaiti" for Chinese.

These are fonts that Fontist cannot directly install, and the user is responsible
for pre-installing them on their machine.
--

== Working with proprietary fonts for the Flagship slogan title

Flagship publications are allowed a "slogan title" that utilizes proprietary
fonts.

Fontist is unable to install (does not support) those fonts since they are
only available on proprietary platforms.

Specifically:

* "Adelle Italic" is a proprietary font on all platforms. On macOS, the
macOS-licensed font "Adelle Devanagari" can serve as an identical and free
substitution of "Adelle Italic". "Adelle Devanagari" has to be installed via
the macOS Font Book as an add-on.

* "Traditional Arabic" is a Microsoft-licensed font that comes by default on
Windows and Office;

* "STKaiti" is a Microsoft-licensed font only provided by Office.

This means in order to comply with the ITU branding guidelines, the user
must pre-install these fonts on their machine manually. Once these fonts are
available in the system, Fontist will find these fonts pass them into the
Metanorma PDF production tool (`mn2pdf`).

Since the slogan title is rarely used, these fonts are not specified internally
in the font manifest of Metanorma for ITU, and require manual specification
via the
link:/author/ref/document-attributes/#visual-appearance[`:fonts:` document attribute].

.Using proprietary fonts for the Flagship slogan title
[example]
====
[source,adoc]
----
= World Radiocommunication Conference 2019 (WRC-19)
:slogan-title: Provisional Final Acts
:fonts: Adelle Devanagari, Traditional Arabic, STKaiti

// body content
----
====