---
layout: tutorial
title: Term definitions
---
:page-liquid:
//Revise whole section
If you want to cite a term throughout the standard, include it in the terms and definitions section. Term definitions vary from definition lists, as they are more granular and provide metadata to mark features such as alternative terms or deprecated terms. 
Let’s have a look at a term entry:

[source, AsciiDoc]
----
== Terms and definitions <1>

=== husked rice <2>
deprecated:[cargo rice] <3>

Paddy from which the husk only has been removed. <4>

[.source] <5>
<<ISO7301,clause 3.2>>, The term "cargo rice" is shown as deprecated, and Note 1 to entry is not included here

=== milled rice
alt:[white rice] <6>

term:[husked rice] from which almost all of the bran and embryo have been removed by milling. <7>

=== extraneous matter
alt:[EM]
domain:[rice] <8>

organic and inorganic components other than whole or broken kernels

[example] <9>
Foreign seeds, husks, bran, sand, dust.
----
<1> The start of the terms and definitions section
<2> The term that should be defined is marked as a subheading using three equal signs. `===`.
<3> The term `husked rice` supersedes `cargo rice`. To document the old term, use the annotation `deprecated:[term]`.
<4> Definition for the term: the first paragraph of text after macros like `deprecated:[]` and `alt:[]`.
<5> The `[.source]` attribute indicates that a citation follows, indicating where the term definition has been taken from. Make sure to include the dot `.` before source, so that the citation will be rendered correctly. 
<6> `alt:[white rice]` indicates the alternative term for milled rice. 
<7> `term:[husked rice]` cites the previously introduced term.
<8> Terms that do not obviously belong to a certain domain can be annotated with `domain:[]` at the start of their definition.
<9> If you provide an example, use the `[example]` attribute so that it renders according to the styling rules of your SDO. 


=== Practice time

{% include_relative /exercises.adoc content="exercise-2-3-2" %}

The next type of block we will cover are tables.
//Button