---
layout: tutorial
title: Editing a Metanorma document - Introduction to AsciiDoc
---
[[learning-objectives-2]]
Before we write our first Metanorma document, let us look at the foundation for all Metanorma documents: AsciiDoc. 

In this lesson, you will learn:

* What AsciiDoc is 
* Which elements a typical Metanorma document contains
* How to write and format text with AsciiDoc

//include::/author/concepts/intro_to_asciidoc.adoc[tag=tutorial, leveloffset=+2]

== Introduction to Metanorma AsciiDoc

Each Metanorma document is written in AsciiDoc, a markup language that annotates text with processing instructions for layout. Since AsciiDoc only consists of text, you can use any editor to create AsciiDoc files (`.adoc` files). AsciiDoc is very similar to Markdown or Wiki formatting but provides more precise markup for creating text documents, for example to create a bibliography section or an index.

Because Metanorma fulfills the markup requirements of SDOs, Metanorma extends plain AsciiDoc. This version of AsciiDoc is called Metanorma AsciiDoc. 

An AsciiDoc document consists of different levels of granularity:

* The document head (also called the header)
* Sections
* Blocks
* Inline markup

//This is not part of the include
We will have a look at these different levels of markup in the following lessons and you can do exercises on your local machine.

=== Prerequisites

* link:/installation/[Install Metanorma]
+
TIP: Use Metanorma in Docker to get started faster. 
* Download the https://github.com/metanorma/metanorma-tutorial[Metanorma tutorial project]. 


+++
<div class="cta tutorial"><a class="button" href="/tutorial/lessons/lesson-2-1/">Start next lesson »</a></div>
+++