---
layout: author-docs
description: >-
  <p>
  This is a general guidance for authoring Metanorma documents.

  <p>
  Since Metanorma uses AsciiDoc markup
  (see <a href="../approach/">Approach</a>) for technical background),
  a lot of this section deals with Metanorma’s interpretation of AsciiDoc.

  <p>
  If you are using one of the
  <a href="/flavours/">officially supported flavours of Metanorma</a>,
  be sure to also check out guidelines for your flavour.
---

= Metanorma document format reference

== How does authoring with AsciiDoc work, for&nbsp;beginners

The AsciiDoc approach Metanorma suggests for authoring standards
is not WYSIWYG—meaning that you’ll be dealing with a plain-text editor and a command line,
rather than something that resembles, say, a Microsoft Word document.

The text you’ll be authoring would look more like HTML or Markdown,
and it will be formatted like the end document during build stage.

This might look confusing at first, but the upside, in our opinion, far outweighs that:
with documents formatted using semantic markup like Asciidoctor
it is much easier to automate key validation and formatting processes
such as checking for missing document components, automatic numbering,
and generating output in multiple formats from one source text.

If you are new to AsciiDoc (and maybe if you aren’t),
you are encouraged to use the http://asciidoctor.org/docs/user-manual/[Asciidoctor manual]
alongside this guidance.
