---
layout: rsd-flavor
---

= Using Metanorma-RSD

== Document attributes

[[note_general_doc_ref_doc_attrib_rsd]]
[NOTE]
====
Below are listed only document attributes that are unique to Metanorma’s processing of RSD documents.

For _common document attributes_, see link:/author/ref/document-attributes/[Document attributes reference] in general Metanorma author’s documentation. That page describes attributes that apply to all Metanorma flavors, not just RSD.

For an _introduction to Metanorma AsciiDoc document attributes_ and how Metanorma uses them, see link:/author/topics/document-format/meta-attributes/[the corresponding topic].
====

`:security:`::
Security level classification. For example, "confidential", "client confidential"

`:doctype:`::
*Mandatory.* Document type (see RSD deliverables: The different types of
RSD publications). Permitted types:
+
--
* policy-and-procedures
* best-practices
* supporting-document
* report
* legal
* directives
* proposal
* standard
--

`:status:``::
Document status. Synonym: `:docstage:`.
Permitted types: `proposal`, `working-draft`, `committee-draft`, `draft-standard`, `final-draft`,
`published`, `withdrawn`

`:committee:`::
*Mandatory.* Name of relevant RSD committee

`:committee-type:`::
*Mandatory.* Type of relevant RSD committee. Could be `technical`
or `provisional`

== Markup features

* `+[keyword]#...#+`: encodes keywords, such as "MUST", "MUST NOT". (Encoded as
`<span class="keyword">...</span>`.
