---
layout: rsd-flavor
---

= Using Metanorma-RSD

== Document attributes

[[note_general_doc_ref_doc_attrib_rsd]]
NOTE: The list of document attributes supported by all flavors of Metanorma can be seen in link:/author/ref/document-attributes[Document attributes] section in general Metanorma documentation.

`:security:`::
Security level classification. For example, "confidential", "client confidential"

`:doctype:`::
*Mandatory.* Document type (see RSD deliverables: The different types of
RSD publications). Permitted types:
+
--
* policy-and-procedures
* best-practices
* supporting-document
* report
* legal
* directives
* proposal
* standard
--

`:status:``::
Document status. Synonym: `:docstage:`.
Permitted types: `proposal`, `working-draft`, `committee-draft`, `draft-standard`, `final-draft`,
`published`, `withdrawn`

`:committee:`::
*Mandatory.* Name of relevant RSD committee

`:committee-type:`::
*Mandatory.* Type of relevant RSD committee. Could be `technical`
or `provisional`

== Markup features

* `+[keyword]#...#+`: encodes keywords, such as "MUST", "MUST NOT". (Encoded as
`<span class="keyword">...</span>`.
