---
layout: iso-flavour
title: "Metanorma sample: AsciiISO Rice"
---

To check out Metanorma-ISO capabilities, you can take a look at the Rice model
sample document formatted as a Metanorma-ISO project.
We also call it “AsciiISO Rice”, where “AsciiISO” is the name of link:../markup/[markup]
used to author Metanorma-ISO documents.

== Build

You can obtain the AsciiISO Rice document source
from its https://github.com/riboseinc/isodoc-rice/[GitHub repository],
and see it in the rendered form on its https://riboseinc.github.io/isodoc-rice/[GitHub page].

To build the document via the provided Makefile, simply run `make` from within
the sample directory.

[NOTE]
====
By default, `make` expects that  `metanorma` binary is available somewhere on your path.

If you are using Docker-based distribution of Metanorma,
run `export METANORMA_DOCKER=1`, then `make` will invoke Metanorma through Docker container.

- See link:/docs/getting-started/#install-metanorma[Getting started]
  for the different ways of getting the Metanorma toolchain set up.
====

== Customize

You can use the sample as a starting point for authoring your own ISO documents with Metanorma.
To make it easier, refer to the https://github.com/riboseinc/isodoc-rice/[README]
for an overview of how the source is structured.
