---
layout: ietf-flavor
---

= Output formats

[[note_general_doc_ref_output-formats]]
NOTE: This section supplements link:/author/topics/building/output-formats[Output formats] in general Metanorma documentation.

The following outputs are generated [added in https://github.com/metanorma/metanorma-ietf/releases/tag/v2.0.0]:

* RFC XML v3
** Metanorma `doctype`: `ietf` (in previous versions: `rfc3`)
** Metanorma file extension: `rfc.xml` (not `xml`! That is the suffix for Metanormal XML)
** Format name: `rfc` (used in `:mn-output-extensions:` attribute, in `metanorma -x`, and in passthrough blocks to nominate RFC XML as their target.)

The "`xml2rfc`" Vocabulary (hereinafter "`RFC XML`") is an XML-based language
used for writing
https://www.ietf.org/id-info/guidelines.html[Internet-Drafts]
and https://tools.ietf.org/html/rfc7322[RFCs (RFC7322)].

Metanorma-IETF allows you to author these types of documents in AsciiDoc, and outputs
RFC XML output in the RFC XML format, which is consumed by IETF software like `xml2rfc`
link:../output-formats[IETF software discussion]) to generate
formatted IETF specifications. If `metanorma -x` or the `:mn-output-extensions:` attribute
are invoked with `html`, `pdf`, or `txt`, those formats are generated through `xml2rfc`
instead of metanorma itself.

* RFC XML v3 is defined in
https://tools.ietf.org/html/rfc7991[RFC 7991], supplemented by
https://tools.ietf.org/html/draft-levkowetz-xml2rfc-v3-implementation-notes-10[Levkowetz' implementation notes]

Previous versions of this gem supported RFC XML v3 as it was defined in RFC 7991 in 2016, but
without the additions and modifications documented in Levkowetz' implementation notes. The
v3 output of those versions will not compile under the `xml2rfc` releases that actually support v3.

Previous versions of this gem supported RFC XML v2 (https://tools.ietf.org/html/rfc7749[RFC 7749]):

* RFC XML v2
** Metanorma `doctype`: `rfc2`
** Metanorma file extension: `xmlrfc` (not `xml`!)

IETF is moving to RFC XML v3 as its main format, and Metanorma will only be supporting RFC XML v3
from now on:


NOTE: IETF support of RFC XML v3 is quite new, and v3 should be used with some caution. The
IETF processing tools that consume RFC XML v3 are still under development; Metanorma will be
endeavouring to keep Metanorma-IETF up to date with changes to Levkowetz' implementation notes.

NOTE: Metanorma-IETF validates all RFC XML generated through the RELAXNG schema definitions
of RFC XML. While Metanorma attempts to generate valid RFC XML, some AsciiDoc
markup may not align with the RFC XML document model, and any highlighted syntax
errors will also need to be rectified in postediting, before processing the
generated XML further.
