---
layout: ietf-flavor
---

= Output formats

The following outputs are generated:

* RFC XML v2
** Metanorma `doctype`: `rfc2`
** Metanorma file extension: `xmlrfc` (not `xml`!)

* RFC XML v3
** Metanorma `doctype`: `rfc3`
** Metanorma file extension: `xmlrfc` (not `xml`!)

The "`xml2rfc`" Vocabulary (hereinafter "`RFC XML`") is an XML-based language
used for writing
https://www.ietf.org/id-info/guidelines.html[Internet-Drafts]
and https://tools.ietf.org/html/rfc7322[RFCs (RFC7322)].

Metanorma-IETF allows you to author these types of documents in AsciiDoc, and outputs
RFC XML output in both v3 and v2 formats:

* v3 RFC XML (https://tools.ietf.org/html/rfc7991[RFC 7991])
* v2 RFC XML (https://tools.ietf.org/html/rfc7749[RFC 7749])

NOTE: Metanorma-IETF validates all RFC XML generated through the RELAXNG schema definitions
of RFC XML. While Metanorma attempts to generate valid RFC XML, some AsciiDoc
markup may not align with the RFC XML document model, and any highlighted syntax
errors will also need to be rectified in postediting, before processing the
generated XML further.
