---
layout: docs
---

= Metanorma authoring reference

This is a general guidance for authoring Metanorma documents.

Since Metanorma uses AsciiDoc markup (see link:../approach/[Approach] for technical background),
a lot of this section deals with Metanorma’s interpretation of AsciiDoc.

If you are using one of the link:/flavours/[officially supported flavours of Metanorma],
be sure to also check out guidelines for your flavour.

== How does authoring with AsciiDoc work, for&nbsp;beginners

The AsciiDoc approach Metanorma suggests for authoring standards
is not WYSIWYG—meaning that you’ll be dealing with a plain-text editor and a command line,
rather than something that resembles, say, a Microsoft Word document.

The text you’ll be authoring would look more like HTML or Markdown,
and it will be formatted like the end document during build stage.

This might look confusing at first, but the upside, in our opinion, far outweighs that:
with documents formatted using semantic markup like Asciidoctor
it is much easier to automate key validation and formatting processes
such as checking for missing document components, automatic numbering,
and generating output in multiple formats from one source text.

If you are new to AsciiDoc (and maybe if you aren’t),
you are encouraged to use the http://asciidoctor.org/docs/user-manual/[Asciidoctor manual]
alongside this guidance.

== Contents

- Validation. Metanorma is capable of checking various aspects of your document,
  and it will output warning and errors during build stage

- Output in different languages

- Asciidoctor document header

- Document sections

- Text markup (footnotes, lists, tables, and so on)

- Asciidoctor tips that may be useful when authoring Metanorma documents
