---
layout: docs
title: Get started
description: >-
  Metanorma installation, samples, customization & usage tips.
html-class: getting-started
redirect_from:
  - /overview/getting-started/
---

== Choose your starting point

If you'd like to *adopt Metanorma for your organization's standard & specification management workflows*,
the best starting point is to customize an existing processor that
matches your requirements best, such as Metanorma-ISO.

* link:/docs/[Learn more] about Metanorma's features
aiming to help organizations with management of standardization documents

* Check out link:/docs/customization/[Metanorma customization guidelines]

To *author documents compliant with the requirements of certain established standard bodies*,
you may already find an existing Metanorma processor:
see link:/flavours/[Metanorma’s officially supported document flavours]


== Install Metanorma

To be able to build Metanorma documents of any flavour, you need to have the
`metanorma-cli` Ruby gem installed.
To simplify installation of the gem and its dependencies,
following installation methods are currently supported.

[[docker-setup]]
=== Docker setup

This setup method works for all platforms that support the Docker container
framework.

[TIP]
====
This method is the recommended way of getting Metanorma installed, although
for certain reasons (such as performance)
that you may wish to setup the components directly on your machine.
====

. Pull the container:
+
[source,sh]
----
docker pull ribose/metanorma
----
. Specify the `:local-cache-only:` AsciiDoc attribute
in document header to speed up rendering
. To render the document into HTML, Word and XML,
execute from within the directory containing the Metanorma document
(replacing `{my-document-file}` with your actual document's filename):
+
[source,sh]
----
docker run -v "$(pwd)":/metanorma/ -w /metanorma ribose/metanorma "metanorma -t iso -x html,doc,xml {my-document-file}"
----


See https://github.com/riboseinc/metanorma-docker[metanorma-docker] for more information
and some shortcuts, including a pre-made Makefile.


[[macos-setup]]
=== macOS setup: Homebrew

[source,sh]
----
brew tap riboseinc/metanorma
brew install metanorma
----

This uses Metanorma’s link:/software/homebrew-metanorma[Homebrew formula].
To install using the HEAD development version of the formula, run:

[source,sh]
----
brew install --HEAD https://raw.githubusercontent.com/riboseinc/homebrew-metanorma/master/metanorma.rb
----


=== macOS setup: all-in-one script

Run the following for an automatic install
that would prepare a fresh system to work with Metanorma.

NOTE: This installs not just the Metanorma components, but also prerequisites
such as Homebrew and basic tools like Sublime Text.

This should take less than 15 minutes depending on your machine and Internet connection:

[source,sh]
----
bash <(curl -s https://raw.githubusercontent.com/riboseinc/metanorma-macos-setup/master/metanorma-setup)
----


=== Linux setup: Ubuntu

Run the following for an automatic install via the https://github.com/riboseinc/metanorma-linux-setup[metanorma-linux-setup] scripts.

This should take less than 15 minutes depending on your machine and Internet connection:

[source,sh]
----
# Prerequisites: "curl"
# apt-get update && apt-get install -y curl
sudo bash -c "curl -L https://raw.githubusercontent.com/riboseinc/metanorma-linux-setup/master/ubuntu.sh | bash"
curl -L https://raw.githubusercontent.com/riboseinc/metanorma-linux-setup/master/install-gems.sh | bash
----

=== Linux setup: CentOS

Run the following for an automatic install via the https://github.com/riboseinc/metanorma-linux-setup[metanorma-linux-setup] scripts.

This should take less than 15 minutes depending on your machine and Internet connection:

[source,sh]
----
# Prerequisites: "curl"
# yum install -y curl
sudo bash -c "curl -L https://raw.githubusercontent.com/riboseinc/metanorma-linux-setup/master/centos.sh | bash"
curl -L https://raw.githubusercontent.com/riboseinc/metanorma-linux-setup/master/install-gems.sh | bash
----

=== Windows setup

Run this command in your `cmd.exe` or `PowerShell` to install
the Metanorma Docker container and all prerequisites (see <<docker-setup>>):

[source,sh]
----
bitsadmin /transfer get https://raw.githubusercontent.com/riboseinc/metanorma-windows-setup/master/install.bat %cd%\install.bat & .\install.bat
----

If you'd like to do one of the following instead,
please refer to
https://github.com/riboseinc/metanorma-windows-setup[metanorma-windows-setup]:

* setup the Metanorma Docker container manually; or
* setup the Metanorma toolchain directly on your Windows machine.


=== Installing individual components

You can also link:/software/metanorma-cli/docs/installation[install Metanorma command-line tool]
as a gem on its own, but be sure to note the dependencies.

== [tbd]#Write your first standard#

