---
layout: docs
title: Get started
description: >-
  Metanorma installation, samples, customization & usage tips.
html-class: getting-started
---

== Introduction

If you'd like to *adopt Metanorma for your organization's standard & specification management workflows*,
the best starting point is to customize an existing processor that
matches your requirements best, such as Metanorma-ISO.

* Check out link:/software/metanorma-iso/[Metanorma-ISO docs]
for customization tips

* link:/overview/[Learn more] about Metanorma's features
aiming to help organizations with management of standardization documents

* See Metanorma ecosystem's existing link:/software/Sample_processor/[example processors]
and link:/software/For_enterprises/[enterprise processors]

To *author documents compliant with the requirements of certain established standard bodies*,
you may already find an existing Metanorma processor -- see corresponding authoring documentation
and document samples:

[cols="h,a,a"]
|===
|Processor |Docs |Samples

|ISO documents
| link:/software/metanorma-iso/docs/guidance/[Authoring quickstart]
| https://github.com/riboseinc/isodoc-rice[ISO Rice document]

|IETF RFC/Internet-Drafts
| https://github.com/riboseinc/asciidoctor-rfc[README]
| link:/samples/draft-camelot-holy-grenade/[Camelot]

|CalConnect CSD
| link:/software/metanorma-csd/docs/quickstart/[Authoring quickstart]
| https://github.com/CalConnect/csd-calspam-bcp[CC/R 18003]

|Cloud Security Alliance CSAND
| https://github.com/riboseinc/metanorma-csd[README]
| https://github.com/riboseinc/csand-devsecops-whitepaper[DevSecOps Whitepaper]

|UN/ECE Recommendations/Plenary
| https://github.com/riboseinc/metanorma-unece[README]
| https://github.com/riboseinc/unece-cefact-recommendation-42[UN/CEFACT Recommendation 42]

|Chinese Standards
| https://github.com/riboseinc/metanorma-gb[README]
| https://github.com/riboseinc/gmt-0009-2012/[GM/T 0009-2012 translation]

|M3AAWG
| link:https://github.com/riboseinc/metanorma-m3d[README]
| [tbd]#Sample#

|===


== Installing the Metanorma toolchain

=== General

We strongly recommend the <<docker-setup>> due to the number of components
involved in Metanorma.

On the other hand, there are certain reasons (such as performance)
that you may wish to setup the components on your machine.


[[docker-setup]]
=== Docker setup

This setup method works for all platforms that support the Docker container
framework.

. Pull the container:
+
[source,sh]
----
docker pull ribose/metanorma
----
. Specify the `:local-cache-only:` AsciiDoc attribute
in document header to speed up rendering
. To render the document into HTML, Word and XML,
execute from within the directory containing the Metanorma document
(replacing `{my-document-file}` with your actual document's filename):
+
[source,sh]
----
docker run -v "$(pwd)":/metanorma/ -w /metanorma ribose/metanorma "metanorma -t iso -x html,doc,xml {my-document-file}"
----


See https://github.com/riboseinc/metanorma-docker[metanorma-docker] for more information
and some shortcuts, including a pre-made Makefile.

=== macOS setup: all-in-one

Run the following for an automatic install
that would prepare a fresh system to work with Metanorma.

NOTE: This installs not just the Metanorma components but also prerequisites
such as Homebrew and basic tools like Sublime Text.

This should take less than 15 minutes depending on your machine and Internet connection:

[source,sh]
----
bash <(curl -s https://raw.githubusercontent.com/riboseinc/metanorma-macos-setup/master/metanorma-setup)
----


=== Linux setup: Ubuntu

Run the following for an automatic install via the https://github.com/riboseinc/metanorma-linux-setup[metanorma-linux-setup] scripts.

This should take less than 15 minutes depending on your machine and Internet connection:

[source,sh]
----
# Prerequisites: "curl"
# apt-get update && apt-get install -y curl
sudo bash -c "curl -L https://raw.githubusercontent.com/riboseinc/metanorma-linux-setup/master/ubuntu.sh | bash"
curl -L https://raw.githubusercontent.com/riboseinc/metanorma-linux-setup/master/install-gems.sh | bash
----

=== Linux setup: CentOS

Run the following for an automatic install via the https://github.com/riboseinc/metanorma-linux-setup[metanorma-linux-setup] scripts.

This should take less than 15 minutes depending on your machine and Internet connection:

[source,sh]
----
# Prerequisites: "curl"
# yum install -y curl
sudo bash -c "curl -L https://raw.githubusercontent.com/riboseinc/metanorma-linux-setup/master/centos.sh | bash"
curl -L https://raw.githubusercontent.com/riboseinc/metanorma-linux-setup/master/install-gems.sh | bash
----

=== Windows setup

Run this command in your `cmd.exe` or `PowerShell` to install
the Metanorma Docker container and all prerequisites (see <<docker-setup>>):

[source,sh]
----
bitsadmin /transfer get https://raw.githubusercontent.com/riboseinc/metanorma-windows-setup/master/install.bat %cd%\install.bat & .\install.bat
----

If you'd like to do one of the following instead,
please refer to
https://github.com/riboseinc/metanorma-windows-setup[metanorma-windows-setup]:

* setup the Metanorma Docker container manually; or
* setup the Metanorma toolchain directly on your Windows machine.


=== Installing individual components

* link:/software/metanorma-cli/docs/installation[Install Metanorma command-line tools (CLI)]
* link:/software/metanorma-iso/docs/quickstart/[Install the Metanorma-ISO processor]

== [tbd]#Write your first standard#

