= Sample document: Rice
Author
:technical-committee: Food products
:fullname: Author Name
:mn-document-class: standoc
:doctype: document
:language: en
:created-date: 2021-07-31
:copyright-holder: Ribose Inc.
:copyright-year: 2021

...
== Test report

For each test method, the test report shall specify the following:
// Turn into ordered list
all information necessary for the complete identification of the sample;
a reference to this document (i.e. ISO {docnumber}-{partnumber});
the sampling method used;
the test method used;
the test result(s) obtained or, if the repeatability has been checked, the final quoted result obtained;
all operating details not specified in this document, or regarded as optional, together with details of any incidents which may have influenced the test result(s);
any unusual features (anomalies) observed during the test;
the date of the test.

== Terms

=== extraneous matter
alt:[EM]
domain:[rice]

organic and inorganic components other than whole or broken kernels

[example]
====
Foreign seeds 
husks 
bran 
sand 
dust
====

== Definitions

Precision is a description of random errors, a measure of statistical variability.
Accuracy is a description of systematic errors, a measure of statistical bias; low accuracy causes a difference between a result and a "true" value.
Volumetric water content θ is defined as the ratio between volume of water and the volume of the total mass. 


