= Sample document: Rice
Author
:technical-committee: Food products
:fullname: Author Name
:mn-document-class: standoc
:doctype: document
:language: en
:created-date: 2021-07-31
:copyright-holder: Ribose Inc.
:copyright-year: 2021

//Enter foreword section here

The procedures used to develop this document and those intended for its further maintenance are described in the ISO/IEC Directives, Part 1. In particular the different approval criteria needed for the different types of ISO documents should be noted. This document was drafted in accordance with the editorial rules of the ISO/IEC Directives, Part 2 (see www.iso.org/directives).

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. ISO shall not be held responsible for identifying any or all such patent rights. Details of any patent rights identified during the development of the document will be in the Introduction and/or on the ISO list of patent declarations received (see www.iso.org/patents).

Any trade name used in this document is information given for the convenience of users and does not constitute an endorsement.

//Enter introduction section here

This document was developed in response to worldwide demand for minimum specifications for rice traded internationally, since most commercial bulks of grain, which have not been screened or aspirated, contain a proportion of other grains, weed seeds, chaff, straw, stones, sand, etc. The vegetable materials can have physical and biological properties which differ from those of the main constituent and can therefore affect the storage behaviour. 

...

//Enter terms and definitions section here


=== paddy
alt:[paddy rice]
alt:[rough rice]

rice retaining its husk after threshing

=== husked rice
deprecated:[cargo rice]

term:[paddy] from which the husk only has been removed


=== milled rice
alt:[white rice]

term:[husked rice] from which almost all of the bran and embryo have been removed by milling

== Specifications

=== General, organoleptic and health characteristics

Kernels of rice, whether parboiled, husked or milled, and whether whole or broken, shall be sound, clean and free from foreign odours or odour which indicates deterioration.

The levels of additives and pesticide residues and other contaminants shall not exceed the maximum limits permitted in the country of destination.

The presence of living insects which are visible to the naked eye is not permitted. This should be determined before separating the bulk sample into test samples.

...


//Enter bibliography section here



* [[[ISO3696,ISO 3696]]], _Water for analytical laboratory use -- Specification and test methods_

* [[[ISO5725-1,ISO 5725-1]]], _Accuracy (trueness and precision) of measurement methods and results -- Part 1: General principles and definitions_

* [[[ISO5725-2,ISO 5725-2]]], _Accuracy (trueness and precision) of measurement methods and results -- Part 2: Basic method for the determination of repeatability and reproducibility of a standard measurement method_