---
layout: author-docs
---

= Metanorma AsciiDoc tips

Metanorma AsciiDoc adopts Asciidoctor syntax for AsciiDoc, and the
http://asciidoctor.org/docs/user-manual/[Asciidoctor User Manual] is an
excellent companion when authoring Metanorma AsciiDoc documents.

There are some more specialized aspects of Asciidoctor markup,
which you might need to dig deeper to find in the manual; we list some of them here.


== Multi-paragraph footnotes

Metanorma AsciiDoc (and Asciidoctor) supports only single-paragraph
footnotes through its footnote macro
(which can only contain a single line of text).

This is due to a stylistic bias against digressive text by the
Asciidoctor project, and probably will not change.

This can be worked around by introducing line breaks into the macro. See:

- https://github.com/asciidoctor/asciidoctor.org/issues/599
- http://discuss.asciidoctor.org/footnotes-with-paragraph-breaks-td4130.html


== Complex notes and admonitions

A note or admonition can be made to span multiple paragraphs (including lists and tables)
by making it a https://asciidoctor.org/docs/user-manual/#delimited-blocks[delimited block]:

[source,asciidoc]
--
[NOTE]
====
This is a multi-paragraph note.

It includes:

* A list

|===
| And

| a table
|===
====
--

== Attribute references

https://asciidoctor.org/docs/user-manual/#using-attributes-set-assign-and-reference[Attribute references]
can be used as template variables in a document:
if your document contains the text `{foo}`,
you can assign the value to be populated in `{foo}`
by setting it as a document attribute in the Metanorma AsciiDoc header:
`:foo: this is the text to replace "foo"`.

In the AsciiISO Rice model sample document, document attributes are used
to provide the Subcommittee and Technical Committee names, which are populated
as template entries in the document foreword.

See also: link:/author/topics/document-format/meta-attributes/[Document attributes].

== List items with complex contents

List items can contain other blocks in Metanorma AsciiDoc through
concatenating blocks; for example:

[source.asciidoc]
--
* List
+
|===
| Contains | A table

|===
--

However, output formatters (such as MS Word) may not be able to cope with embedding blocks
within list items.

In particular, Microsoft Word will force a carriage return between a list item,
and a list or table contained in the item.

This means the output like follows, with the list number flush with the embedded block,
is not possible in Microsoft Word (though it is in HTML):

....
a)  1. Text
b)  |-------|------ |
    | table | table |
    |---------------|
c)  Definition Term   Definition
    Definition Term   Definition
....

[[asciidoc_escaping]]
== AsciiDoc escaping

There are some characters that constitute markup in Metanorma AsciiDoc
//(and Asciidoctor AsciiDoc),
and need to be escaped if they will be used in text (usually by putting a backslash before them).

That applies in particular to:

* period at the start of a line, which will be interpreted as a block title;

* open bracket at the start of a line, which will be interpreted as a style attribute;

* close bracket inside of a macro (such as footnotes), which are themselves delimited by a close bracket;

* a number followed by period at the start of a line, which will be interpreted as a numbered
list. (This does not happen inside of blocks like examples.)

Sometimes, a backslash will not be enough to make the character make sense to
Metanorma AsciiDoc markup.
The "`break in case of emergency solution`" is to make the troublesome span of text
a document attribute, since document attributes are skipped over when processing
Metanorma AsciiDoc markup, and processed only at the very end.

See for example https://asciidoctor.org/docs/user-manual/#url[the Asciidoctor User Manual]
on using document attributes to deal with complex URLs.

== Document attributes
As just noted (<<asciidoc_escaping>>), document attributes are skipped over
when processing Metanorma AsciiDoc markup. That means that markup you would
normally expect to be processed is ignored if present in a document attribute.
That includes not only inline markup such as boldface and italics, but also
mathematical formatting, and footnotes. It also includes text substitutions such
as smart quotes and `--` for em-dash, although Metanorma does go back separately
and reimpose smart quotes and `--` as em-dash on all text in the document, including
document attribute text. (It ignores source code, pseudocode, and monospace text).

Note that this lack of markup includes document titles and subtitles, which are
populated via document attributes.


