= Sample document: Rice
Author
:technical-committee: Food products
:fullname: Author Name
:mn-document-class: standoc
:doctype: document
:language: en
:created-date: 2021-07-31
:copyright-holder: Ribose Inc.
:copyright-year: 2021

== Introduction
=== Future potential of rice
// Excerpt from https://en.wikipedia.org/wiki/Rice#Biotechnology


As the UN Millennium Development project seeks to spread global economic development to Africa, the "Green Revolution" is cited as the model for economic development. 
With the intent of replicating the successful Asian boom in agronomic productivity, groups like the Earth Institute are doing research on African agricultural systems, hoping to increase productivity. 
An important way this can happen is the production of "New Rices for Africa" (NERICA). 
These rices, selected to tolerate the low input and harsh growing conditions of African agriculture, are produced by the African Rice Center, and billed as technology "from Africa, for Africa". 
The NERICA have appeared in The New York Times (October 10, 2007) and International Herald Tribune (October 9, 2007), trumpeted as miracle crops that will dramatically increase rice yield in Africa and enable an economic resurgence. 
Ongoing research in China to develop perennial rice could result in enhanced sustainability and food security.

// Add the index section here