---
layout: iho-flavor
title: Terms and definitions
---

Specific terms used in this guide is defined in this section.

== admonition

statement used to draw the attention of the reader by labeling it with a
priority tag

[example]
WARNING, NOTE, TIP.

== boilerplate (also _boilerplate text_)

predefined content that is automatically inserted into the output in accordance
to flavor requirements

== clause (also _section_)

logical group of content that is numerically identified in ascending order

== subclause (also _subsection_)

clause that belongs to a top-level clause or another subclause

== cross-reference

link to a location in the current document or in another external document

== document attribute

key-value pair that specifies execution configuration or
provides metadata at the document level

NOTE: A Metanorma document attribute key-value pair is implemented using the
syntax of `:{key}: {value}`.

== block attribute

key-value pair that specifies execution configuration or provides metadata at
the block level

NOTE: A Metanorma document attribute key-value pair is implemented using the
syntax of `{key}={value}`.

== Metanorma flavor

Metanorma implementation that conforms to a publishing organization's content
model

NOTE: Conformance of content covers validity of content, the content generation
process, and formatting of deliverables.

== Metanorma AsciiDoc

markup syntax for the authoring of standards based on AsciiDoc

== Metanorma template

files that serve as guidance to author a specific document type in IHO flavor

== NesCom

IHO New Standards Committee

== MEC

IHO Mandatory Editorial Coordination, the editorial process for publishing
draft IHO deliverables for ballot

== PAR

Project Authorization Request, first step to starting a WG

== RevCom

IHO Standards Review Committee that approves an SA standard

== SC

IHO Standards Committee

== IHOSB

IHO Standards Board

== WG

IHO Working Group


== CRG

IHO Comment Resolution Group

== Project Number

number of IHO project with an identifier starting with the character "P"

[example]
P6001.14, P2830.

== Draft Number

sequence number of IHO draft with an identifier starting with the character "D"

[example]
P6001.14, P2830.

== Document Number

identifier for an IHO document either with a published document number
or a draft identified by a combination of the project number and draft number

[example]
2830, P6001.14/D3.

== IHO standards document

standardization deliverable produced and recognized by IHO as result
of consensus

== IHO Standard

IHO standards document with mandatory requirements

SOURCE: https://standards.iho.org/wp-content/uploads/import/documents/other/iho_sa_toolkit.pdf[IHO Quick Reference Guide: Standards Development Process]

== IHO Recommended practices

IHO standards document in which procedures and positions preferred by IHO
are presented

SOURCE: https://standards.iho.org/wp-content/uploads/import/documents/other/iho_sa_toolkit.pdf[IHO Quick Reference Guide: Standards Development Process]

== IHO Guide

IHO standards document in which alternative approaches to good practice are
suggested but no clear-cut recommendations are made

SOURCE: https://standards.iho.org/wp-content/uploads/import/documents/other/iho_sa_toolkit.pdf[IHO Quick Reference Guide: Standards Development Process]

These levels of requirements are often shown by the use of particular “standards verbs,” i.e., “shall” for requirements, “should” for recommendations, and “may” for guidelines. (more information can be found in the IHO Standards Board Operations Manual and the IHO Standards Style Manual) Figuring out what level of requirement is needed helps determine what kind of document should be developed.
