---
layout: m3d-flavor
---

= Writing M3AAWG documents using Metanorma

== Document Attributes

[[note_general_doc_ref_doc_attrib_m3d]]
[NOTE]
====
Below are listed only document attributes that are unique to Metanorma’s processing of M3D documents.

For _common document attributes_, see link:/author/ref/document-attributes/[Document attributes reference] in general Metanorma author’s documentation. That page describes attributes that apply to all Metanorma flavors, not just M3D.

For an _introduction to AsciiDoc document attributes_ and how Metanorma uses them, see link:/author/topics/document-format/meta-attributes/[the corresponding topic].
====

`:status:``:: The document status. Synonym: `:docstage:`.
The permitted types are: `proposal`,
`working-draft`, `committee-draft`, `draft-standard`, `final-draft`,
`published`, `withdrawn`.

`:doctype:`:: The document type (see _M3D deliverables: The different types of
M3D publications_) (mandatory). The permitted types are:
+
--
* policy 
* best-practices 
* supporting-document 
* report
--

== Markup

`+[keyword]#...#+`: encodes keywords, such as "MUST", "MUST NOT".
(They are formatted as `<span class="keyword">...</span>`.)
